Repository tari-project/tari-ootle, pull requests merged in 2022-11, with the labels that each got.

#145 feat: base layer scanner should read consensus constants from base layer (see #115)
  Cargo.lock
  applications/tari_validator_node/src/base_layer_scanner.rs
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/epoch_manager_service.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/handle.rs
  applications/tari_validator_node/src/registration.rs
  dan_layer/common_types/src/epoch.rs
  dan_layer/core/src/consensus_constants.rs
  dan_layer/storage/src/global/metadata_db.rs
Labels: P-acks_required, P-reviews_required

#167 feat(tests): create a cucumber test to call Counter::new() function on a VNC
  Cargo.lock
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/basic.feature
  applications/tari_validator_node/tests/features/json_rpc.feature
  applications/tari_validator_node/tests/log4rs/validator_node.yml
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/counter/Cargo.toml
  applications/tari_validator_node/tests/templates/counter/src/lib.rs
  applications/tari_validator_node/tests/utils/base_node.rs
  applications/tari_validator_node/tests/utils/http_server.rs
  applications/tari_validator_node/tests/utils/miner.rs
  applications/tari_validator_node/tests/utils/mod.rs
  applications/tari_validator_node/tests/utils/template.rs
  applications/tari_validator_node/tests/utils/validator_node.rs
  applications/tari_validator_node/tests/utils/wallet.rs
Labels: CR-too_long

#171 fix: vote reject when wasm panics
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  applications/tari_validator_node/src/payload_processor.rs
  applications/tari_validator_node_web_ui/build/index.html
  applications/tari_validator_node_web_ui/public/index.html
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/engine_types/src/commit_result.rs
Labels: P-acks_required, P-reviews_required

#172 feat: return QC to client for submit-transaction calls
  Cargo.lock
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  clients/validator_node_client/Cargo.toml
  clients/validator_node_client/src/types.rs
  dan_layer/common_types/src/epoch.rs
  dan_layer/core/src/workers/events.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
Labels: P-acks_required

#181 fix: check pledges against changes being made
  applications/tari_validator_node/proto/dan/consensus.proto
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/proto/conversions/consensus.rs
  applications/tari_validator_node/src/payload_processor.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  clients/validator_node_client/src/types.rs
  dan_layer/core/src/models/hot_stuff_tree_node.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/models/vote_message.rs
  dan_layer/core/src/services/payload_processor.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/integration_tests/src/test_consensus.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-acks_required

#166 feat: state sync on epoch change (see #154)
  applications/tari_validator_node/proto/dan/rpc.proto
  applications/tari_validator_node/src/base_layer_scanner.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/p2p/rpc/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/epoch_manager_service.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/initializer.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/mod.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/sync_peers.rs
  applications/tari_validator_node/src/p2p/services/rpc_client.rs
  dan_layer/common_types/src/epoch.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/services/epoch_manager.rs
  dan_layer/core/src/storage/shard_db.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: CR-too_long, P-acks_required

#187 fix: add committee size constant, to remove duplicate code (see #174)
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/epoch_manager_service.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/initializer.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/mod.rs
  dan_layer/core/src/consensus_constants.rs
Labels: P-merge

#190 feat: add templates to web gui
  applications/tari_validator_node_web_ui/src/Connections.tsx
  applications/tari_validator_node_web_ui/src/Templates.css
  applications/tari_validator_node_web_ui/src/Templates.tsx
  applications/tari_validator_node_web_ui/src/ValidatorNode.tsx
  applications/tari_validator_node_web_ui/src/interfaces.tsx
  applications/tari_validator_node_web_ui/src/json_rpc.tsx
Labels: P-merge

#184 fix: remove finalized transactions from mempool (see issue #111)
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/mempool/handle.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  package-lock.json
Labels: P-merge, P-acks_required, P-reviews_required

#195 fix!: max_outputs missing from proto conversion
  applications/tari_validator_node/proto/dan/transaction.proto
  applications/tari_validator_node/src/p2p/proto/conversions/transaction.rs
  dan_layer/core/src/storage/error.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-acks_required

#194 feat: add timestamp to payloads
  Cargo.lock
  dan_layer/core/Cargo.toml
  dan_layer/core/src/models/tari_dan_payload.rs
  dan_layer/storage_sqlite/migrations/2022-11-09-142700_add_timestamp_to_payloads/down.sql
  dan_layer/storage_sqlite/migrations/2022-11-09-142700_add_timestamp_to_payloads/up.sql
  dan_layer/storage_sqlite/src/models/payload.rs
  dan_layer/storage_sqlite/src/schema.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: CR-insufficient_context, P-merge
