Repository tari-project/tari-ootle, pull requests merged in 2022-10, with the labels that each got.

#79 feat: add better hotstuff logging
  applications/tari_validator_node/log4rs_sample.yml
  applications/tari_validator_node/proto/dan/common.proto
  applications/tari_validator_node/proto/dan/validator_node.proto
  applications/tari_validator_node/src/p2p/proto/conversions.rs
  applications/tari_validator_node/src/p2p/services/hotstuff/hotstuff_service.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/core/src/services/leader_strategy.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
Labels: CR-insufficient_context

#88 fix: don't propose after height 4
  Cargo.lock
  dan_layer/core/src/workers/hotstuff_error.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
Labels: CR-insufficient_context

#95 feat: vn re-registers each epoch
  applications/tari_validator_node/src/auto_registration.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_validator_node_cli/src/account_manager.rs
Labels: P-merge

#101 docs: create readme
  applications/tari_validator_node/README.md
Labels: CR-insufficient_context, P-merge, P-acks_required

#104 feat: better sqlite object pledging
  applications/tari_validator_node/log4rs_sample.yml
  applications/tari_validator_node/proto/dan/consensus.proto
  applications/tari_validator_node/src/p2p/proto/conversions.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/models/payload.rs
  dan_layer/core/src/models/tari_dan_payload.rs
  dan_layer/core/src/models/vote_message.rs
  dan_layer/core/src/storage/error.rs
  dan_layer/core/src/storage/shard_db.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/hotstuff_error.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/engine/src/transaction/builder.rs
  dan_layer/engine/src/transaction/mod.rs
  dan_layer/storage_sqlite/migrations/2022-10-03-178235_create_shard_store/up.sql
  dan_layer/storage_sqlite/src/models/mod.rs
  dan_layer/storage_sqlite/src/models/objects.rs
  dan_layer/storage_sqlite/src/models/substate.rs
  dan_layer/storage_sqlite/src/schema.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-acks_required

#97 fix: remove unnecessary validator config settings
  applications/tari_validator_node/src/config.rs
  integration_tests/config/config.toml
Labels: P-merge

#94 feat(cli): add "templates list" command
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node/src/p2p/services/template_manager/handle.rs
  applications/tari_validator_node/src/p2p/services/template_manager/manager.rs
  applications/tari_validator_node/src/p2p/services/template_manager/service.rs
  applications/tari_validator_node_cli/src/command/template.rs
  applications/tari_validator_node_cli/src/main.rs
  applications/tari_validator_node_cli/src/table.rs
  clients/validator_node_client/src/lib.rs
  clients/validator_node_client/src/types.rs
  dan_layer/core/src/storage/mocks/global_db.rs
  dan_layer/storage/src/global/backend_adapter.rs
  dan_layer/storage/src/global/template_db.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
Labels: CR-too_long, P-merge

#100 feat: use default port
  applications/tari_validator_node/src/auto_registration.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/main.rs
Labels: P-merge

#96 feat: implement waiting for transaction result in jrpc
  .license.ignore
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/default_service_specification.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/hotstuff/hotstuff_service.rs
  applications/tari_validator_node/src/p2p/services/hotstuff/initializer.rs
  applications/tari_validator_node/src/p2p/services/networking/peer_sync.rs
  applications/tari_validator_node/src/p2p/services/networking/service.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_web_ui/.nvmrc
  clients/validator_node_client/src/types.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/core/src/services/asset_proxy.rs
  dan_layer/core/src/services/mempool/mod.rs
  dan_layer/core/src/services/mempool/outbound.rs
  dan_layer/core/src/services/mempool/service.rs
  dan_layer/core/src/services/mod.rs
  dan_layer/core/src/services/service_specification.rs
  dan_layer/core/src/storage/shard_db.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/events.rs
  dan_layer/core/src/workers/hotstuff_error.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/core/src/workers/mod.rs
  dan_layer/core/src/workers/tests/mod.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-merge, P-acks_required

#105 feat: vn register only when registered
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/grpc/services/wallet_client.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/epoch_manager_service.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/handle.rs
  applications/tari_validator_node/src/registration.rs
  clients/validator_node_client/src/lib.rs
  dan_layer/core/src/digital_assets_error.rs
  dan_layer/storage/src/global/metadata_db.rs
Labels: P-acks_required

#113 fix: add template_name field to type `DbTemplate`
  applications/tari_validator_node/src/base_layer_scanner.rs
  applications/tari_validator_node/src/p2p/services/template_manager/handle.rs
  applications/tari_validator_node/src/p2p/services/template_manager/manager.rs
  dan_layer/storage/src/global/template_db.rs
  dan_layer/storage_sqlite/global_db_migrations/2022-10-06-091532_create_templates/up.sql
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  dan_layer/storage_sqlite/src/global/models/template.rs
  dan_layer/storage_sqlite/src/global/schema.rs
Labels: P-merge, P-acks_required

#114 fix: global db migrations
  dan_layer/storage_sqlite/global_db_migrations/2022-10-06-091532_create_templates/up.sql
  dan_layer/storage_sqlite/src/schema.rs
  dan_layer/storage_sqlite/src/sqlite_db_factory.rs
Labels: P-merge, P-acks_required

#117 fix: include transaction meta in transaction proto
  applications/tari_validator_node/proto/dan/common.proto
  applications/tari_validator_node/proto/dan/validator_node.proto
  applications/tari_validator_node/src/p2p/proto/conversions.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/engine/src/transaction/mod.rs
Labels: P-merge

#118 docs: add main README file
  README.md
Labels: CR-insufficient_context, P-merge

#122 feat: add sqlite message logging
  .license.ignore
  Cargo.lock
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/comms/broadcast.rs
  applications/tari_validator_node/src/comms/deserialize.rs
  applications/tari_validator_node/src/comms/initializer.rs
  applications/tari_validator_node/src/comms/mod.rs
  comms/tari_comms_logging/Cargo.toml
  comms/tari_comms_logging/README.md
  comms/tari_comms_logging/diesel.toml
  comms/tari_comms_logging/migrations/.gitkeep
  comms/tari_comms_logging/migrations/2022-10-20-121212_create_table/down.sql
  comms/tari_comms_logging/migrations/2022-10-20-121212_create_table/up.sql
  comms/tari_comms_logging/migrations/2022-10-20-121213_create_inbound/down.sql
  comms/tari_comms_logging/migrations/2022-10-20-121213_create_inbound/up.sql
  comms/tari_comms_logging/src/lib.rs
  comms/tari_comms_logging/src/schema.rs
  comms/tari_comms_logging/src/sqlite_message_log.rs
  dan_layer/core/src/message.rs
  dan_layer/core/src/models/hot_stuff_message.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/models/tari_dan_payload.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/engine/src/transaction/mod.rs
Labels: P-merge

#123 feat(cli): adds submit call-method command
  Cargo.lock
  applications/tari_validator_node_cli/Cargo.toml
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_cli/src/main.rs
Labels: P-acks_required

#91 feat: add p2p state sync for validator nodes (see issue #66)
  Cargo.lock
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/proto/dan/common.proto
  applications/tari_validator_node/proto/dan/network.proto
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/p2p/proto/conversions.rs
  applications/tari_validator_node/src/p2p/rpc/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  dan_layer/core/src/storage/shard_db.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-merge, P-acks_required

#128 fix: fix saving votes to db
  applications/tari_validator_node/proto/dan/consensus.proto
  applications/tari_validator_node/src/p2p/proto/conversions.rs
  dan_layer/core/src/models/hot_stuff_message.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-merge

#133 fix: allow compile without npm
  applications/tari_validator_node/build.rs
  applications/tari_validator_node_web_ui/build/index.html
Labels: P-acks_required

#135 doc: update README.md
  README.md
Labels: P-merge

#136 feat: pretty print json message logs to db
  comms/tari_comms_logging/src/sqlite_message_log.rs
Labels: P-acks_required

#129 fix: base layer scanner should scan fixed number blocks behind (see #107)
  Cargo.lock
  applications/tari_validator_node/src/base_layer_scanner.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus_constants.rs
  applications/tari_validator_node/src/main.rs
Labels: P-merge

#138 fix: fix only propose once each node
  applications/tari_validator_node_web_ui/build/index.html
  dan_layer/core/src/workers/hotstuff_waiter.rs
Labels: CR-insufficient_context, P-merge

#139 fix: use hex encoding for json
  applications/tari_validator_node/src/comms/broadcast.rs
  dan_layer/common_types/src/serde_with/base64.rs
  dan_layer/common_types/src/serde_with/hex.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/models/tree_node_hash.rs
Labels: P-merge

#132 fix: use detach HSflag for tor
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/comms/initializer.rs
  applications/tari_validator_node/src/comms/mod.rs
Labels: P-acks_required

#140 fix(base-layer-scanner): takes confirmations into account when detecting chain progress
  applications/tari_validator_node/src/base_layer_scanner.rs
  dan_layer/storage/src/global/metadata_db.rs
Labels: P-acks_required

#141 feat(jrpc): bind on OS-assigned port if preferred unavailable
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node_cli/src/cli.rs
Labels: P-acks_required

#103 feat: add cucumber-rs integration test infrastructure
  Cargo.lock
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/json_rpc.feature
  applications/tari_validator_node/tests/utils/base_node.rs
  applications/tari_validator_node/tests/utils/miner.rs
  applications/tari_validator_node/tests/utils/mod.rs
  applications/tari_validator_node/tests/utils/validator_node.rs
  applications/tari_validator_node/tests/utils/wallet.rs
  dan_layer/core/Cargo.toml
Labels: CR-too_long, P-acks_required

#142 fix: correctly load component into in-memory state store
  applications/tari_validator_node/src/p2p/services/hotstuff/hotstuff_service.rs
  applications/tari_validator_node/src/payload_processor.rs
  dan_layer/engine/src/lib.rs
  dan_layer/engine/src/runtime/commit_result.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/runtime/tracker.rs
Labels: P-acks_required, P-reviews_required

#143 fix(cucumber): reduce number of runtimes, use client for get_identity
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/comms/initializer.rs
  applications/tari_validator_node/src/http_ui/server.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/utils/base_node.rs
  applications/tari_validator_node/tests/utils/miner.rs
  applications/tari_validator_node/tests/utils/validator_node.rs
  applications/tari_validator_node/tests/utils/wallet.rs
  applications/tari_validator_node_web_ui/build/index.html
  clients/validator_node_client/Cargo.toml
  clients/validator_node_client/src/lib.rs
  clients/validator_node_client/src/types.rs
Labels: P-acks_required, P-reviews_required

#157 feat!: return entire FinalizeResult on submit transaction + other fixes
  Cargo.lock
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/proto/conversions/consensus.rs
  applications/tari_validator_node/src/p2p/services/template_manager/service.rs
  applications/tari_validator_node/src/payload_processor.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_cli/src/from_hex.rs
  clients/validator_node_client/src/types.rs
  comms/tari_comms_logging/src/sqlite_message_log.rs
  dan_layer/common_types/Cargo.toml
  dan_layer/common_types/src/lib.rs
  dan_layer/core/src/services/payload_processor.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/core/src/workers/tests/mod.rs
  dan_layer/engine/src/models/bucket.rs
  dan_layer/engine/src/models/component.rs
  dan_layer/engine/src/models/mod.rs
  dan_layer/engine/src/models/vault.rs
  dan_layer/engine/src/runtime/commit_result.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/traits.rs
  dan_layer/engine/src/transaction/builder.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/src/wasm/mod.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/engine_types/src/execution_result.rs
  dan_layer/engine_types/src/lib.rs
  dan_layer/engine_types/src/logs.rs
  dan_layer/engine_types/src/resource.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/storage_sqlite/migrations/2022-10-03-178235_create_shard_store/up.sql
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  dan_layer/storage_sqlite/src/models/substate.rs
  dan_layer/storage_sqlite/src/schema.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
  dan_layer/storage_sqlite/src/sqlite_transaction.rs
  dan_layer/template_abi/src/types.rs
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/models/amount.rs
  dan_layer/template_lib/src/models/component.rs
  dan_layer/template_lib/src/models/metadata.rs
  dan_layer/template_test_tooling/src/mock_runtime_interface.rs
  dan_layer/template_test_tooling/src/template_test.rs
Labels: CR-too_long, P-acks_required

#152 fix: get_committee
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
Labels: P-acks_required

#150 feat(template_manager): validate binary hash for template downloads
  Cargo.lock
  applications/tari_validator_node/src/p2p/services/template_manager/downloader.rs
  applications/tari_validator_node/src/p2p/services/template_manager/error.rs
  applications/tari_validator_node/src/p2p/services/template_manager/manager.rs
  applications/tari_validator_node/src/p2p/services/template_manager/service.rs
  applications/tari_validator_node_cli/src/command/template.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/lib.rs
  dan_layer/engine_types/src/template.rs
Labels: P-acks_required

#153 feat: check base node grpc connection on startup
  applications/tari_validator_node/src/grpc/services/base_node_client.rs
  applications/tari_validator_node/src/lib.rs
  dan_layer/core/src/services/base_node_client.rs
Labels: P-acks_required

#146 feat: send the whole payload with first message
  applications/tari_validator_node/proto/dan/consensus.proto
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/proto/conversions/consensus.rs
  dan_layer/core/src/models/hot_stuff_message.rs
  dan_layer/core/src/models/hot_stuff_tree_node.rs
  dan_layer/core/src/models/tari_dan_payload.rs
  dan_layer/core/src/storage/shard_db.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/engine/src/transaction/mod.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: CR-too_long, CR-insufficient_context, P-acks_required, P-reviews_required

#158 feat!: add arguments to cli
  Cargo.lock
  applications/tari_validator_node/log4rs_sample.yml
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  dan_layer/core/Cargo.toml
  dan_layer/core/src/models/domain_events/consensus_worker_domain_event.rs
  dan_layer/core/src/models/node.rs
  dan_layer/core/src/models/vote_message.rs
  dan_layer/core/src/storage/error.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/wasm/environment.rs
  dan_layer/engine/tests/templates/erc20/Cargo.lock
  dan_layer/engine/tests/templates/hello_world/Cargo.lock
  dan_layer/engine/tests/templates/private_function/Cargo.lock
  dan_layer/engine/tests/templates/state/Cargo.lock
  dan_layer/engine/tests/templates/tuples/Cargo.lock
  dan_layer/storage_lmdb/src/engine_state_store.rs
  dan_layer/storage_sqlite/src/sqlite_db_factory.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
  dan_layer/storage_sqlite/src/sqlite_transaction.rs
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_lib/src/models/amount.rs
  dan_layer/template_lib/src/models/metadata.rs
Labels: P-acks_required, P-reviews_required
