Repository tari-project/tari-ootle, pull requests merged in 2023-04, with the labels that each got.

#458 fix(tari_indexer): invalid CBOR decoding of confidential vaults
  applications/tari_indexer/src/substate_decoder.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#450 feat!: make resource address deterministic
  applications/tari_dan_app_grpc/src/conversions/transaction.rs
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/fungible.feature
  applications/tari_validator_node/tests/features/indexer.feature
  applications/tari_validator_node/tests/features/nft.feature
  applications/tari_validator_node/tests/templates/basic_nft/src/lib.rs
  applications/tari_validator_node/tests/templates/faucet/src/lib.rs
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  applications/tari_validator_node_cli/src/command/account.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/core/src/models/payload.rs
  dan_layer/core/src/models/tari_dan_payload.rs
  dan_layer/engine/src/bootstrap.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine/tests/templates/faucet/src/lib.rs
  dan_layer/engine/tests/templates/nft/airdrop/src/lib.rs
  dan_layer/engine/tests/templates/nft/basic_nft/src/lib.rs
  dan_layer/engine/tests/templates/nft/emoji_id/src/lib.rs
  dan_layer/engine/tests/templates/nft/marketplace/src/lib.rs
  dan_layer/engine/tests/templates/nft/nft_list/src/lib.rs
  dan_layer/engine/tests/templates/nft/tickets/src/lib.rs
  dan_layer/engine/tests/templates/random/Cargo.lock
  dan_layer/engine_types/src/hashing.rs
  dan_layer/engine_types/src/resource.rs
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/mod.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/transaction/src/builder.rs
  dan_layer/transaction/src/id_provider.rs
  dan_layer/transaction/src/lib.rs
  dan_layer/transaction/src/object_claim.rs
  dan_layer/transaction/src/transaction.rs
Labels: P-acks_required

#456 feat: add signaling server
  Cargo.lock
  Cargo.toml
  applications/tari_signaling_server/Cargo.toml
  applications/tari_signaling_server/log4rs_sample.yml
  applications/tari_signaling_server/src/cli.rs
  applications/tari_signaling_server/src/data.rs
  applications/tari_signaling_server/src/jrpc_server.rs
  applications/tari_signaling_server/src/main.rs
Labels: CR-too_long, P-acks_required

#453 feat: adds columns to substate table for claiming fees by leader VNs
  applications/tari_dan_app_grpc/proto/consensus.proto
  applications/tari_dan_app_grpc/proto/rpc.proto
  applications/tari_dan_app_grpc/src/conversions/consensus.rs
  applications/tari_dan_app_grpc/src/conversions/rpc.rs
  applications/tari_dan_wallet_daemon/src/services/events.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node/src/p2p/services/hotstuff/hotstuff_service.rs
  applications/tari_validator_node/src/p2p/services/hotstuff/initializer.rs
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  clients/validator_node_client/src/lib.rs
  clients/validator_node_client/src/types.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/common_types/src/quorum_certificate.rs
  dan_layer/core/src/models/hot_stuff_message.rs
  dan_layer/core/src/models/hot_stuff_tree_node.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/models/substate_shard_data.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/events.rs
  dan_layer/core/src/workers/hotstuff_error.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/integration_tests/src/test_consensus.rs
  dan_layer/storage_sqlite/migrations/2022-10-03-178235_create_shard_store/up.sql
  dan_layer/storage_sqlite/migrations/2023-04-03-205834_alter_substates_table_for_fees/down.sql
  dan_layer/storage_sqlite/migrations/2023-04-03-205834_alter_substates_table_for_fees/up.sql
  dan_layer/storage_sqlite/src/models/substate.rs
  dan_layer/storage_sqlite/src/schema.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/wallet/sdk/src/models/wallet_transaction.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#449 feat: add webrtc and webextension for tari
  Cargo.lock
  Cargo.toml
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/cli.rs
  applications/tari_dan_wallet_daemon/src/handlers/context.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/webrtc.rs
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_validator_node/tests/utils/wallet_daemon.rs
  applications/tari_web_extension/.gitignore
  applications/tari_web_extension/Cargo.lock
  applications/tari_web_extension/Cargo.toml
  applications/tari_web_extension/README.md
  applications/tari_web_extension/package-lock.json
  applications/tari_web_extension/package.json
  applications/tari_web_extension/popup/.gitignore
  applications/tari_web_extension/popup/index.html
  applications/tari_web_extension/popup/package-lock.json
  applications/tari_web_extension/popup/package.json
  applications/tari_web_extension/popup/src/App.css
  applications/tari_web_extension/popup/src/App.tsx
  applications/tari_web_extension/popup/src/Components/AlertDialog.tsx
  applications/tari_web_extension/popup/src/Components/CopyToClipboard.tsx
  applications/tari_web_extension/popup/src/Components/Copyright.tsx
  applications/tari_web_extension/popup/src/Components/HeadingMenu.tsx
  applications/tari_web_extension/popup/src/Components/JsonTooltip.tsx
  applications/tari_web_extension/popup/src/Components/Logo.tsx
  applications/tari_web_extension/popup/src/Components/MenuItems.tsx
  applications/tari_web_extension/popup/src/Components/PageHeading.tsx
  applications/tari_web_extension/popup/src/Components/SearchFilter.tsx
  applications/tari_web_extension/popup/src/Components/SecondaryHeading.tsx
  applications/tari_web_extension/popup/src/Components/StyledComponents.ts
  applications/tari_web_extension/popup/src/Components/Title.tsx
  applications/tari_web_extension/popup/src/index.css
  applications/tari_web_extension/popup/src/main.tsx
  applications/tari_web_extension/popup/src/routes/AllowedPages/AllowedPages.tsx
  applications/tari_web_extension/popup/src/routes/ErrorPage.tsx
  applications/tari_web_extension/popup/src/theme.ts
  applications/tari_web_extension/popup/src/utils/helpers.tsx
  applications/tari_web_extension/popup/src/utils/interfaces.tsx
  applications/tari_web_extension/popup/src/vite-env.d.ts
  applications/tari_web_extension/popup/tsconfig.json
  applications/tari_web_extension/popup/tsconfig.node.json
  applications/tari_web_extension/popup/vite.config.ts
  applications/tari_web_extension/src/lib.rs
  applications/tari_web_extension/static/background.js
  applications/tari_web_extension/static/content.js
  applications/tari_web_extension/static/inject.js
  applications/tari_web_extension/static/manifest.json
  applications/tari_web_extension/static/options.html
  applications/tari_web_extension/webpack.config.js
  clients/wallet_daemon_client/src/types.rs
  config/logs.yml
Labels: CR-too_long, P-acks_required

#461 feat: add wallet daemon config
  Cargo.lock
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/cli.rs
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/main.rs
  applications/tari_dan_wallet_daemon/src/webrtc.rs
  applications/tari_validator_node/tests/utils/wallet_daemon.rs
Labels: P-acks_required

#452 feat: adds read me instructions to claim fees via dan wallet cli
  README.md
Labels: P-acks_required

#460 feat: add web ui fees
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node_web_ui/src/App.tsx
  applications/tari_validator_node_web_ui/src/Components/MenuItems.tsx
  applications/tari_validator_node_web_ui/src/index.tsx
  applications/tari_validator_node_web_ui/src/routes/Fees/Fees.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Fees.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/ValidatorNode.tsx
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
  clients/validator_node_client/src/lib.rs
  clients/validator_node_client/src/types.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#466 chore: update tari version to new tag
  Cargo.lock
  applications/tari_dan_app_grpc/Cargo.toml
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_wallet_cli/Cargo.toml
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/tests/templates/fees/Cargo.toml
  applications/tari_validator_node/tests/utils/wallet.rs
  applications/tari_validator_node_cli/Cargo.toml
  clients/tari_indexer_client/Cargo.toml
  clients/validator_node_client/Cargo.toml
  clients/wallet_daemon_client/Cargo.toml
  dan_layer/common_types/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/engine/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/integration_tests/Cargo.toml
  dan_layer/storage/Cargo.toml
  dan_layer/storage_lmdb/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  dan_layer/transaction/Cargo.toml
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/storage_sqlite/Cargo.toml
Labels: P-acks_required

#468 refactor!: remove CBOR binary tag for Amount
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_cli/src/command/proof.rs
  applications/tari_validator_node/tests/features/fungible.feature
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/faucet/src/lib.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine/tests/airdrop.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/fees.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine/tests/templates/faucet/src/lib.rs
  dan_layer/engine/tests/templates/nft/airdrop/src/lib.rs
  dan_layer/engine/tests/templates/nft/marketplace/src/lib.rs
  dan_layer/engine/tests/templates/nft/tickets/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_lib/src/args/value.rs
  dan_layer/template_lib/src/models/amount.rs
  dan_layer/template_lib/src/models/binary_tag.rs
  dan_layer/template_test_tooling/templates/faucet/src/lib.rs
  dan_layer/transaction_manifest/src/generator.rs
  dan_layer/transaction_manifest/tests/examples/picture_seller.rs
  dan_layer/transaction_manifest/tests/parser.rs
  dan_layer/wallet/storage_sqlite/src/models/account.rs
  dan_layer/wallet/storage_sqlite/src/models/vault.rs
Labels: P-acks_required

#472 fix: invalid URL format on wallet daemon cucumber utils
  applications/tari_validator_node/tests/log4rs/cucumber.yml
  applications/tari_validator_node/tests/utils/wallet_daemon.rs
Labels: P-acks_required

#471 feat: claim free testnet coins
  applications/tari_dan_app_grpc/proto/transaction.proto
  applications/tari_dan_app_grpc/src/conversions/transaction.rs
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/transaction/error.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/instruction.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#469 feat(wallet_ui): add account details page
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_web_ui/src/App.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_validator_node/src/cli.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/serialize.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/wallet/sdk/src/models/account.rs
  dan_layer/wallet/storage_sqlite/README.md
  dan_layer/wallet/storage_sqlite/migrations/2023-02-08-122514_initial/up.sql
  dan_layer/wallet/storage_sqlite/src/models/account.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
Labels: CR-insufficient_context, P-acks_required

#467 feat: jwt token to the wallet daemon jrpc
  Cargo.lock
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/handlers/context.rs
  applications/tari_dan_wallet_daemon/src/handlers/rpc.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/jwt.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/webrtc.rs
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_signaling_server/src/jrpc_server.rs
  applications/tari_web_extension/static/inject.js
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
Labels: P-acks_required

#464 fix: don't send announce on address update
  applications/tari_validator_node/src/p2p/services/networking/service.rs
Labels: P-acks_required

#484 feat(vn): show inbound connectivity status in logs only when changed
  applications/tari_validator_node/src/dan_node.rs
Labels: P-acks_required

#483 refactor(indexer): indexer theme files
  applications/tari_indexer_web_ui/src/App.tsx
  applications/tari_indexer_web_ui/src/Components/Logo.tsx
  applications/tari_indexer_web_ui/src/Components/PageHeading.tsx
  applications/tari_indexer_web_ui/src/Components/SecondaryHeading.tsx
  applications/tari_indexer_web_ui/src/Components/StyledComponents.ts
  applications/tari_indexer_web_ui/src/assets/Logo.tsx
  applications/tari_indexer_web_ui/src/assets/images/TariLogoBlack.svg
  applications/tari_indexer_web_ui/src/assets/images/TariLogoWhite.svg
  applications/tari_indexer_web_ui/src/index.css
  applications/tari_indexer_web_ui/src/index.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/Connections.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/MonitoredNftCollections.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/MonitoredSubstates.tsx
  applications/tari_indexer_web_ui/src/theme/LayoutMain.tsx
  applications/tari_indexer_web_ui/src/theme/fonts/AvenirLTStd-Book.otf
  applications/tari_indexer_web_ui/src/theme/fonts/AvenirLTStd-Heavy.otf
  applications/tari_indexer_web_ui/src/theme/fonts/AvenirLTStd-Medium.otf
  applications/tari_indexer_web_ui/src/theme/theme.css
  applications/tari_indexer_web_ui/src/theme/theme.ts
Labels: P-acks_required

#486 fix: return os error codes on error
  applications/tari_dan_wallet_cli/src/main.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/main.rs
  applications/tari_signaling_server/src/main.rs
  applications/tari_validator_node_cli/src/main.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#487 fix: account ui fixes
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_validator_node_cli/src/cli.rs
  clients/wallet_daemon_client/src/types.rs
Labels: P-acks_required

#480 feat: add airdrop faucet tokens description in readme
  README.md
Labels: P-acks_required

#491 fix: correct cargo manifest key for git revisions (ciborium)
  Cargo.lock
  applications/tari_indexer/Cargo.toml
  dan_layer/engine/tests/templates/caller_context/Cargo.lock
  dan_layer/engine/tests/templates/confidential/faucet/Cargo.lock
  dan_layer/engine/tests/templates/confidential/utilities/Cargo.lock
  dan_layer/engine/tests/templates/consensus/Cargo.lock
  dan_layer/engine/tests/templates/errors/Cargo.lock
  dan_layer/engine/tests/templates/faucet/Cargo.lock
  dan_layer/engine/tests/templates/hello_world/Cargo.lock
  dan_layer/engine/tests/templates/nft/airdrop/Cargo.lock
  dan_layer/engine/tests/templates/nft/basic_nft/Cargo.lock
  dan_layer/engine/tests/templates/nft/emoji_id/Cargo.lock
  dan_layer/engine/tests/templates/nft/nft_list/Cargo.lock
  dan_layer/engine/tests/templates/nft/tickets/Cargo.lock
  dan_layer/engine/tests/templates/private_function/Cargo.lock
  dan_layer/engine/tests/templates/random/Cargo.lock
  dan_layer/engine/tests/templates/state/Cargo.lock
  dan_layer/engine/tests/templates/tuples/Cargo.lock
  dan_layer/tari_bor/Cargo.toml
  dan_layer/template_builtin/templates/account/Cargo.lock
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required
