Repository tari-project/tari-ootle, pull requests merged in 2023-10, with the labels that each got.

#716 feat(ci): add cucumber logs as artifact
  .github/workflows/ci.yml
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/block_sync.feature
  integration_tests/tests/features/claim_burn.feature
  integration_tests/tests/features/claim_fees.feature
  integration_tests/tests/features/fungible.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
  integration_tests/tests/log4rs/cucumber.yml
Labels: P-acks_required, P-reviews_required

#726 fix(cucumber): cancel account create request after timeout
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#678 feat: count votes as newview
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/spec.rs
  applications/tari_validator_node/src/p2p/rpc/sync_task.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_next_sync_view.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/on_sync_request.rs
  dan_layer/consensus/src/hotstuff/state_machine/check_sync.rs
  dan_layer/consensus/src/hotstuff/state_machine/event.rs
  dan_layer/consensus/src/hotstuff/state_machine/idle.rs
  dan_layer/consensus/src/hotstuff/state_machine/running.rs
  dan_layer/consensus/src/hotstuff/state_machine/state.rs
  dan_layer/consensus/src/hotstuff/state_machine/worker.rs
  dan_layer/consensus/src/hotstuff/vote_receiver.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/new_view.rs
  dan_layer/consensus/src/messages/vote.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/spec.rs
  dan_layer/consensus_tests/src/support/sync.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/epoch_manager/Cargo.toml
  dan_layer/epoch_manager/src/base_layer/handle.rs
  dan_layer/epoch_manager/src/traits.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/bookkeeping.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/last_sent_vote.rs
  dan_layer/storage/src/consensus_models/mod.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/proto/consensus.proto
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/features/block_sync.feature
Labels: P-acks_required

#719 feat: add cli app scaffolder
  Cargo.lock
  Cargo.toml
  applications/tari_dan_wallet_cli/src/command/auth.rs
  applications/tari_dan_wallet_daemon/src/handlers/rpc.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_indexer/src/lib.rs
  applications/tari_scaffolder/Cargo.toml
  applications/tari_scaffolder/src/cli.rs
  applications/tari_scaffolder/src/command/mod.rs
  applications/tari_scaffolder/src/main.rs
  applications/tari_scaffolder/src/template/.gitignore.liquid
  applications/tari_scaffolder/src/template/Cargo.toml.liquid
  applications/tari_scaffolder/src/template/src/cli.rs.liquid
  applications/tari_scaffolder/src/template/src/daemon_client.rs.liquid
  applications/tari_scaffolder/src/template/src/main.rs.liquid
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/engine_types/src/argument_parser.rs
  dan_layer/engine_types/src/lib.rs
  dan_layer/indexer_lib/src/substate_decoder.rs
  dan_layer/indexer_lib/src/transaction_autofiller.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
  integration_tests/src/wallet_daemon.rs
  scripts/file_license_check.sh
  scripts/update_crate_metadata.sh
Labels: P-acks_required

#732 feat: add transfer to dan wallet ui
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/AssetVault.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AddAccount.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimBurn.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  clients/wallet_daemon_client/src/types.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#736 fix(tx-generator): fix compile err by forcing critical-section feature for once_cell
  Cargo.lock
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  utilities/transaction_generator/Cargo.toml
Labels: P-acks_required

#725 fix: dan wallet ui for failed transaction
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
Labels: P-acks_required

#714 fix(transactions)!: remove transaction output
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/transaction/src/builder.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/validator_node_rpc/proto/transaction.proto
  dan_layer/validator_node_rpc/src/conversions/transaction.rs
  dan_layer/wallet/storage_sqlite/src/models/mod.rs
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#738 feat: add jrpc address for webui to connect to
  applications/tari_indexer/src/config.rs
  applications/tari_indexer/src/http_ui/server.rs
  applications/tari_indexer/src/lib.rs
Labels: P-acks_required

#728 fix(cucumber): unignore claim burn and 4-vn committee test
  dan_layer/storage/src/consensus_models/quorum_certificate.rs
  dan_layer/storage/src/consensus_models/substate.rs
  integration_tests/tests/features/claim_burn.feature
  integration_tests/tests/features/committee.feature
  integration_tests/tests/steps/validator_node.rs
Labels: P-acks_required

#737 feat(indexer): new jrpc method to get all transactions related to a substate
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/json_rpc/server.rs
  applications/tari_indexer/src/substate_manager.rs
  clients/tari_indexer_client/src/types.rs
Labels: P-acks_required, P-reviews_required

#730 fix(consensus): allow multiple QCs to justify a block
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/storage/src/consensus_models/quorum.rs
Labels: P-controversial, P-acks_required, P-reviews_required

#724 fix: foreign vaults/accounts
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  dan_layer/wallet/sdk/src/apis/accounts.rs
Labels: P-acks_required

#735 fix(cucumber): fix indexer tests
  integration_tests/src/indexer.rs
  integration_tests/src/miner.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/claim_fees.feature
  integration_tests/tests/features/committee.feature
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
  integration_tests/tests/steps/indexer.rs
  integration_tests/tests/steps/miner.rs
Labels: P-acks_required

#718 fix: confidential transfer
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  dan_layer/wallet/sdk/src/apis/confidential_outputs.rs
  dan_layer/wallet/sdk/src/models/confidential_output.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-02-08-122514_initial/up.sql
  dan_layer/wallet/storage_sqlite/src/models/output.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#740 fix(mempool): validate that executed transaction has at least one input/output shard
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/p2p/services/mempool/error.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/after/has_involved_shards.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/after/input_refs.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/after/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/after/outputs_dont_exist_locally.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/claim_fee_instructions.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/fee.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/has_inputs.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/template_exists.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/mod.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/transaction/src/transaction.rs
Labels: P-acks_required

#743 refactor: token symbol should not have to be unique per template
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  dan_layer/transaction/src/id_provider.rs
  integration_tests/src/templates/basic_nft/src/lib.rs
  integration_tests/tests/features/nft.feature
Labels: P-acks_required

#747 chore: remove unused transaction fields
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_scaffolder/src/template/src/daemon_client.rs.liquid
  applications/tari_validator_node_cli/src/command/account.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  integration_tests/src/validator_node_cli.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/committee.feature
  integration_tests/tests/features/counter.feature
  integration_tests/tests/features/fungible.feature
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/features/nft.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
Labels: P-acks_required

#741 feat: change base node grpc address to string
  applications/tari_dan_wallet_daemon/src/cli.rs
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/http_ui/server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_indexer/src/cli.rs
  applications/tari_indexer/src/config.rs
  applications/tari_indexer/src/http_ui/server.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer_web_ui/src/utils/json_rpc.tsx
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/http_ui/server.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
  clients/base_node_client/src/grpc.rs
  integration_tests/src/base_node.rs
  integration_tests/src/indexer.rs
  integration_tests/src/validator_node.rs
Labels: P-acks_required

#752 feat: create registration file on startup
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/config.rs
Labels: P-acks_required

#746 fix(template)!: make token_symbol part of the metadata again in resources
  applications/tari_dan_wallet_cli/src/command/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_validator_node/src/bootstrap.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine/src/bootstrap.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine/tests/templates/faucet/src/lib.rs
  dan_layer/engine/tests/templates/nft/airdrop/src/lib.rs
  dan_layer/engine/tests/templates/nft/basic_nft/src/lib.rs
  dan_layer/engine/tests/templates/nft/emoji_id/src/lib.rs
  dan_layer/engine/tests/templates/nft/marketplace/src/lib.rs
  dan_layer/engine/tests/templates/nft/nft_list/src/lib.rs
  dan_layer/engine/tests/templates/nft/tickets/src/lib.rs
  dan_layer/engine/tests/templates/tariswap/src/lib.rs
  dan_layer/engine_types/src/resource.rs
  dan_layer/template_builtin/templates/account_nfts/src/lib.rs
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/mod.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/wallet/sdk/src/models/non_fungible_tokens.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-10-23-083718_remove_token_symbol/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-10-23-083718_remove_token_symbol/up.sql
  dan_layer/wallet/storage_sqlite/src/models/non_fungible_tokens.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  integration_tests/src/templates/basic_nft/src/lib.rs
  integration_tests/src/templates/faucet/src/lib.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#749 chore: rename fee to max_fee
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_cli/src/command/validator.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/validator.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/transaction/src/builder.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#754 fix: add http prefix if it is missing
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer_web_ui/src/utils/json_rpc.tsx
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#748 feat: fetch transactions by component
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service.rs
  applications/tari_dan_wallet_web_ui/src/api/hooks/useTransactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: P-acks_required

#753 fix(template-macro)!: template ABI uses global export byte literal
  Cargo.lock
  applications/tari_dan_app_utilities/src/template_manager/implementation/service.rs
  applications/tari_scaffolder/src/main.rs
  dan_layer/engine/src/flow/flow_factory.rs
  dan_layer/engine/src/flow/workers/call_method_worker.rs
  dan_layer/engine/src/packager/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/wasm/environment.rs
  dan_layer/engine/src/wasm/error.rs
  dan_layer/engine/src/wasm/module.rs
  dan_layer/engine/tests/templates/buggy/Cargo.toml
  dan_layer/engine/tests/templates/buggy/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/template_abi/src/lib.rs
  dan_layer/template_abi/src/types.rs
  dan_layer/template_lib/src/template_dependencies.rs
  dan_layer/template_macros/Cargo.toml
  dan_layer/template_macros/src/template/abi.rs
  dan_layer/template_macros/src/template/ast.rs
  dan_layer/template_macros/src/template/definition.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required
