Repository tari-project/tari-ootle, pull requests merged in 2023-12, with the labels that each got.

#817 chore: comment out flaky test
  integration_tests/tests/features/block_sync.feature
Labels: P-acks_required

#819 feat: set refresh balance interval to 5 sec
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
Labels: P-acks_required

#823 fix: shorten string on small strings
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
Labels: P-acks_required

#805 fix: indexer settings in dan wallet ui
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/IndexerSettings.tsx
  applications/tari_dan_wallet_web_ui/src/store/accountStore.ts
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required, P-reviews_required

#815 feat: add transaction json download to ui
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Substates.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
Labels: P-acks_required

#824 docs(template_lib): add rustdoc documentation
  dan_layer/tari_bor/src/lib.rs
  dan_layer/template_abi/src/abi/mod.rs
  dan_layer/template_lib/src/args/arg.rs
  dan_layer/template_lib/src/args/mod.rs
  dan_layer/template_lib/src/args/result.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/args/value.rs
  dan_layer/template_lib/src/auth/access_rules.rs
  dan_layer/template_lib/src/auth/mod.rs
  dan_layer/template_lib/src/auth/owner_rule.rs
  dan_layer/template_lib/src/caller_context.rs
  dan_layer/template_lib/src/component/instance.rs
  dan_layer/template_lib/src/component/manager.rs
  dan_layer/template_lib/src/component/mod.rs
  dan_layer/template_lib/src/constants.rs
  dan_layer/template_lib/src/context.rs
  dan_layer/template_lib/src/crypto/balance_proof.rs
  dan_layer/template_lib/src/crypto/commitment.rs
  dan_layer/template_lib/src/crypto/error.rs
  dan_layer/template_lib/src/crypto/mod.rs
  dan_layer/template_lib/src/crypto/ristretto.rs
  dan_layer/template_lib/src/engine.rs
  dan_layer/template_lib/src/events.rs
  dan_layer/template_lib/src/hash.rs
  dan_layer/template_lib/src/macros.rs
  dan_layer/template_lib/src/models/amount.rs
  dan_layer/template_lib/src/models/binary_tag.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/component.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_lib/src/models/layer_one_commitment.rs
  dan_layer/template_lib/src/models/metadata.rs
  dan_layer/template_lib/src/models/mod.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/template_lib/src/models/non_fungible_index.rs
  dan_layer/template_lib/src/models/proof.rs
  dan_layer/template_lib/src/models/resource.rs
  dan_layer/template_lib/src/models/system.rs
  dan_layer/template_lib/src/models/vault.rs
  dan_layer/template_lib/src/newtype_serde_macros.rs
  dan_layer/template_lib/src/panic_hook.rs
  dan_layer/template_lib/src/rand.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/mod.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/template_lib/src/resource/mod.rs
  dan_layer/template_lib/src/template/manager.rs
  dan_layer/template_lib/src/template/mod.rs
Labels: P-acks_required

#810 feat: show substate version in dan wallet ui
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Substates.tsx
Labels: P-acks_required

#799 fix: propagation
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_validator_node/src/p2p/rpc/sync_task.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
Labels: P-acks_required

#798 feat(integration_tests): new test for downed substates
  Cargo.lock
  integration_tests/Cargo.toml
  integration_tests/src/validator_node_cli.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/substates.feature
Labels: P-acks_required

#796 fix: shard range computation
  dan_layer/common_types/src/shard_bucket.rs
Labels: P-acks_required

#804 feat: sort TXs in UI, add timestamp
  Cargo.lock
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  clients/wallet_daemon_client/Cargo.toml
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/wallet_transaction.rs
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: P-acks_required

#760 feat: request foreign blocks
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_request_missing_foreign_blocks.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/consensus/src/messages/mod.rs
  dan_layer/consensus/src/messages/request_missing_foreign_blocks.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/proto/consensus.proto
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
Labels: P-acks_required

#833 fix: force txs refetch on account change in UI
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
Labels: P-acks_required

#836 fix(swarm): exit with error if unsupported seed multiaddr
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/common_types/src/peer_address.rs
  networking/core/src/handle.rs
  networking/core/src/lib.rs
  networking/core/src/spawn.rs
  networking/core/src/worker.rs
  networking/swarm/src/behaviour.rs
Labels: P-acks_required

#837 fix: cli argument duplicate
  applications/tari_validator_node/src/cli.rs
  igor/config/config.toml
  igor/config/indexer/log4rs.yml
  igor/data/indexer/global_storage.sqlite
  igor/indexer_id.json
Labels: P-acks_required

#835 feat: add version to template WASMs
  dan_layer/engine/src/flow/flow_factory.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/template_abi/src/types.rs
  dan_layer/template_macros/src/template/abi.rs
Labels: P-acks_required

#843 feat: show dummy blocks in ui
  applications/tari_validator_node_web_ui/src/Components/StatusChip.tsx
  applications/tari_validator_node_web_ui/src/routes/Committees/Committee.tsx
  applications/tari_validator_node_web_ui/src/routes/Committees/Committees.tsx
  applications/tari_validator_node_web_ui/src/routes/Committees/CommitteesLayout.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Blocks.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/ValidatorNode.tsx
Labels: P-acks_required

#838 chore: unify cargo workspace
  Cargo.lock
  Cargo.toml
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_wallet_cli/Cargo.toml
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_scaffolder/Cargo.toml
  applications/tari_signaling_server/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node_cli/Cargo.toml
  clients/base_node_client/Cargo.toml
  clients/tari_indexer_client/Cargo.toml
  clients/validator_node_client/Cargo.toml
  clients/wallet_daemon_client/Cargo.toml
  dan_layer/common_types/Cargo.toml
  dan_layer/comms_rpc_state_sync/Cargo.toml
  dan_layer/consensus/Cargo.toml
  dan_layer/consensus_tests/Cargo.toml
  dan_layer/engine/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/epoch_manager/Cargo.toml
  dan_layer/indexer_lib/Cargo.toml
  dan_layer/p2p/Cargo.toml
  dan_layer/state_store_sqlite/Cargo.toml
  dan_layer/storage/Cargo.toml
  dan_layer/storage_lmdb/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  dan_layer/tari_bor/Cargo.toml
  dan_layer/template_abi/Cargo.toml
  dan_layer/template_builtin/Cargo.toml
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_macros/Cargo.toml
  dan_layer/template_test_tooling/Cargo.toml
  dan_layer/transaction/Cargo.toml
  dan_layer/transaction_manifest/Cargo.toml
  dan_layer/validator_node_rpc/Cargo.toml
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/storage_sqlite/Cargo.toml
  integration_tests/Cargo.toml
  integration_tests/src/templates/fees/Cargo.toml
  networking/core/Cargo.toml
  networking/libp2p-messaging/Cargo.toml
  networking/libp2p-substream/Cargo.toml
  networking/proto_builder/Cargo.toml
  networking/rpc_framework/Cargo.toml
  networking/rpc_macros/Cargo.toml
  networking/sqlite_message_logger/Cargo.toml
  networking/swarm/Cargo.toml
  scripts/update_crate_metadata.sh
  utilities/transaction_generator/Cargo.toml
  utilities/transaction_submitter/Cargo.toml
Labels: CR-too_long, P-acks_required

#841 fix: claim burn in the ui
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimBurn.tsx
Labels: P-acks_required

#826 feat: do fee estimation in UI transfer
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/confidential_outputs.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#845 fix(p2p/messaging): single stream per connection
  dan_layer/storage/Cargo.toml
  networking/core/src/worker.rs
  networking/libp2p-messaging/src/behaviour.rs
  networking/libp2p-messaging/src/event.rs
  networking/libp2p-messaging/src/handler.rs
  networking/libp2p-messaging/src/stream.rs
Labels: P-acks_required, P-reviews_required

#850 feat(template_test_tooling): include account_nft builtin template
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/template_test_tooling/src/package_builder.rs
  dan_layer/template_test_tooling/src/template_test.rs
Labels: P-acks_required

#847 feat: create get_non_fungible_ids action for buckets
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/models/bucket.rs
Labels: P-acks_required

#778 chore: publish wasm dependencies to crates
  Cargo.toml
  dan_layer/template_builtin/build.rs
  dan_layer/template_builtin/templates/account/Cargo.toml
  dan_layer/template_builtin/templates/account_nfts/Cargo.toml
  dan_layer/template_macros/Cargo.lock
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  scripts/publish_crates.sh
Labels: CR-insufficient_context, P-acks_required, P-reviews_required
