Repository tari-project/tari-ootle, pull requests merged in 2023-07, with the labels that each got.

#584 fix(ci): use nightly only for cargo fmt
  .github/workflows/ci.yml
  Cargo.lock
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/templates/caller_context/Cargo.toml
  dan_layer/engine/tests/templates/caller_context/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/template_builtin/templates/account/Cargo.lock
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_lib/src/caller_context.rs
  dan_layer/template_lib/src/context.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_lib/src/prelude.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required

#586 fix: log path
  applications/tari_dan_wallet_daemon/log4rs_sample.yml
  applications/tari_indexer/log4rs_sample.yml
  applications/tari_signaling_server/log4rs_sample.yml
  applications/tari_validator_node/log4rs_sample.yml
Labels: P-acks_required

#585 feat: separate jrpc and listening address
  applications/tari_dan_wallet_daemon/src/cli.rs
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/http_ui/server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/http_ui/server.rs
  applications/tari_validator_node/src/lib.rs
  clients/wallet_daemon_client/src/lib.rs
  integration_tests/src/wallet_daemon.rs
Labels: P-acks_required, P-reviews_required

#587 ci(feature): support cross-compile - openssl vendored
  Cargo.lock
  applications/tari_web_extension/Cargo.toml
Labels: P-acks_required

#590 ci: fix testing jobs
  .config/nextest.toml
  .github/workflows/ci.yml
  dan_layer/consensus_tests/src/worker.rs
Labels: P-acks_required

#591 fix(walletd): use identical encoding for DH output encrytion key hasher
  dan_layer/engine_types/src/base_layer_hashing.rs
  dan_layer/wallet/sdk/src/confidential/kdfs.rs
Labels: P-acks_required

#577 feat(consensus): implement simpler batching co-ordination
  dan_layer/common_types/src/committee.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/event.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/epoch_manager.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus/src/traits/state_manager.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/lib.rs
  dan_layer/consensus_tests/src/support/address.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/helpers.rs
  dan_layer/consensus_tests/src/support/leader_strategy.rs
  dan_layer/consensus_tests/src/support/mod.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/spec.rs
  dan_layer/consensus_tests/src/support/state_manager.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/consensus_tests/src/worker.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/error.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/sql_models/mod.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction_decision.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction_pool.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/mod.rs
  dan_layer/storage/src/consensus_models/pledge.rs
  dan_layer/storage/src/consensus_models/quorum_certificate.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/consensus_models/transaction_decision.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/consensus_models/transaction_pools.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: CR-too_long, P-acks_required

#589 feat: account nft list for dan wallet ui
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#567 fix(wasm)!: avoid using hashmaps in templates
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/templates/events/src/lib.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_builtin/templates/account_nfts/src/lib.rs
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/events.rs
  dan_layer/template_lib/src/models/metadata.rs
Labels: P-acks_required

#580 chore!: update hash domain consistency
  dan_layer/common_types/src/hashing.rs
  dan_layer/core/src/lib.rs
  dan_layer/engine_types/src/base_layer_hashing.rs
  dan_layer/engine_types/src/hashing.rs
Labels: P-acks_required

#597 chore: update to tari 0.51.0-pre.4
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_wallet_cli/Cargo.toml
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/indexer_jrpc_impl.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_indexer/Cargo.toml
  applications/tari_signaling_server/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/p2p/services/mempool/validator.rs
  applications/tari_validator_node_cli/Cargo.toml
  clients/base_node_client/Cargo.toml
  clients/tari_indexer_client/Cargo.toml
  clients/validator_node_client/Cargo.toml
  clients/validator_node_client/src/lib.rs
  clients/wallet_daemon_client/Cargo.toml
  dan_layer/common_types/Cargo.toml
  dan_layer/consensus/Cargo.toml
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/engine/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/epoch_manager/Cargo.toml
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/integration_tests/Cargo.toml
  dan_layer/state_store_sqlite/Cargo.toml
  dan_layer/storage/Cargo.toml
  dan_layer/storage_lmdb/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  dan_layer/transaction/Cargo.toml
  dan_layer/validator_node_rpc/Cargo.toml
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/storage_sqlite/Cargo.toml
  integration_tests/Cargo.toml
  integration_tests/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/src/templates/fees/Cargo.toml
Labels: P-acks_required

#598 chore: organise fmt config into nightly and stable
  rustfmt.toml
Labels: P-acks_required

#581 feat: jrpc for get all txs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: P-acks_required

#592 ci: new artifacts
  .github/workflows/base_node_binaries.yml
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
Labels: P-acks_required

#603 ci: last try on selfhosted
  .github/workflows/ci.yml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#593 feat: request missing TXs
  Cargo.lock
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/state_manager.rs
  applications/tari_validator_node/src/p2p/services/messaging/outbound.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_request_missing_transactions.rs
  dan_layer/consensus/src/hotstuff/on_receive_requested_transactions.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/consensus/src/messages/mod.rs
  dan_layer/consensus/src/messages/request_missing_transaction.rs
  dan_layer/consensus/src/messages/requested_transaction.rs
  dan_layer/consensus_tests/Cargo.toml
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/p2p/src/outbound_service.rs
  dan_layer/state_store_sqlite/migrations/2023-07-12-192955_add_missing_txs/down.sql
  dan_layer/state_store_sqlite/migrations/2023-07-12-192955_add_missing_txs/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/proto/consensus.proto
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
Labels: P-acks_required

#624 fix: use round robin leader strategy
  applications/tari_validator_node/src/consensus/leader_selection.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/spec.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/leader_strategy.rs
  dan_layer/consensus_tests/src/support/leader_strategy.rs
Labels: P-acks_required

#619 feat: jwt management page
  applications/tari_dan_wallet_web_ui/src/App.tsx
  applications/tari_dan_wallet_web_ui/src/Components/MenuItems.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccessTokens/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/JWTGrid.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Wallet.tsx
  applications/tari_dan_wallet_web_ui/src/theme/theme.css
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#621 fix: getting/revoking tokens
  applications/tari_dan_wallet_cli/src/command/auth.rs
  applications/tari_dan_wallet_daemon/src/handlers/rpc.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#626 fix: better errors and create free coins button
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_validator_node/log4rs_sample.yml
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/wasm/process.rs
Labels: P-acks_required, P-reviews_required

#622 fix(consensus)!: handle SomePrepared case, use less blocks
  applications/tari_validator_node/src/comms/initializer.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  dan_layer/common_types/src/committee.rs
  dan_layer/common_types/src/shard_id.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_request_missing_transactions.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/helpers.rs
  dan_layer/consensus_tests/src/support/mod.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/state_manager.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/serialization.rs
  dan_layer/state_store_sqlite/src/sql_models/substate.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction_pool.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/quorum_certificate.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/proto/consensus.proto
  dan_layer/validator_node_rpc/src/conversions/common.rs
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
Labels: P-acks_required

#625 fix(mempool): add transaction to state store before execution
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/services/mempool/executor.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/migrations/2023-07-12-192955_add_missing_txs/down.sql
  dan_layer/state_store_sqlite/migrations/2023-07-12-192955_add_missing_txs/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/mod.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/state_store/mod.rs
  integration_tests/tests/features/claim_burn.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
Labels: P-acks_required, P-reviews_required

#633 fix(consensus): wait for transaction execution before processing proposal
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/state_store/mod.rs
  integration_tests/tests/features/committee.feature
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/features/wallet_daemon.feature
Labels: P-acks_required

#634 refactor(engine-types): move transaction receipt into own module
  Cargo.lock
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/json_rpc/special_substate_encoding.rs
  applications/tari_validator_node/src/consensus/mod.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/engine_types/src/lib.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/engine_types/src/transaction_receipt.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
Labels: P-acks_required

#631 chore(template_lib): derive Ord/PartialOrd for NonFungibleAddress type
  dan_layer/template_lib/src/models/non_fungible.rs
Labels: P-acks_required

#628 feat: token permissions and ui updates
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Keys.tsx
Labels: P-acks_required

#636 fix: infinite loop in validator node UI
  applications/tari_validator_node_web_ui/src/routes/VN/Components/TemplateFunctions.tsx
Labels: P-acks_required

#637 refactor(consensus)!: use validator address for proposed_by in block
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_dan_wallet_web_ui/.gitignore
  applications/tari_dan_wallet_web_ui/dist/.gitkeep
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/spec.rs
  applications/tari_validator_node/src/consensus/state_manager.rs
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/committee_state_sync.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/messaging/mod.rs
  dan_layer/common_types/src/node_addressable.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_request_missing_transactions.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/consensus/src/messages/proposal.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus/src/traits/state_manager.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/address.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/spec.rs
  dan_layer/consensus_tests/src/support/state_manager.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/p2p/src/message.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/store.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/leaf_block.rs
  dan_layer/storage/src/consensus_models/locked_block.rs
  dan_layer/storage/src/consensus_models/quorum_certificate.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/src/client.rs
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
Labels: P-acks_required
