Repository tari-project/tari-ootle, pull requests merged in 2023-01, with the labels that each got.

#277 fix: exit validator node process on panic
  applications/tari_validator_node/src/http_ui/server.rs
  applications/tari_validator_node/src/main.rs
Labels: P-acks_required, CR-one_job

#278 feat(webui): add visualization of hotstuff nodes
  applications/tari_validator_node/openrpc.json
  applications/tari_validator_node_web_ui/package-lock.json
  applications/tari_validator_node_web_ui/package.json
  applications/tari_validator_node_web_ui/src/routes/Transaction/Components/Output.tsx
  applications/tari_validator_node_web_ui/src/routes/Transaction/Components/Substates.tsx
  applications/tari_validator_node_web_ui/src/routes/Transaction/Transaction.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/RecentTransactions.tsx
  dan_layer/core/src/models/mod.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#275 refactor(shard_store): split read and write operations in shard store
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
  applications/tari_validator_node/src/p2p/services/epoch_manager/state_sync.rs
  applications/tari_validator_node/src/p2p/services/template_manager/manager.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/integration_tests/src/temp_shard_store_factory.rs
  dan_layer/integration_tests/src/test_consensus.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
  dan_layer/storage_sqlite/src/sqlite_transaction.rs
Labels: P-acks_required

#286 fix: state sync regression
  dan_layer/core/src/storage/error.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-acks_required

#288 chore: update cargo.lock
  Cargo.lock
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/tests/templates/counter/Cargo.toml
  applications/tari_validator_node/tests/utils/miner.rs
  applications/tari_validator_node_cli/Cargo.toml
  dan_layer/common_types/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/engine/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/integration_tests/Cargo.toml
  dan_layer/template_test_tooling/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#290 feat: add dns4 multiaddr
  applications/tari_validator_node_cli/src/main.rs
Labels: CR-insufficient_context, P-acks_required

#291 fix: remove comma
  applications/tari_validator_node_cli/src/main.rs
Labels: P-acks_required

#297 chore: more openrpc examples
  applications/tari_validator_node/openrpc.json
Labels: CR-insufficient_context, P-acks_required

#299 fix(integration_tests): base node, wallet and template compilation is broken
  applications/tari_validator_node/tests/features/basic.feature
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/utils/base_node.rs
  applications/tari_validator_node/tests/utils/wallet.rs
Labels: P-merge

#298 fix: improve invalid peer error message
  applications/tari_validator_node/src/p2p/services/networking/peer_sync.rs
  applications/tari_validator_node/src/p2p/services/networking/service.rs
Labels: P-acks_required

#300 chore(integration_tests): use proper port initialization in base node and remove old CI tasks
  .github/workflows/dan_layer_integration_tests.yml
  .github/workflows/long_running.yml
  .github/workflows/non_critical_integration_tests.yml
  applications/tari_validator_node/tests/utils/base_node.rs
Labels: P-merge

#274 fix(consensus): reuse previous execution result for a payload
  applications/tari_validator_node/src/p2p/proto/conversions/consensus.rs
  applications/tari_validator_node/src/p2p/proto/conversions/network.rs
  applications/tari_validator_node/src/p2p/services/hotstuff/hotstuff_service.rs
  applications/tari_validator_node/src/p2p/services/messaging/dispatcher.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/common_types/src/quorum_certificate.rs
  dan_layer/common_types/src/shard_pledge.rs
  dan_layer/common_types/src/shard_vote.rs
  dan_layer/core/src/message.rs
  dan_layer/core/src/models/mod.rs
  dan_layer/core/src/models/payload.rs
  dan_layer/core/src/models/vote_message.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/integration_tests/src/test_consensus.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-acks_required

#302 fix(consensus): abandon pledges if not voting on rejected tx
  dan_layer/core/src/workers/hotstuff_waiter.rs
Labels: P-merge
