Repository tari-project/tari-ootle, pull requests merged in 2023-05, with the labels that each got.

#488 feat(walletd): scan vaults belonging to accounts, scan destination accounts when sending
  applications/tari_dan_app_grpc/src/conversions/transaction.rs
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/context.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/webrtc.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_daemon/src/services/mod.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/services/template_manager/manager.rs
  applications/tari_validator_node/src/p2p/services/template_manager/service.rs
  clients/validator_node_client/src/types.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/common_types/src/services/template_provider.rs
  dan_layer/engine/src/flow/workers/call_method_worker.rs
  dan_layer/engine/src/packager/package.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/transaction/error.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/wallet/sdk/src/apis/accounts.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/substate.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/models/substate.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  dan_layer/wallet/storage_sqlite/tests/substates.rs
Labels: P-acks_required

#494 fix(walletd): minor improvement to webrtc error handling and walletd webui
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/handlers/webrtc.rs
  applications/tari_dan_wallet_daemon/src/webrtc.rs
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Keys.tsx
  clients/tari_indexer_client/src/graphql_client.rs
Labels: P-acks_required

#495 feat: add jrcp from env and fix auth
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#499 feat!: templates can specify the component_id
  applications/tari_validator_node/tests/templates/basic_nft/Cargo.lock
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/faucet/Cargo.lock
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/airdrop.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/component/interface.rs
  dan_layer/template_lib/src/crypto.rs
  dan_layer/template_lib/src/engine.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/template_macros/src/template/definition.rs
  dan_layer/template_macros/src/template/dispatcher.rs
Labels: P-acks_required

#498 test: create pid on startup
  applications/tari_dan_wallet_cli/src/cli.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/main.rs
  applications/tari_signaling_server/src/jrpc_server.rs
  applications/tari_signaling_server/src/main.rs
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
  clients/wallet_daemon_client/src/types.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#504 chore: add license key to all crate.toml,cargo deny config
  .github/workflows/auto_labels.yml
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_wallet_cli/Cargo.toml
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_signaling_server/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node_cli/Cargo.toml
  applications/tari_web_extension/Cargo.toml
  clients/tari_indexer_client/Cargo.toml
  clients/validator_node_client/Cargo.toml
  clients/wallet_daemon_client/Cargo.toml
  comms/tari_comms_logging/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/engine/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/indexer_lib/Cargo.toml
  dan_layer/integration_tests/Cargo.toml
  dan_layer/storage_lmdb/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  dan_layer/tari_bor/Cargo.toml
  dan_layer/template_abi/Cargo.toml
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_macros/Cargo.toml
  dan_layer/template_test_tooling/Cargo.toml
  dan_layer/transaction/Cargo.toml
  dan_layer/transaction_manifest/Cargo.toml
  dan_layer/validator_node_rpc/Cargo.toml
  deny.toml
  rustfmt.toml
Labels: P-acks_required

#473 feat: add transaction construction to daemon
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  clients/wallet_daemon_client/src/types.rs
Labels: P-acks_required

#507 fix(vn): only return payload result from RPC/JRPC if finalized
  applications/tari_dan_wallet_daemon/src/indexer_jrpc_impl.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/transaction_manager/error.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  dan_layer/core/src/services/validator_node_rpc_client.rs
  dan_layer/core/src/storage/shard_store.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/storage_sqlite/migrations/2023-05-05-125535_add_is_finalized_to_payload/down.sql
  dan_layer/storage_sqlite/migrations/2023-05-05-125535_add_is_finalized_to_payload/up.sql
  dan_layer/storage_sqlite/src/models/payload.rs
  dan_layer/storage_sqlite/src/schema.rs
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: P-acks_required

#500 feat: event integration with graphql
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/graphql/model/mod.rs
  applications/tari_indexer/src/graphql/server.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2023-04-28-153806_create_events_table/down.sql
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2023-04-28-153806_create_events_table/up.sql
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  applications/tari_indexer/src/substate_storage_sqlite/models/mod.rs
  applications/tari_indexer/src/substate_storage_sqlite/schema.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/indexer.feature
  applications/tari_validator_node/tests/utils/indexer.rs
  clients/tari_indexer_client/src/graphql_client.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/engine/tests/events.rs
  dan_layer/engine/tests/templates/events/src/lib.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/events.rs
Labels: P-acks_required

#509 feat: account transfer creates destination account component
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_validator_node/tests/features/fungible.feature
  applications/tari_validator_node/tests/features/transfer.feature
  applications/tari_validator_node/tests/steps/validator_node.rs
  applications/tari_validator_node/tests/steps/wallet_daemon.rs
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/faucet/Cargo.lock
  applications/tari_validator_node/tests/utils/helpers.rs
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine_types/src/component.rs
  dan_layer/engine_types/src/lib.rs
  dan_layer/transaction/src/id_provider.rs
Labels: P-acks_required

#444 feat: add cucumber tests for faucet and confidential assets transfer using wallet daemon
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/claim_burn.feature
  applications/tari_validator_node/tests/features/fungible.feature
  applications/tari_validator_node/tests/features/transfer.feature
  applications/tari_validator_node/tests/features/wallet_daemon.feature
  applications/tari_validator_node/tests/steps/validator_node.rs
  applications/tari_validator_node/tests/steps/wallet_daemon.rs
  applications/tari_validator_node/tests/utils/helpers.rs
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  applications/tari_validator_node/tests/utils/wallet_daemon.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/types.rs
Labels: P-acks_required, P-reviews_required

#514 feat: add selecting permissions
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/webrtc.rs
  applications/tari_dan_wallet_daemon/src/handlers/webrtc.rs
  applications/tari_dan_wallet_daemon/src/webrtc.rs
  applications/tari_dan_wallet_web_ui/src/Components/ConnectorLink/ConnectorLink.tsx
  applications/tari_dan_wallet_web_ui/src/Components/ConnectorLink/Permissions.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_dan_wallet_web_ui/src/utils/tari_permissions.tsx
  applications/tari_signaling_server/Cargo.toml
  applications/tari_signaling_server/src/data.rs
  applications/tari_signaling_server/src/jrpc_server.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-05-09-120000_add_revokability/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-05-09-120000_add_revokability/up.sql
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#512 fix(walletd)!: free test commitment detectable by wallet, auto create account
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  applications/tari_dan_wallet_daemon/src/handlers/mod.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_daemon/src/services/events.rs
  applications/tari_indexer/src/substate_decoder.rs
  applications/tari_validator_node/tests/templates/basic_nft/Cargo.lock
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/faucet/Cargo.lock
  applications/tari_validator_node/tests/utils/helpers.rs
  applications/tari_validator_node/tests/utils/indexer.rs
  applications/tari_validator_node/tests/utils/validator_node.rs
  applications/tari_validator_node/tests/utils/wallet_daemon.rs
  clients/wallet_daemon_client/src/lib.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/transaction/error.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/templates/confidential/faucet/Cargo.lock
  dan_layer/engine/tests/templates/confidential/utilities/Cargo.lock
  dan_layer/engine/tests/templates/consensus/Cargo.lock
  dan_layer/engine/tests/templates/errors/Cargo.lock
  dan_layer/engine/tests/templates/events/Cargo.lock
  dan_layer/engine/tests/templates/faucet/Cargo.lock
  dan_layer/engine/tests/templates/nft/airdrop/Cargo.lock
  dan_layer/engine/tests/templates/nft/basic_nft/Cargo.lock
  dan_layer/engine/tests/templates/nft/emoji_id/Cargo.lock
  dan_layer/engine/tests/templates/nft/nft_list/Cargo.lock
  dan_layer/engine/tests/templates/state/Cargo.lock
  dan_layer/engine_types/src/confidential/validation.rs
  dan_layer/engine_types/src/confidential/withdraw.rs
  dan_layer/engine_types/src/instruction.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/validator_node_rpc/proto/transaction.proto
  dan_layer/validator_node_rpc/src/conversions/transaction.rs
  dan_layer/wallet/sdk/src/apis/confidential_crypto.rs
  dan_layer/wallet/sdk/src/apis/confidential_outputs.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
  dan_layer/wallet/sdk/src/confidential/mod.rs
  dan_layer/wallet/sdk/src/confidential/proof.rs
Labels: P-acks_required

#522 chore: bump the tari version
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_wallet_cli/Cargo.toml
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/comms/initializer.rs
  applications/tari_signaling_server/Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/comms/initializer.rs
  applications/tari_validator_node/tests/templates/fees/Cargo.toml
  applications/tari_validator_node/tests/utils/base_node.rs
  applications/tari_validator_node/tests/utils/indexer.rs
  applications/tari_validator_node/tests/utils/validator_node.rs
  applications/tari_validator_node/tests/utils/wallet.rs
  applications/tari_validator_node_cli/Cargo.toml
  clients/tari_indexer_client/Cargo.toml
  clients/validator_node_client/Cargo.toml
  clients/wallet_daemon_client/Cargo.toml
  dan_layer/common_types/Cargo.toml
  dan_layer/core/Cargo.toml
  dan_layer/engine/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/integration_tests/Cargo.toml
  dan_layer/storage/Cargo.toml
  dan_layer/storage_lmdb/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  dan_layer/template_builtin/templates/account/Cargo.lock
  dan_layer/transaction/Cargo.toml
  dan_layer/validator_node_rpc/Cargo.toml
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/storage_sqlite/Cargo.toml
Labels: P-acks_required

#523 fix: auth call in dan wallet ui
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#510 refactor: remove fee loans
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/payload_processor.rs
  dan_layer/engine/src/fees/fee_table.rs
  dan_layer/engine/src/fees/mod.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/template_test_tooling/src/template_test.rs
Labels: P-acks_required

#511 refactor: create destination account on confidential transfers
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_validator_node/tests/features/transfer.feature
  applications/tari_validator_node/tests/steps/wallet_daemon.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#524 ci: add cucumber result file
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/counter.feature
  applications/tari_validator_node/tests/features/fungible.feature
  applications/tari_validator_node/tests/log4rs/cucumber.yml
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/counter/Cargo.toml
  applications/tari_validator_node/tests/utils/helpers.rs
  applications/tari_validator_node/tests/utils/miner.rs
  applications/tari_validator_node/tests/utils/wallet.rs
  dan_layer/engine/tests/templates/caller_context/Cargo.lock
  dan_layer/engine/tests/templates/confidential/faucet/Cargo.lock
  dan_layer/engine/tests/templates/confidential/utilities/Cargo.lock
  dan_layer/engine/tests/templates/consensus/Cargo.lock
  dan_layer/engine/tests/templates/errors/Cargo.lock
  dan_layer/engine/tests/templates/events/Cargo.lock
  dan_layer/engine/tests/templates/hello_world/Cargo.lock
  dan_layer/engine/tests/templates/nft/airdrop/Cargo.lock
  dan_layer/engine/tests/templates/nft/basic_nft/Cargo.lock
  dan_layer/engine/tests/templates/nft/emoji_id/Cargo.lock
  dan_layer/engine/tests/templates/nft/nft_list/Cargo.lock
  dan_layer/engine/tests/templates/nft/tickets/Cargo.lock
  dan_layer/engine/tests/templates/private_function/Cargo.lock
  dan_layer/engine/tests/templates/random/Cargo.lock
  dan_layer/engine/tests/templates/state/Cargo.lock
  dan_layer/engine/tests/templates/tuples/Cargo.lock
Labels: CR-insufficient_context

#516 feat: adds tx result to network substates
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_validator_node/tests/features/wallet_daemon.feature
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_cli/src/component_manager.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/argument_parser.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/engine_types/src/hashing.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_lib/src/lib.rs
  dan_layer/template_lib/src/models/binary_tag.rs
  dan_layer/transaction_manifest/src/generator.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
Labels: CR-too_long, P-acks_required, P-reviews_required

#526 test: fix cucumber
  .github/workflows/ci.yml
  .github/workflows/test_results.yml
  .gitignore
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/main.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/claim_burn.feature
  applications/tari_validator_node/tests/features/committee.feature
  applications/tari_validator_node/tests/features/indexer.feature
  applications/tari_validator_node/tests/features/leader_failure.feature
  applications/tari_validator_node/tests/features/transfer.feature
  applications/tari_validator_node/tests/features/wallet_daemon.feature
  applications/tari_validator_node/tests/templates/basic_nft/Cargo.lock
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/templates/faucet/Cargo.lock
  applications/tari_validator_node/tests/utils/base_node.rs
  applications/tari_validator_node/tests/utils/indexer.rs
  applications/tari_validator_node/tests/utils/validator_node.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/templates/caller_context/Cargo.lock
  dan_layer/engine/tests/templates/confidential/faucet/Cargo.lock
  dan_layer/engine/tests/templates/confidential/utilities/Cargo.lock
  dan_layer/engine/tests/templates/consensus/Cargo.lock
  dan_layer/engine/tests/templates/errors/Cargo.lock
  dan_layer/engine/tests/templates/events/Cargo.lock
  dan_layer/engine/tests/templates/faucet/Cargo.lock
  dan_layer/engine/tests/templates/hello_world/Cargo.lock
  dan_layer/engine/tests/templates/nft/airdrop/Cargo.lock
  dan_layer/engine/tests/templates/nft/basic_nft/Cargo.lock
  dan_layer/engine/tests/templates/nft/emoji_id/Cargo.lock
  dan_layer/engine/tests/templates/nft/nft_list/Cargo.lock
  dan_layer/engine/tests/templates/nft/tickets/Cargo.lock
  dan_layer/engine/tests/templates/private_function/Cargo.lock
  dan_layer/engine/tests/templates/random/Cargo.lock
  dan_layer/engine/tests/templates/state/Cargo.lock
  dan_layer/engine/tests/templates/tariswap/Cargo.lock
  dan_layer/engine/tests/templates/tuples/Cargo.lock
  dan_layer/template_builtin/templates/account/account.wasm
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#503 fix(consenus): vote reject and release pledges if remote pledges invalid
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/tests/steps/validator_node.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
Labels: P-acks_required, P-reviews_required

#505 feat: adds test for leader failure with multiple committees, corrects previous bug
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/leader_failure.feature
  applications/tari_validator_node_cli/src/command/transaction.rs
  dan_layer/transaction/src/builder.rs
Labels: P-acks_required

#528 fix: reject transaction if component address is duplicate
  .gitignore
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/claim_burn.feature
  applications/tari_validator_node/tests/features/transfer.feature
  applications/tari_validator_node/tests/features/wallet_daemon.feature
  applications/tari_validator_node/tests/steps/validator_node.rs
  applications/tari_validator_node/tests/steps/wallet_daemon.rs
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/wallet/sdk/src/apis/accounts.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: P-acks_required

#531 feat: add serde serialization to optionals
  dan_layer/engine_types/src/serde_with/hex.rs
Labels: P-acks_required

#527 feat: adds event indexing over component addresses
  Cargo.lock
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/p2p/services/epoch_manager/epoch_manager_service.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2023-05-19-165832_add_version_to_events_table/down.sql
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2023-05-19-165832_add_version_to_events_table/up.sql
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  applications/tari_indexer/src/substate_storage_sqlite/schema.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/indexer.feature
  applications/tari_validator_node/tests/features/wallet_daemon.feature
  applications/tari_validator_node/tests/templates/counter/Cargo.lock
  applications/tari_validator_node/tests/utils/indexer.rs
  applications/tari_validator_node/tests/utils/validator_node_cli.rs
  clients/tari_indexer_client/src/graphql_client.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/core/src/consensus_constants.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/engine/tests/events.rs
  dan_layer/engine/tests/templates/events/src/lib.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/indexer_lib/Cargo.toml
  dan_layer/indexer_lib/src/error.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_lib/src/args/engine.rs
  dan_layer/template_lib/src/engine.rs
  dan_layer/template_lib/src/events.rs
  dan_layer/template_lib/src/models/component.rs
  dan_layer/template_macros/src/template/definition.rs
  dan_layer/template_macros/src/template/dispatcher.rs
  dan_layer/validator_node_rpc/proto/rpc.proto
  dan_layer/validator_node_rpc/src/client.rs
Labels: CR-too_long

#532 fix: remove unnecessary checked_sub and expect
  applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs
Labels: P-acks_required

#538 fix!: use ordered map (BTreeMap) for substates
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  applications/tari_validator_node/tests/cucumber.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_lib/src/models/metadata.rs
Labels: P-acks_required
