Repository tari-project/tari-ootle, pull requests merged in 2023-11, with the labels that each got.

#756 fix(cucumber): fix test in wallet_daemon.feature + improve scan step
  integration_tests/tests/features/block_sync.feature
  integration_tests/tests/features/claim_burn.feature
  integration_tests/tests/features/claim_fees.feature
  integration_tests/tests/features/committee.feature
  integration_tests/tests/features/counter.feature
  integration_tests/tests/features/fungible.feature
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/features/nft.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
  integration_tests/tests/steps/indexer.rs
  integration_tests/tests/steps/validator_node.rs
Labels: P-acks_required

#744 feat: adds settings JSON-RPC call to allow changes to indexer URL
  Cargo.lock
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/handlers/mod.rs
  applications/tari_dan_wallet_daemon/src/handlers/settings.rs
  applications/tari_dan_wallet_daemon/src/indexer_jrpc_impl.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ActionMenu.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/config.rs
  dan_layer/wallet/sdk/src/network.rs
  dan_layer/wallet/sdk/src/sdk.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
Labels: P-acks_required

#758 chore: remove unused envvar from dan wallet ui
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#729 feat: add transaction failure reason
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/helpers.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/validator.rs
  applications/tari_dan_wallet_daemon/src/services/events.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service.rs
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Substates.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  clients/validator_node_client/src/types.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/tests/fees.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/wallet_transaction.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-02-08-122514_initial/up.sql
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  integration_tests/src/validator_node_cli.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#759 fix: onboarding flow
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/AssetVault.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/MyAssets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionsLayout.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Wallet.tsx
Labels: P-acks_required

#763 fix(indexer): correct json rpc address
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer_web_ui/src/utils/json_rpc.tsx
  applications/tari_validator_node/src/lib.rs
Labels: CR-insufficient_context, P-acks_required

#755 feat: foreign proposal broadcast
  dan_layer/comms_rpc_state_sync/src/manager.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/proposer.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/storage/src/consensus_models/block.rs
Labels: P-acks_required

#764 fix(github-actions): fix CI test result stall caused by title update
  .github/workflows/test_results.yml
Labels: P-acks_required

#766 fix(mempool): correct shard id for transaction receipt
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/common_types/src/shard_id.rs
  dan_layer/engine_types/src/substate.rs
Labels: P-acks_required

#770 ci(fix): update binary workflow
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
  Cross.toml
Labels: P-acks_required

#765 refactor(mempool): move epoch range check to validators
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/epoch_range.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/mod.rs
Labels: P-acks_required

#767 fix(template): improvements to template testing api
  Cargo.lock
  applications/tari_dan_app_utilities/src/template_manager/implementation/manager.rs
  applications/tari_dan_app_utilities/src/template_manager/interface/error.rs
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_scaffolder/src/main.rs
  applications/tari_validator_node/src/transaction_processor.rs
  dan_layer/engine/src/flow/flow_context.rs
  dan_layer/engine/src/flow/flow_factory.rs
  dan_layer/engine/src/flow/flow_instance.rs
  dan_layer/engine/src/flow/workers/arg_worker.rs
  dan_layer/engine/src/flow/workers/call_method_worker.rs
  dan_layer/engine/src/lib.rs
  dan_layer/engine/src/packager/package.rs
  dan_layer/engine/src/packager/template_loader.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/template/error.rs
  dan_layer/engine/src/template/loaded_template.rs
  dan_layer/engine/src/template/mod.rs
  dan_layer/engine/src/template/template_loader.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/src/wasm/module.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine/tests/composability.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/reentrancy.rs
  dan_layer/engine/tests/shenanigans.rs
  dan_layer/engine/tests/tariswap.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine/tests/templates/faucet/Cargo.toml
  dan_layer/engine/tests/templates/faucet/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/component.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/template_lib/src/crypto.rs
  dan_layer/template_lib/src/lib.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/proof.rs
  dan_layer/template_lib/src/models/vault.rs
  dan_layer/template_lib/src/prelude.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_macros/src/lib.rs
  dan_layer/template_macros/src/template/ast.rs
  dan_layer/template_macros/src/template/definition.rs
  dan_layer/template_macros/src/template/dispatcher.rs
  dan_layer/template_macros/src/template/mod.rs
  dan_layer/template_test_tooling/Cargo.toml
  dan_layer/template_test_tooling/src/lib.rs
  dan_layer/template_test_tooling/src/package_builder.rs
  dan_layer/template_test_tooling/src/read_only_state_store.rs
  dan_layer/template_test_tooling/src/support/assert_error.rs
  dan_layer/template_test_tooling/src/support/confidential.rs
  dan_layer/template_test_tooling/src/support/mod.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  dan_layer/template_test_tooling/templates/faucet/src/lib.rs
  dan_layer/transaction/src/builder.rs
Labels: P-acks_required

#769 fix(template): add mint_confidential call
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/template_lib/src/resource/manager.rs
Labels: P-acks_required

#772 chore: fix cargo fmt
  dan_layer/engine/tests/confidential.rs
Labels: P-acks_required

#776 chore: update tari libs to include stable fix
  Cargo.lock
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_signaling_server/Cargo.toml
Labels: P-acks_required

#775 ci(fix): docker build from workflow
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  docker_rig/README.md
  docker_rig/cross-compile-tooling.sh
  docker_rig/tari-dan.Dockerfile
Labels: P-acks_required

#773 feat(engine): implement recall
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/json_rpc/json_encoding.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker_auth.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/recall.rs
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/recall/Cargo.toml
  dan_layer/engine/tests/templates/recall/src/lib.rs
  dan_layer/engine_types/src/confidential/withdraw.rs
  dan_layer/engine_types/src/instruction_result.rs
  dan_layer/engine_types/src/resource_container.rs
  dan_layer/engine_types/src/vault.rs
  dan_layer/storage/Cargo.toml
  dan_layer/storage_sqlite/Cargo.toml
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/auth/access_rules.rs
  dan_layer/template_lib/src/crypto.rs
  dan_layer/template_lib/src/crypto/balance_proof.rs
  dan_layer/template_lib/src/crypto/commitment.rs
  dan_layer/template_lib/src/crypto/error.rs
  dan_layer/template_lib/src/crypto/mod.rs
  dan_layer/template_lib/src/crypto/ristretto.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_lib/src/models/vault.rs
  dan_layer/template_lib/src/prelude.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/template_lib/src/resource/mod.rs
  dan_layer/template_test_tooling/src/support/confidential.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/validator_node_rpc/src/conversions/transaction.rs
  dan_layer/wallet/sdk/src/apis/confidential_crypto.rs
  utilities/transaction_submitter/Cargo.toml
Labels: P-acks_required

#771 fix(templates): minor improvements,add ComponentManager::get_template_address
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine/tests/composability.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/recall.rs
  dan_layer/engine/tests/reentrancy.rs
  dan_layer/engine/tests/shenanigans.rs
  dan_layer/engine/tests/templates/component_manager/Cargo.toml
  dan_layer/engine/tests/templates/component_manager/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/component/manager.rs
  dan_layer/template_lib/src/models/proof.rs
  dan_layer/template_lib/src/models/vault.rs
  dan_layer/template_test_tooling/src/lib.rs
  dan_layer/template_test_tooling/src/support/crypto.rs
  dan_layer/template_test_tooling/src/support/mod.rs
Labels: P-acks_required

#779 feat: add result to transaction details pages
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/TransactionDetails.tsx
Labels: P-acks_required

#780 feat: add metadata string parser
  dan_layer/engine_types/src/argument_parser.rs
  dan_layer/template_lib/src/models/metadata.rs
Labels: P-acks_required

#782 ci(fix): docker - add openssl and ca-certificates to runtime
  docker_rig/tari-dan.Dockerfile
Labels: P-acks_required

#783 fix: default committee size
  applications/tari_dan_app_utilities/src/consensus_constants.rs
Labels: P-acks_required

#781 feat(ui): show reject reasons
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/TransactionDetails.tsx
Labels: CR-insufficient_context, P-acks_required

#768 fix: multi committee transaction
  applications/tari_validator_node/src/consensus/state_manager.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/traits/state_manager.rs
  dan_layer/consensus_tests/src/support/state_manager.rs
  dan_layer/state_store_sqlite/src/reader.rs
Labels: P-acks_required

#784 docs: add basic clean virtualised linux install and build notes
  .license.ignore
  buildtools/build-notes.md
  buildtools/vagrant/.gitignore
  buildtools/vagrant/Vagrantfile
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required

#785 feat: better tuple support in templates
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  dan_layer/engine/tests/templates/tuples/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/template_abi/src/types.rs
  dan_layer/template_macros/src/template/abi.rs
  dan_layer/template_macros/src/template/ast.rs
  dan_layer/template_macros/src/template/dispatcher.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required

#751 feat: improve scaffolding
  applications/tari_indexer_web_ui/src/routes/VN/Components/Connections.tsx
  applications/tari_scaffolder/src/main.rs
  applications/tari_scaffolder/src/template/Cargo.toml.liquid
  applications/tari_scaffolder/src/template/src/cli.rs.liquid
  applications/tari_scaffolder/src/template/src/daemon_client.rs.liquid
  applications/tari_scaffolder/src/template/src/main.rs.liquid
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Connections.tsx
  dan_layer/template_lib/src/models/metadata.rs
  dan_layer/transaction/src/builder.rs
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#786 fix: the genesis block_id values should be 0
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/comms_rpc_state_sync/src/manager.rs
Labels: P-acks_required

#790 ci(fix): bring ci in sync and remove deprecated actions
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
  .github/workflows/build_dockers.yml
  .github/workflows/build_dockers_workflow.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/pr_title.yml
  .github/workflows/test_results.yml
Labels: P-acks_required

#757 feat!: foreign broadcast reliability counter
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/proposer.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/sql_models/bookkeeping.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/foreign_receive_counters.rs
  dan_layer/storage/src/consensus_models/foreign_send_counters.rs
  dan_layer/storage/src/consensus_models/mod.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/proto/consensus.proto
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
Labels: P-acks_required

#795 fix(wallet_daemon_web_ui): send correct max_fee param on transfers
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
Labels: P-acks_required
