Repository tari-project/tari-ootle, pull requests merged in 2023-06, with the labels that each got.

#534 feat: address substate manager todos
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required

#539 feat: add jrpc method for revoking the permission token
  applications/tari_dan_wallet_cli/src/command/auth.rs
  applications/tari_dan_wallet_daemon/src/handlers/rpc.rs
  applications/tari_dan_wallet_daemon/src/handlers/webrtc.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#536 feat: indexer auto-fills transaction inputs
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/transaction_manager/error.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_validator_node/src/payload_processor.rs
  applications/tari_validator_node/tests/cucumber.rs
  applications/tari_validator_node/tests/features/leader_failure.feature
  applications/tari_validator_node/tests/features/transfer.feature
  applications/tari_validator_node/tests/log4rs/cucumber.yml
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/indexer_lib/Cargo.toml
  dan_layer/indexer_lib/src/lib.rs
  dan_layer/indexer_lib/src/substate_decoder.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/indexer_lib/src/transaction_autofiller.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/transaction/src/builder.rs
  dan_layer/transaction/src/lib.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/validator_node_rpc/proto/transaction.proto
  dan_layer/validator_node_rpc/src/conversions/transaction.rs
  dan_layer/wallet/sdk/src/models/substate.rs
Labels: P-acks_required, P-reviews_required

#541 feat: add account nft template
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/template_builtin/build.rs
  dan_layer/template_builtin/src/lib.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_builtin/templates/account_nfts/Cargo.toml
  dan_layer/template_builtin/templates/account_nfts/account_nfts.wasm
  dan_layer/template_builtin/templates/account_nfts/src/lib.rs
  dan_layer/template_lib/src/models/metadata.rs
Labels: P-acks_required

#543 refactor: represent tariswap fee as a per-mil amount
  dan_layer/engine/tests/tariswap.rs
  dan_layer/engine/tests/templates/tariswap/src/lib.rs
Labels: P-acks_required

#535 feat(walletui): transaction confirmation popup
  applications/tari_dan_wallet_web_ui/src/Components/ConnectorLink/ConfirmTransaction.tsx
  applications/tari_dan_wallet_web_ui/src/Components/ConnectorLink/ConnectorLink.tsx
Labels: P-acks_required

#544 feat(tari_validator_node_cli): extract each type of substate address
  applications/tari_validator_node_cli/src/command/transaction.rs
Labels: P-acks_required

#542 fix(walletd): include required inputs for transfer
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  dan_layer/indexer_lib/src/substate_decoder.rs
  dan_layer/indexer_lib/src/transaction_autofiller.rs
  dan_layer/transaction/src/builder.rs
Labels: P-acks_required

#547 feat(walletd): add naming to the JWT tokens
  applications/tari_dan_wallet_cli/src/command/auth.rs
  applications/tari_dan_wallet_daemon/src/handlers/rpc.rs
  applications/tari_dan_wallet_daemon/src/handlers/webrtc.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: P-acks_required

#549 fix: jwt permission issues between wallet daemon and signaling server
  Cargo.lock
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_web_ui/src/utils/tari_permissions.tsx
  applications/tari_signaling_server/Cargo.toml
  applications/tari_signaling_server/src/data.rs
  applications/tari_signaling_server/src/jrpc_server.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
Labels: P-acks_required

#551 fix: get fees query
  applications/tari_validator_node/openrpc.json
  dan_layer/storage_sqlite/src/sqlite_shard_store_factory.rs
Labels: CR-too_long, P-acks_required

#554 fix: fix to use correct signing key when submitting instruction
  applications/tari_dan_wallet_daemon/log4rs_sample.yml
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer/log4rs_sample.yml
  applications/tari_indexer/src/json_rpc/server.rs
  applications/tari_signaling_server/src/data.rs
  applications/tari_validator_node/tests/utils/wallet_daemon_cli.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/storage/src/models/substate_shard_data.rs
  dan_layer/wallet/sdk/src/apis/jwt.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-02-08-122514_initial/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-04-25-155300_add_auth_status/up.sql
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#558 fix: stop retriggering redraw
  applications/tari_validator_node_web_ui/src/Components/SearchFilter.tsx
Labels: P-acks_required

#559 fix: confidential transfers
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
Labels: P-acks_required

#565 fix: dan wallet ui the "unsupported" columns
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
Labels: P-acks_required

#568 feat(consensus): add on vote receved and transaction executor
  Cargo.lock
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/transaction_executor/mod.rs
  applications/tari_validator_node/src/transaction_executor/traits.rs
  applications/tari_validator_node/src/transaction_executor/worker.rs
  dan_layer/common_types/src/committee.rs
  dan_layer/common_types/src/hashing.rs
  dan_layer/common_types/src/shard_id.rs
  dan_layer/consensus/Cargo.toml
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/consensus/src/messages/vote.rs
  dan_layer/consensus/src/traits/epoch_manager.rs
  dan_layer/consensus/src/traits/signing_service.rs
  dan_layer/core/src/consensus_constants.rs
  dan_layer/epoch_manager/src/base_layer/base_layer_epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/config.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/mod.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction.rs
  dan_layer/state_store_sqlite/src/sql_models/vote.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/Cargo.toml
  dan_layer/storage/src/consensus_models/mod.rs
  dan_layer/storage/src/consensus_models/quorum.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/consensus_models/transaction_pools.rs
  dan_layer/storage/src/consensus_models/vote.rs
  dan_layer/storage/src/consensus_models/vote_signature.rs
  dan_layer/storage/src/global/backend_adapter.rs
  dan_layer/storage/src/global/models/validator_node.rs
  dan_layer/storage/src/global/validator_node_db.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  dan_layer/storage_sqlite/src/global/models/validator_node.rs
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_builtin/templates/account_nfts/account_nfts.wasm
Labels: P-acks_required, P-reviews_required

#573 fix: fix issue in existing cucumber test
  applications/tari_validator_node/tests/features/transfer.feature
Labels: P-acks_required

#566 fix: gitignore wasm binaries
  dan_layer/template_builtin/templates/.gitignore
  dan_layer/template_builtin/templates/account/account.wasm
  dan_layer/template_builtin/templates/account_nfts/account_nfts.wasm
Labels: P-acks_required

#575 feat: add account nft get and list methods on the daemon
  applications/tari_dan_wallet_cli/src/command/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/engine_types/src/resource.rs
  dan_layer/template_builtin/templates/account_nfts/src/lib.rs
  dan_layer/wallet/sdk/src/apis/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/models/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-06-21-122832_add_token_symbol_to_nft_table/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-21-122832_add_token_symbol_to_nft_table/up.sql
  dan_layer/wallet/storage_sqlite/src/models/non_fungible_tokens.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#579 fix(wallet_daemon): proper permissions on `wait_result` method
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
Labels: P-acks_required
