Repository tari-project/tari-ootle, pull requests merged in 2023-03, with the labels that each got.

#442 fix(wallet): add fee support to the remaining transaction commands
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_daemon/src/services/events.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/wallet_transaction.rs
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
Labels: P-acks_required

#443 fix(mempool): return error to caller if tx fails validation
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/mempool/handle.rs
  applications/tari_validator_node/src/p2p/services/mempool/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
Labels: P-acks_required

#440 feat: add dan wallet ui
  applications/tari_dan_wallet_web_ui/.gitignore
  applications/tari_dan_wallet_web_ui/index.html
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
  applications/tari_dan_wallet_web_ui/src/App.css
  applications/tari_dan_wallet_web_ui/src/App.tsx
  applications/tari_dan_wallet_web_ui/src/Components/AlertDialog.tsx
  applications/tari_dan_wallet_web_ui/src/Components/CopyToClipboard.tsx
  applications/tari_dan_wallet_web_ui/src/Components/Copyright.tsx
  applications/tari_dan_wallet_web_ui/src/Components/HeadingMenu.tsx
  applications/tari_dan_wallet_web_ui/src/Components/JsonTooltip.tsx
  applications/tari_dan_wallet_web_ui/src/Components/Logo.tsx
  applications/tari_dan_wallet_web_ui/src/Components/MenuItems.tsx
  applications/tari_dan_wallet_web_ui/src/Components/PageHeading.tsx
  applications/tari_dan_wallet_web_ui/src/Components/SecondaryHeading.tsx
  applications/tari_dan_wallet_web_ui/src/Components/StyledComponents.ts
  applications/tari_dan_wallet_web_ui/src/Components/Title.tsx
  applications/tari_dan_wallet_web_ui/src/Components/TransactionFilter.tsx
  applications/tari_dan_wallet_web_ui/src/index.css
  applications/tari_dan_wallet_web_ui/src/main.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Accounts/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/ErrorPage.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Keys/Keys.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Error.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Keys.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Wallet.css
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Wallet.tsx
  applications/tari_dan_wallet_web_ui/src/theme.ts
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_dan_wallet_web_ui/src/vite-env.d.ts
  applications/tari_dan_wallet_web_ui/tsconfig.json
  applications/tari_dan_wallet_web_ui/tsconfig.node.json
  applications/tari_dan_wallet_web_ui/vite.config.ts
Labels: CR-too_long

#447 feat(vnui): add payload details to transaction screen
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service.rs
  applications/tari_indexer/src/comms/broadcast.rs
  applications/tari_validator_node/src/comms/broadcast.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/jrpc_errors.rs
  applications/tari_validator_node/src/json_rpc/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/messaging/outbound.rs
  applications/tari_validator_node/src/p2p/services/networking/service.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_web_ui/src/routes/Transaction/Transaction.tsx
  applications/tari_validator_node_web_ui/src/utils/helpers.tsx
  clients/wallet_daemon_client/src/types.rs
  dan_layer/core/src/workers/hotstuff_waiter.rs
  dan_layer/core/src/workers/pacemaker_worker.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/template_builtin/templates/account/account.wasm
Labels: P-acks_required, P-reviews_required
