Repository tari-project/tari-ootle, pull requests merged in 2023-09, with the labels that each got.

#675 fix: stable clippy
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/services/mod.rs
  applications/tari_validator_node_cli/src/component_manager.rs
  applications/tari_web_extension/src/lib.rs
  dan_layer/engine/src/state_store/memory.rs
  dan_layer/template_lib/src/models/metadata.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  integration_tests/tests/cucumber.rs
Labels: P-acks_required

#647 feat(wallet): new permission for public key listing
  applications/tari_dan_wallet_daemon/src/handlers/keys.rs
  applications/tari_dan_wallet_web_ui/src/utils/tari_permissions.tsx
  dan_layer/wallet/sdk/src/apis/jwt.rs
Labels: P-acks_required

#674 fix: panic on empty confidential
  dan_layer/engine/src/runtime/tracker.rs
Labels: P-acks_required

#676 docs: new web-wallet sequence diagram
  docs/wallet_sequence_diagram.md
Labels: P-acks_required

#682 feat: random JWT secrets on wallet daemon and signaling server
  Cargo.lock
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_signaling_server/Cargo.toml
  applications/tari_signaling_server/src/data.rs
  dan_layer/common_types/src/crypto.rs
Labels: P-acks_required

#667 fix(template-manager): prevent unncessary wasm loading in high concurrency
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_app_utilities/src/template_manager/implementation/cmap_semaphore.rs
  applications/tari_dan_app_utilities/src/template_manager/implementation/manager.rs
  applications/tari_dan_app_utilities/src/template_manager/implementation/mod.rs
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/engine/src/wasm/module.rs
  dan_layer/template_builtin/src/lib.rs
  dan_layer/template_test_tooling/src/template_test.rs
Labels: P-acks_required

#653 feat(template-lib)!: impl human readable (de)serializer for address newtypes
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/engine/src/bootstrap.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/fees.rs
  dan_layer/tari_bor/Cargo.toml
  dan_layer/template_builtin/templates/account/Cargo.lock
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_lib/src/constants.rs
  dan_layer/template_lib/src/hash.rs
  dan_layer/template_lib/src/lib.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/component.rs
  dan_layer/template_lib/src/models/layer_one_commitment.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/template_lib/src/models/non_fungible_index.rs
  dan_layer/template_lib/src/models/resource.rs
  dan_layer/template_lib/src/models/vault.rs
  dan_layer/template_lib/src/newtype_serde_macros.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#692 test(consensus): ignore flaky test for now
  .config/nextest.toml
  dan_layer/consensus_tests/src/consensus.rs
Labels: P-acks_required

#677 fix(consensus)!: undo pending transaction stage transitions on leader fail
  applications/tari_validator_node/src/dan_node.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/event.rs
  dan_layer/consensus/src/hotstuff/on_next_sync_view.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/pacemaker.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/leader_strategy.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/leader_strategy.rs
  dan_layer/consensus_tests/src/support/logging.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/spec.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction_pool.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/last_proposed.rs
  dan_layer/storage/src/consensus_models/last_voted.rs
  dan_layer/storage/src/consensus_models/leaf_block.rs
  dan_layer/storage/src/consensus_models/locked_block.rs
  dan_layer/storage/src/consensus_models/quorum_certificate.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/error.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required

#680 docs(consensus): initial diagram for consensus state machine
  docs/consensus_state_machine.md
  docs/wallet_sequence_diagram.md
Labels: P-acks_required, P-reviews_required

#681 fix(vn): add dedicated messaging substream for consensus msgs
  applications/tari_indexer/src/comms/broadcast.rs
  applications/tari_indexer/src/comms/deserialize.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/comms/broadcast.rs
  applications/tari_validator_node/src/comms/deserialize.rs
  applications/tari_validator_node/src/comms/initializer.rs
  applications/tari_validator_node/src/comms/logger.rs
  applications/tari_validator_node/src/comms/mod.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/p2p/services/messaging/dispatcher.rs
  applications/tari_validator_node/src/p2p/services/messaging/inbound.rs
  applications/tari_validator_node/src/p2p/services/messaging/mod.rs
  applications/tari_validator_node/src/p2p/services/messaging/outbound.rs
  comms/tari_comms_logging/src/sqlite_message_log.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/p2p/src/lib.rs
  dan_layer/p2p/src/message.rs
  dan_layer/p2p/src/outbound_service.rs
  dan_layer/validator_node_rpc/proto/network.proto
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
  dan_layer/validator_node_rpc/src/conversions/network.rs
  utilities/transaction_submitter/src/main.rs
Labels: CR-too_long, P-acks_required

#696 docs: adapt web-wallet diagram to tari-connector changes
  docs/wallet_sequence_diagram.md
Labels: P-acks_required

#701 fix(tari-bor): ciborium_io error for nostd after merge
  Cargo.lock
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/jrpc_errors.rs
  clients/tari_indexer_client/src/json_rpc_client.rs
  clients/tari_indexer_client/src/types.rs
  dan_layer/engine/tests/templates/buggy/Cargo.toml
  dan_layer/tari_bor/Cargo.toml
  dan_layer/tari_bor/src/error.rs
  dan_layer/tari_bor/src/lib.rs
  integration_tests/src/lib.rs
  integration_tests/tests/features/claim_fees.feature
  integration_tests/tests/features/committee.feature
  integration_tests/tests/steps/indexer.rs
  integration_tests/tests/steps/mod.rs
  integration_tests/tests/steps/validator_node.rs
Labels: P-acks_required

#700 test(consensus): readd leader_failure_output_conflict
  clients/tari_indexer_client/src/graphql_client.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/template_builtin/templates/account/Cargo.lock
Labels: P-acks_required

#702 feat(consensus): consensus state machine
  applications/tari_validator_node/src/consensus/mod.rs
  clients/tari_indexer_client/src/graphql_client.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/pacemaker.rs
  dan_layer/consensus/src/hotstuff/pacemaker_handle.rs
  dan_layer/consensus/src/hotstuff/state_machine/check_sync.rs
  dan_layer/consensus/src/hotstuff/state_machine/event.rs
  dan_layer/consensus/src/hotstuff/state_machine/idle.rs
  dan_layer/consensus/src/hotstuff/state_machine/mod.rs
  dan_layer/consensus/src/hotstuff/state_machine/running.rs
  dan_layer/consensus/src/hotstuff/state_machine/state.rs
  dan_layer/consensus/src/hotstuff/state_machine/syncing.rs
  dan_layer/consensus/src/hotstuff/state_machine/worker.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/steps/validator_node.rs
Labels: P-acks_required

#705 fix: fix adding an account in wallet UI
  applications/tari_dan_wallet_daemon/build.rs
  applications/tari_dan_wallet_web_ui/dist/.gitkeep
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AddAccount.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#630 docs: add some docs to the template_lib
  dan_layer/template_lib/src/consensus.rs
  dan_layer/template_lib/src/lib.rs
  dan_layer/template_lib/src/prelude.rs
Labels: P-acks_required

#693 feat(mempool): efficient transaction gossip
  applications/tari_indexer/src/dry_run/processor.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/p2p/services/mempool/gossip.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/messaging/dispatcher.rs
  applications/tari_validator_node/src/p2p/services/messaging/mod.rs
  applications/tari_validator_node/src/p2p/services/messaging/outbound.rs
  dan_layer/common_types/src/committee.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/base_layer_epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/handle.rs
  dan_layer/epoch_manager/src/base_layer/types.rs
  dan_layer/epoch_manager/src/error.rs
  dan_layer/epoch_manager/src/traits.rs
  dan_layer/p2p/src/message.rs
  dan_layer/p2p/src/outbound_service.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  dan_layer/transaction/src/transaction.rs
Labels: P-acks_required

#671 feat: blocks in vn ui
  Cargo.lock
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node_web_ui/src/App.tsx
  applications/tari_validator_node_web_ui/src/Components/MenuItems.tsx
  applications/tari_validator_node_web_ui/src/Components/SearchFilter.tsx
  applications/tari_validator_node_web_ui/src/index.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/BlockDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/Blocks.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/Transactions.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Blocks.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/RecentTransactions.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/ValidatorNode.css
  applications/tari_validator_node_web_ui/src/routes/VN/ValidatorNode.tsx
  applications/tari_validator_node_web_ui/src/utils/helpers.tsx
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
  clients/validator_node_client/src/types.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/storage/Cargo.toml
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required, P-reviews_required
