Repository tari-project/tari-ootle, pull requests merged in 2024-06, with the labels that each got.

#1044 fix(rpc)!: remove chunking
  networking/rpc_framework/src/client/mod.rs
  networking/rpc_framework/src/lib.rs
  networking/rpc_framework/src/message.rs
  networking/rpc_framework/src/server/chunking.rs
  networking/rpc_framework/src/server/mod.rs
  networking/rpc_framework/src/test/comms_integration.rs
  networking/rpc_framework/src/test/greeting_service.rs
  networking/rpc_framework/src/test/mock.rs
  networking/rpc_framework/src/test/mod.rs
  networking/rpc_framework/src/test/smoke.rs
Labels: P-acks_required

#1040 fix(template-lib)!: improve initial supply api resource builder
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/engine/src/bootstrap.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/scope.rs
  dan_layer/engine/tests/resource.rs
  dan_layer/engine/tests/shenanigans.rs
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine/tests/templates/nft/airdrop/src/lib.rs
  dan_layer/engine/tests/templates/nft/basic_nft/src/lib.rs
  dan_layer/engine/tests/templates/recall/src/lib.rs
  dan_layer/engine/tests/templates/resource/Cargo.toml
  dan_layer/engine/tests/templates/resource/src/lib.rs
  dan_layer/engine_types/src/bucket.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/constants.rs
  dan_layer/template_lib/src/models/amount.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/template_lib/src/models/vault.rs
  dan_layer/template_lib/src/prelude.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_test_tooling/templates/faucet/src/lib.rs
  integration_tests/src/templates/basic_nft/Cargo.toml
  integration_tests/src/templates/basic_nft/src/lib.rs
  integration_tests/src/templates/counter/Cargo.toml
  integration_tests/src/templates/faucet/Cargo.toml
  integration_tests/src/templates/faucet/src/lib.rs
  integration_tests/src/templates/fees/Cargo.toml
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/tariswap_test_bench/src/tariswap.rs
Labels: P-acks_required

#1043 refactor(indexer): event filtering and related substate storing
  Cargo.lock
  applications/tari_dan_app_utilities/config_presets/d_indexer.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/config.rs
  applications/tari_indexer/src/event_data.rs
  applications/tari_indexer/src/event_manager.rs
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/json_rpc/server.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer_web_ui/src/App.tsx
  applications/tari_indexer_web_ui/src/Components/MenuItems.tsx
  applications/tari_indexer_web_ui/src/main.tsx
  applications/tari_indexer_web_ui/src/routes/MonitoredNftCollections/MonitoredNftCollections.tsx
  applications/tari_indexer_web_ui/src/routes/MonitoredSubstates/MonitoredSubstates.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/MonitoredNftCollections.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/MonitoredSubstates.tsx
  applications/tari_indexer_web_ui/src/routes/VN/ValidatorNode.tsx
  applications/tari_indexer_web_ui/src/utils/json_rpc.tsx
  bindings/index.ts
  bindings/src/types/ExecutedTransaction.ts
  bindings/src/types/ResourceContainer.ts
  bindings/src/types/ShardEvidence.ts
  bindings/src/types/SubstateLockFlag.ts
  bindings/src/types/TransactionPoolRecord.ts
  bindings/src/types/tari-indexer-client/AddAddressRequest.ts
  bindings/src/types/tari-indexer-client/AddAddressResponse.ts
  bindings/src/types/tari-indexer-client/ClearAddressesResponse.ts
  bindings/src/types/tari-indexer-client/DeleteAddressRequest.ts
  bindings/src/types/tari-indexer-client/DeleteAddressResponse.ts
  bindings/src/types/tari-indexer-client/GetAddressesResponse.ts
  bindings/tari-indexer-client.ts
  bindings/validator-node-client.ts
  bindings/wallet-daemon-client.ts
  clients/tari_indexer_client/src/json_rpc_client.rs
  clients/tari_indexer_client/src/types.rs
  integration_tests/src/indexer.rs
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/steps/indexer.rs
Labels: CR-too_long, P-acks_required

#1047 fix(engine)!: uuid duplication on the same EntityId
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/engine_types/src/id_provider.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required

#1048 docs: setup instructions for tari swarm
  applications/tari_swarm_daemon/docker/README.md
Labels: P-acks_required

#1049 feat(indexer): new JRPC method to list substates
  applications/tari_indexer/src/event_manager.rs
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/json_rpc/server.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2024-06-18-095000_add_metadata_to_events_and_substates/down.sql
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2024-06-18-095000_add_metadata_to_events_and_substates/up.sql
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  applications/tari_indexer/src/substate_storage_sqlite/models/substate.rs
  applications/tari_indexer/src/substate_storage_sqlite/schema.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  bindings/src/types/tari-indexer-client/ListSubstateItem.ts
  bindings/src/types/tari-indexer-client/ListSubstatesRequest.ts
  bindings/src/types/tari-indexer-client/ListSubstatesResponse.ts
  bindings/src/types/tari-indexer-client/SubstateType.ts
  bindings/tari-indexer-client.ts
  clients/tari_indexer_client/src/types.rs
  integration_tests/src/indexer.rs
Labels: P-acks_required

#1052 fix(indexer): clippy fixes
  applications/tari_indexer/src/event_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
Labels: P-acks_required, P-reviews_required

#1057 fix(indexer): reuse validator RPC sessions
  Cargo.lock
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/validator_node_rpc/Cargo.toml
  dan_layer/validator_node_rpc/src/client.rs
  networking/rpc_framework/src/lib.rs
Labels: P-acks_required

#1055 feat(consensus): proposed block parked and ready event
  applications/tari_validator_node/src/dan_node.rs
  dan_layer/consensus/src/hotstuff/event.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/harness.rs
Labels: P-acks_required

#1060 refactor(wallet_daemon): use the indexer for substate listing
  applications/tari_dan_wallet_daemon/src/handlers/substates.rs
  applications/tari_dan_wallet_daemon/src/indexer_jrpc_impl.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  bindings/src/types/tari-indexer-client/ListSubstatesRequest.ts
  bindings/src/types/tari-indexer-client/SubstateType.ts
  bindings/src/types/wallet-daemon-client/SubstatesListRequest.ts
  bindings/tari-indexer-client.ts
  clients/tari_indexer_client/src/json_rpc_client.rs
  clients/tari_indexer_client/src/types.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/common_types/src/substate_type.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
  dan_layer/wallet/sdk/src/models/substate.rs
  dan_layer/wallet/sdk/src/network.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: P-acks_required

#1059 feat(swarm): json-rpc call to delete instance data
  applications/tari_swarm_daemon/src/process_definitions/definition.rs
  applications/tari_swarm_daemon/src/process_definitions/indexer.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_node.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_wallet.rs
  applications/tari_swarm_daemon/src/process_definitions/validator_node.rs
  applications/tari_swarm_daemon/src/process_definitions/wallet_daemon.rs
  applications/tari_swarm_daemon/src/process_manager/handle.rs
  applications/tari_swarm_daemon/src/process_manager/instances/manager.rs
  applications/tari_swarm_daemon/src/process_manager/manager.rs
  applications/tari_swarm_daemon/src/webserver/rpc/instances.rs
  applications/tari_swarm_daemon/src/webserver/server.rs
  applications/tari_swarm_daemon/webui/src/routes/Main.tsx
Labels: P-acks_required, P-reviews_required

#1051 feat(swarm): list all running instances (ports etc)
  applications/tari_swarm_daemon/src/process_manager/port_allocator.rs
  applications/tari_swarm_daemon/src/webserver/rpc/instances.rs
  applications/tari_swarm_daemon/src/webserver/server.rs
  applications/tari_swarm_daemon/webui/src/routes/Main.tsx
Labels: P-acks_required

#1046 fix(engine)!: allow multiple create components in one call
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/address_allocation/src/lib.rs
  dan_layer/engine/tests/templates/state/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/component.rs
  dan_layer/engine_types/src/id_provider.rs
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/caller_context.rs
  dan_layer/template_lib/src/component/instance.rs
  dan_layer/template_test_tooling/src/read_only_state_store.rs
  dan_layer/wallet/sdk/src/apis/confidential_transfer.rs
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/transaction_generator/src/transaction_builders/free_coins.rs
Labels: P-acks_required

#1062 fix(consensus): various consensus fixes from tariswap testing
  .github/workflows/ci.yml
  .prettierrc.mjs
  Cargo.lock
  applications/tari_dan_wallet_daemon/src/handlers/validator.rs
  applications/tari_dan_wallet_web_ui/.prettierrc.js
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
  applications/tari_dan_wallet_web_ui/src/Components/Accordion.tsx
  applications/tari_dan_wallet_web_ui/src/Components/ConnectorLink/Permissions.tsx
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/Components/StyledComponents.ts
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/SettingsTabs.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/FeeInstructions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_dan_wallet_web_ui/src/utils/cbor.ts
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_dan_wallet_web_ui/tsconfig.json
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/state_machine/running.rs
  dan_layer/consensus/src/hotstuff/substate_store/error.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/transaction/src/transaction.rs
  integration_tests/tests/features/claim_fees.feature
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/tariswap_test_bench/src/main.rs
  utilities/tariswap_test_bench/src/runner.rs
  utilities/tariswap_test_bench/src/tariswap.rs
  utilities/transaction_generator/Cargo.toml
  utilities/transaction_generator/src/transaction_reader.rs
  utilities/transaction_generator/src/transaction_writer.rs
  utilities/transaction_submitter/src/main.rs
Labels: CR-too_long, P-acks_required
