Repository tari-project/tari-ootle, pull requests merged in 2024-12, with the labels that each got.

#1209 fix(consensus): correctly handle conflicting outputs for transaction
  dan_layer/consensus/src/hotstuff/substate_store/error.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
Labels: P-reviews_required

#1208 feat: new PublishTemplate instruction
  Cargo.lock
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_indexer/src/dry_run/processor.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_validator_node/src/bootstrap.rs
  bindings/dist/index.d.ts
  bindings/dist/index.js
  bindings/dist/tari-indexer-client.d.ts
  bindings/dist/tari-indexer-client.js
  bindings/dist/types/Instruction.d.ts
  bindings/dist/types/PublishedTemplate.d.ts
  bindings/dist/types/PublishedTemplate.js
  bindings/dist/types/PublishedTemplateAddress.d.ts
  bindings/dist/types/PublishedTemplateAddress.js
  bindings/dist/types/wallet-daemon-client/TransactionSubmitRequest.d.ts
  bindings/dist/validator-node-client.d.ts
  bindings/dist/validator-node-client.js
  bindings/dist/wallet-daemon-client.d.ts
  bindings/dist/wallet-daemon-client.js
  bindings/src/index.ts
  bindings/src/tari-indexer-client.ts
  bindings/src/types/Instruction.ts
  bindings/src/types/wallet-daemon-client/TransactionSubmitRequest.ts
  bindings/src/validator-node-client.ts
  bindings/src/wallet-daemon-client.ts
  dan_layer/consensus/src/consensus_constants.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/engine/src/transaction/error.rs
  dan_layer/engine/src/transaction/mod.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine_types/src/instruction.rs
  dan_layer/p2p/proto/transaction.proto
  dan_layer/p2p/src/conversions/transaction.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/transaction/src/builder.rs
Labels: P-acks_required

#1216 feat(state-tree)!: implement verify for Merkle in/exclusion proofs
  applications/tari_swarm_daemon/src/main.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/state_tree/src/bit_iter.rs
  dan_layer/state_tree/src/jellyfish/error.rs
  dan_layer/state_tree/src/jellyfish/mod.rs
  dan_layer/state_tree/src/jellyfish/tree.rs
  dan_layer/state_tree/src/jellyfish/types.rs
  dan_layer/state_tree/src/key_mapper.rs
  dan_layer/state_tree/src/lib.rs
  dan_layer/state_tree/src/tree.rs
  dan_layer/state_tree/tests/support.rs
  dan_layer/state_tree/tests/test.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/consensus_models/substate_change.rs
  integration_tests/tests/features/eviction.feature
Labels: P-acks_required, P-reviews_required

#1220 feat!: adds inclusion proof to eviction proof
  Cargo.lock
  Cargo.toml
  dan_layer/common_types/src/versioned_substate_id.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/eviction_proof.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/substate_store/sharded_state_tree.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/Cargo.toml
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/confidential/elgamal.rs
  dan_layer/engine_types/src/fee_claim.rs
  dan_layer/engine_types/src/instruction.rs
  dan_layer/engine_types/src/serde_with/hex.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/engine_types/src/transaction_receipt.rs
  dan_layer/p2p/Cargo.toml
  dan_layer/p2p/src/conversions/rpc.rs
  dan_layer/rpc_state_sync/src/error.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/state_tree/Cargo.toml
  dan_layer/state_tree/src/bit_iter.rs
  dan_layer/state_tree/src/error.rs
  dan_layer/state_tree/src/jellyfish/error.rs
  dan_layer/state_tree/src/jellyfish/hash.rs
  dan_layer/state_tree/src/jellyfish/mod.rs
  dan_layer/state_tree/src/jellyfish/store.rs
  dan_layer/state_tree/src/jellyfish/tree.rs
  dan_layer/state_tree/src/jellyfish/types.rs
  dan_layer/state_tree/src/key_mapper.rs
  dan_layer/state_tree/src/lib.rs
  dan_layer/state_tree/src/memory_store.rs
  dan_layer/state_tree/src/staged_store.rs
  dan_layer/state_tree/src/tree.rs
  dan_layer/state_tree/tests/support.rs
  dan_layer/state_tree/tests/test.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/block_header.rs
  dan_layer/storage/src/consensus_models/epoch_checkpoint.rs
  dan_layer/template_abi/src/types.rs
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_lib/src/models/component.rs
  dan_layer/template_lib/src/models/entity_id.rs
  dan_layer/template_lib/src/models/layer_one_commitment.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/template_lib/src/models/non_fungible_index.rs
  dan_layer/template_lib/src/models/resource.rs
  dan_layer/template_lib/src/models/vault.rs
  integration_tests/tests/features/eviction.feature
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1221 fix: missing types
  dan_layer/engine_types/src/published_template.rs
  dan_layer/template_lib/src/panic_hook.rs
Labels: P-acks_required

#1223 fix(transactions)!: adds versioned transaction schema
  applications/tari_dan_app_utilities/src/template_manager/implementation/cmap_semaphore.rs
  applications/tari_dan_wallet_cli/src/table.rs
  applications/tari_dan_wallet_daemon/build.rs
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimBurn.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimFees.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SelectAccount.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/ViewVaultBalance.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  applications/tari_swarm_daemon/src/process_manager/executables/manager.rs
  applications/tari_validator_node_cli/src/table.rs
  applications/tari_validator_node_web_ui/src/routes/Transactions/TransactionDetails.tsx
  bindings/dist/index.d.ts
  bindings/dist/index.js
  bindings/dist/types/Transaction.d.ts
  bindings/dist/types/TransactionV1.d.ts
  bindings/dist/types/TransactionV1.js
  bindings/package-lock.json
  bindings/package.json
  bindings/src/index.ts
  bindings/src/types/Transaction.ts
  bindings/src/types/TransactionV1.ts
  clients/javascript/wallet_daemon_client/package.json
  clients/javascript/wallet_daemon_client/tsconfig.json
  dan_layer/common_types/src/committee.rs
  dan_layer/consensus/src/hotstuff/substate_store/shard_state_store.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_tree/src/staged_store.rs
  dan_layer/state_tree/src/tree.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/lock_intent.rs
  dan_layer/tari_bor/src/json_encoding.rs
  dan_layer/template_lib/src/panic_hook.rs
  dan_layer/transaction/src/lib.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/transaction/src/v1.rs
  dan_layer/wallet/crypto/src/value_lookup/io_reader_value_lookup.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required, P-reviews_required

#1224 chore: update package.locks
  bindings/package-lock.json
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1225 fix: correct path for wallet client
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
Labels: CR-insufficient_context

#1226 fix(template): add full typename to invalid argument error
  dan_layer/engine/tests/test.rs
  dan_layer/template_abi/src/rust.rs
  dan_layer/template_lib/src/template_dependencies.rs
  dan_layer/template_macros/src/template/dispatcher.rs
Labels: P-acks_required, P-reviews_required
