Repository tari-project/tari-ootle, pull requests merged in 2024-03, with the labels that each got.

#956 fix(walletd): emit AccountChanged event on changes for account refresh
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  dan_layer/consensus_tests/src/consensus.rs
  integration_tests/tests/log4rs/cucumber.yml
Labels: P-acks_required

#959 ci: add tari generate to built binaries
  .github/workflows/build_binaries.yml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#960 fix(engine): claiming burns/fees call frame error
  applications/tari_dan_wallet_cli/src/command/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/component.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/cucumber.rs
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/transaction_generator/src/transaction_builders/free_coins.rs
Labels: P-acks_required

#963 feat: change bindings package usage to git instead of local
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: P-acks_required

#966 fix!: always account for version when querying substates
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/helpers.rs
  dan_layer/common_types/src/substate_address.rs
  dan_layer/engine_types/src/hashing.rs
  integration_tests/tests/features/claim_burn.feature
Labels: P-acks_required, P-reviews_required

#964 feat(jrpc): parse json object args as CBOR
  dan_layer/engine_types/src/argument_parser.rs
Labels: P-acks_required

#939 refactor(tx-builder): allow building unsigned transactions
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/signature.rs
  bindings/src/types/UnsignedTransaction.ts
  bindings/src/types/wallet-daemon-client/TransactionSubmitRequest.ts
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/transaction/src/builder.rs
  dan_layer/transaction/src/lib.rs
  dan_layer/transaction/src/signature.rs
  dan_layer/transaction/src/unsigned_transaction.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required, P-reviews_required

#962 fix(vn/webui): fix template table
  applications/tari_dan_app_utilities/src/template_manager/implementation/service.rs
  applications/tari_validator_node_web_ui/src/routes/VN/Components/TemplateFunctions.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Templates.tsx
  bindings/src/types/validator-node-client/GetTemplateRequest.ts
  bindings/src/types/validator-node-client/TemplateAbi.ts
  bindings/src/types/validator-node-client/TemplateMetadata.ts
  clients/validator_node_client/src/types.rs
Labels: P-acks_required, P-reviews_required

#957 refactor(engine)!: store NFT data as CBOR value
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/nfts.rs
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer/src/json_rpc/json_encoding.rs
  bindings/index.ts
  bindings/src/types/NonFungible.ts
  bindings/src/types/NonFungibleToken.ts
  bindings/src/types/wallet-daemon-client/AccountNftInfo.ts
  bindings/src/types/wallet-daemon-client/ListAccountNftResponse.ts
  bindings/wallet-daemon-client.ts
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/templates/access_rules/Cargo.toml
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/nft/airdrop/src/lib.rs
  dan_layer/engine/tests/templates/recall/src/lib.rs
  dan_layer/engine_types/src/non_fungible.rs
  dan_layer/indexer_lib/src/substate_decoder.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/apis/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/Cargo.toml
  dan_layer/wallet/storage_sqlite/migrations/2023-06-02-156480_add_nft_table/up.sql
  dan_layer/wallet/storage_sqlite/src/models/non_fungible_tokens.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  dan_layer/wallet/storage_sqlite/tests/substates.rs
Labels: P-acks_required, P-reviews_required

#955 fix(wallet): preserve parent when recording substate addresses
  dan_layer/wallet/sdk/src/apis/transaction.rs
Labels: P-acks_required, P-reviews_required

#942 fix(consensus)!: add exhaust burn per transaction, fix block fee malleability
  applications/tari_validator_node_web_ui/src/routes/Blocks/BlockDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Blocks.tsx
  bindings/index.ts
  bindings/src/types/Block.ts
  bindings/src/types/LeaderFee.ts
  bindings/src/types/TransactionAtom.ts
  clients/validator_node_client/src/types.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction_pool.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  integration_tests/tests/features/claim_fees.feature
Labels: P-acks_required

#973 chore: update TypeScript bindings
  bindings/index.ts
  bindings/src/helpers/helpers.ts
  bindings/src/types/Block.ts
  bindings/src/types/UnsignedTransaction.ts
  bindings/src/types/tari-indexer-client/GetEpochManagerStatsResponse.ts
  bindings/src/types/validator-node-client/GetEpochManagerStatsResponse.ts
  bindings/tari-indexer-client.ts
  bindings/tsconfig.json
  bindings/validator-node-client.ts
  bindings/wallet-daemon-client.ts
Labels: P-acks_required

#974 chore(integration_test): show more info about wallet daemons
  integration_tests/tests/cucumber.rs
Labels: P-acks_required

#975 feat(engine): builtin vault events for deposits and withdrawals
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/events.rs
  dan_layer/engine/tests/templates/events/src/lib.rs
Labels: P-acks_required

#980 fix(integration_test): broken indexer event test
  integration_tests/tests/features/indexer.feature
Labels: P-acks_required

#971 fix: broken webui builds and abort compilation when this happens
  applications/tari_dan_wallet_daemon/build.rs
  applications/tari_indexer/build.rs
  applications/tari_indexer_web_ui/package-lock.json
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/build.rs
  applications/tari_validator_node_web_ui/src/routes/Blocks/BlockDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/Transactions.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Blocks.tsx
  bindings/src/types/Block.ts
  dan_layer/storage/src/consensus_models/block.rs
Labels: CR-too_long, P-acks_required, CR-one_job

#945 feat!: block pagination and header timestamp
  Cargo.lock
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node_web_ui/src/Components/Filter.tsx
  applications/tari_validator_node_web_ui/src/Components/HeadingMenu.tsx
  applications/tari_validator_node_web_ui/src/routes/VN/Components/Blocks.tsx
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
  bindings/src/types/Block.ts
  bindings/src/types/validator-node-client/GetBlocksRequest.ts
  bindings/src/types/validator-node-client/GetFilteredBlocksCountRequest.ts
  bindings/validator-node-client.ts
  clients/validator_node_client/src/types.rs
  dan_layer/consensus/Cargo.toml
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required

#953 fix: nft dan wallet ui
  applications/tari_dan_wallet_cli/src/command/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/MyAssets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/FeeInstructions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Instructions.tsx
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer_web_ui/package-lock.json
  applications/tari_validator_node_web_ui/package-lock.json
  bindings/src/types/wallet-daemon-client/ListAccountNftRequest.ts
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
Labels: CR-too_long, P-acks_required

#977 feat(wallet): add support for value brute forcing using secret view key
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  applications/tari_dan_wallet_daemon/src/handlers/context.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/ViewVaultBalance.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Settings.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_dan_wallet_web_ui/tsconfig.json
  applications/tari_validator_node_cli/src/command/transaction.rs
  bindings/index.ts
  bindings/src/types/wallet-daemon-client/ConfidentialViewVaultBalanceRequest.ts
  bindings/src/types/wallet-daemon-client/ConfidentialViewVaultBalanceResponse.ts
  bindings/tari-indexer-client.ts
  bindings/tsconfig.json
  bindings/validator-node-client.ts
  bindings/wallet-daemon-client.ts
  clients/javascript/wallet_daemon_client/src/index.ts
  clients/javascript/wallet_daemon_client/tsconfig.json
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine_types/src/argument_parser.rs
  dan_layer/engine_types/src/confidential/elgamal.rs
  dan_layer/engine_types/src/template.rs
  dan_layer/engine_types/src/vault.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_test_tooling/src/support/mod.rs
  dan_layer/wallet/crypto/src/lib.rs
  dan_layer/wallet/crypto/src/value_lookup/header.rs
  dan_layer/wallet/crypto/src/value_lookup/io_reader_value_lookup.rs
  dan_layer/wallet/crypto/src/value_lookup/mod.rs
  dan_layer/wallet/crypto/tests/viewable_balance_proof.rs
  dan_layer/wallet/sdk/src/apis/confidential_crypto.rs
  dan_layer/wallet/sdk/src/apis/key_manager.rs
Labels: CR-too_long, P-acks_required, P-reviews_required

#981 fix(wallet): improve NFT data JSON output
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_web_ui/src/Components/ConnectorLink/Permissions.tsx
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  applications/tari_dan_wallet_web_ui/src/utils/cbor.ts
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  bindings/build.sh
  bindings/index.ts
  dan_layer/tari_bor/src/json_encoding.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/wallet/sdk/src/apis/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/src/models/non_fungible_tokens.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required, P-reviews_required

#985 feat(indexer): new GraphQL query to get events by payload
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2024-03-19-114926_refactor_event_payloads/down.sql
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2024-03-19-114926_refactor_event_payloads/up.sql
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  applications/tari_indexer/src/substate_storage_sqlite/schema.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/steps/indexer.rs
Labels: P-acks_required

#978 fix(wallet): resubmit transactions on failure
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_app_utilities/src/json_encoding.rs
  applications/tari_dan_app_utilities/src/lib.rs
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/context.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/validator.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_daemon/src/services/events.rs
  applications/tari_dan_wallet_daemon/src/services/mod.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service/error.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service/handle.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service/mod.rs
  applications/tari_dan_wallet_daemon/src/services/transaction_service/service.rs
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/json_rpc/mod.rs
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  bindings/src/types/ExecuteResult.ts
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/consensus_tests/src/support/transaction_executor.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/tests/fees.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/account.rs
  dan_layer/wallet/sdk/src/models/mod.rs
  dan_layer/wallet/sdk/src/models/wallet_transaction.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2024-03-18-054147_add_required_substates_to_transactions/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2024-03-18-054147_add_required_substates_to_transactions/up.sql
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  dan_layer/wallet/storage_sqlite/tests/transaction.rs
  utilities/tariswap_test_bench/src/runner.rs
Labels: P-acks_required, P-reviews_required

#983 feat(wallet)!: conf transfers with input selection and badge support
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  bindings/index.ts
  bindings/src/types/ConfidentialTransferInputSelection.ts
  bindings/src/types/wallet-daemon-client/ConfidentialTransferRequest.ts
  clients/wallet_daemon_client/src/types.rs
  dan_layer/engine_types/src/argument_parser.rs
  dan_layer/template_lib/src/models/amount.rs
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/apis/accounts.rs
  dan_layer/wallet/sdk/src/apis/confidential_outputs.rs
  dan_layer/wallet/sdk/src/apis/confidential_transfer.rs
  dan_layer/wallet/sdk/src/apis/mod.rs
  dan_layer/wallet/sdk/src/models/vault.rs
  dan_layer/wallet/sdk/src/sdk.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-02-08-122514_initial/up.sql
  dan_layer/wallet/storage_sqlite/src/models/vault.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  integration_tests/Cargo.toml
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required, P-reviews_required

#986 feat: store substate_id in events
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Events.tsx
  applications/tari_indexer/src/graphql/model/events.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2024-03-21-212928_refactor_event_substate/down.sql
  applications/tari_indexer/src/substate_storage_sqlite/migrations/2024-03-21-212928_refactor_event_substate/up.sql
  applications/tari_indexer/src/substate_storage_sqlite/models/events.rs
  applications/tari_indexer/src/substate_storage_sqlite/schema.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  applications/tari_signaling_server/src/jrpc_server.rs
  applications/tari_validator_node_web_ui/src/routes/Transactions/Events.tsx
  bindings/index.ts
  bindings/src/types/Event.ts
  bindings/tari-indexer-client.ts
  bindings/tsconfig.json
  bindings/validator-node-client.ts
  bindings/wallet-daemon-client.ts
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/tests/events.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  integration_tests/src/indexer.rs
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/steps/indexer.rs
Labels: P-acks_required, P-reviews_required

#992 feat(template_lib): adds log macros
  dan_layer/template_lib/src/macros.rs
  dan_layer/template_lib/src/prelude.rs
Labels: P-acks_required, P-reviews_required

#991 fix(wallet/webui): fix events on transactions page
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Events.tsx
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/BlockDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/Events.tsx
  applications/tari_validator_node_web_ui/src/utils/helpers.tsx
  bindings/index.ts
  bindings/src/types/Event.ts
  bindings/tari-indexer-client.ts
  bindings/tsconfig.json
  bindings/validator-node-client.ts
  bindings/wallet-daemon-client.ts
  dan_layer/engine_types/src/events.rs
Labels: P-acks_required, P-reviews_required
