Repository tari-project/tari-ootle, pull requests merged in 2024-10, with the labels that each got.

#1165 fix: fixing integration tests
  Cargo.lock
  dan_layer/state_store_sqlite/src/store.rs
  integration_tests/Cargo.toml
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/claim_burn.feature
  integration_tests/tests/features/committee.feature
  integration_tests/tests/features/concurrency.feature
  integration_tests/tests/features/counter.feature
  integration_tests/tests/features/epoch_change.feature
  integration_tests/tests/features/epoch_change.feature.ignore
  integration_tests/tests/features/fungible.feature
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/features/nft.feature
  integration_tests/tests/features/state_sync.feature
  integration_tests/tests/features/substates.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
Labels: P-acks_required, P-reviews_required

#1166 chore: moved fee exhaust constant to consensus constants
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_dan_app_utilities/src/lib.rs
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/lib.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/consensus_constants.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/config.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/lib.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
Labels: P-acks_required

#1167 fix: syncing from epoch 0 before consensus has started
  applications/tari_swarm_daemon/src/config.rs
  applications/tari_swarm_daemon/src/process_manager/manager.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  dan_layer/rpc_state_sync/src/manager.rs
Labels: P-reviews_required

#1175 fix(wallet_web_ui): invalid resource error on transfers
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
Labels: P-acks_required, P-reviews_required

#1174 feat(swarm): auto mining
  applications/tari_swarm_daemon/src/webserver/context.rs
  applications/tari_swarm_daemon/src/webserver/rpc/miners.rs
  applications/tari_swarm_daemon/src/webserver/server.rs
  applications/tari_swarm_daemon/webui/src/routes/Main.tsx
Labels: P-acks_required, P-reviews_required

#1176 feat(template_lib)!: new access rules macro
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine/tests/templates/nft/basic_nft/src/lib.rs
  dan_layer/engine/tests/templates/nft/emoji_id/src/lib.rs
  dan_layer/engine/tests/templates/nft/nft_list/src/lib.rs
  dan_layer/engine/tests/templates/nft/tickets/src/lib.rs
  dan_layer/engine/tests/templates/recall/src/lib.rs
  dan_layer/engine/tests/templates/resource/src/lib.rs
  dan_layer/engine/tests/templates/resource_shenanigans/src/lib.rs
  dan_layer/engine/tests/templates/shenanigans/src/lib.rs
  dan_layer/engine/tests/templates/state/src/lib.rs
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_builtin/templates/account_nfts/src/lib.rs
  dan_layer/template_lib/src/auth/access_rules.rs
  dan_layer/template_lib/src/prelude.rs
  integration_tests/src/templates/basic_nft/src/lib.rs
Labels: P-acks_required, P-reviews_required

#1182 feat(validators): trickle in validators
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/consensus/src/consensus_constants.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/epoch_manager/src/base_layer/base_layer_epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/config.rs
  dan_layer/storage/src/global/backend_adapter.rs
  dan_layer/storage/src/global/validator_node_db.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
Labels: P-acks_required, P-reviews_required

#1185 feat(swarm): register templates on startup automatically if not already registered
  applications/tari_swarm_daemon/src/cli.rs
  applications/tari_swarm_daemon/src/config.rs
  applications/tari_swarm_daemon/src/main.rs
  applications/tari_swarm_daemon/src/process_manager/handle.rs
  applications/tari_swarm_daemon/src/process_manager/manager.rs
Labels: P-acks_required, P-reviews_required

#1186 fix: increase gossip message size limit to 128k
  networking/swarm/src/behaviour.rs
  networking/swarm/src/config.rs
Labels: P-acks_required, P-reviews_required
