Repository tari-project/tari-ootle, pull requests merged in 2024-07, with the labels that each got.

#1069 chore!: renaming and hasher documentation
  applications/tari_validator_node/src/consensus/signature_service.rs
  dan_layer/common_types/src/hasher.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/traits/signing_service.rs
Labels: P-acks_required, P-reviews_required

#1068 ci(fix): osx x86 build
  .cargo/config.toml
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
  .github/workflows/ci.yml
  .license.ignore
  CODEOWNERS
  Cross.toml
  scripts/cross_compile_ubuntu_18-pre-build.sh
  scripts/file_license_check.sh
Labels: P-acks_required

#1072 feat(swarm): allow custom listen IP configuration
  applications/tari_swarm_daemon/src/config.rs
  applications/tari_swarm_daemon/src/logger.rs
  applications/tari_swarm_daemon/src/main.rs
  applications/tari_swarm_daemon/src/process_definitions/context.rs
  applications/tari_swarm_daemon/src/process_definitions/indexer.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_miner.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_node.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_wallet.rs
  applications/tari_swarm_daemon/src/process_definitions/signaling_server.rs
  applications/tari_swarm_daemon/src/process_definitions/validator_node.rs
  applications/tari_swarm_daemon/src/process_definitions/wallet_daemon.rs
  applications/tari_swarm_daemon/src/process_manager/instances/instance.rs
  applications/tari_swarm_daemon/src/process_manager/instances/manager.rs
Labels: P-acks_required, P-reviews_required

#1073 chore: add github workflow for npm publish
  .github/workflows/npm_publish.yml
Labels: P-acks_required, P-reviews_required

#1086 chore!: update to use latest feature-dan2
  Cargo.lock
  Cargo.toml
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/confidential/withdraw.rs
  dan_layer/template_lib/src/crypto/balance_proof.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_test_tooling/src/support/confidential.rs
  dan_layer/wallet/crypto/Cargo.toml
  dan_layer/wallet/crypto/src/api.rs
  dan_layer/wallet/crypto/src/confidential_statement.rs
  dan_layer/wallet/crypto/src/kdfs.rs
  dan_layer/wallet/crypto/src/proof.rs
  dan_layer/wallet/crypto/tests/output_statement.rs
  dan_layer/wallet/crypto/tests/viewable_balance_proof.rs
  dan_layer/wallet/sdk/src/apis/confidential_crypto.rs
  dan_layer/wallet/sdk/src/apis/confidential_transfer.rs
  integration_tests/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/tests/steps/wallet.rs
  scripts/install_ubuntu_dependencies.sh
Labels: CR-too_long, P-acks_required

#1089 ci(feature): add for unsigned commits
  .github/workflows/pr_signed_commits_check.yml
Labels: P-acks_required

#1093 fix(wallet_jrpc_client): empty npm package when publishing
  .github/workflows/npm_publish.yml
  applications/tari_dan_wallet_web_ui/package-lock.json
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: P-acks_required, P-reviews_required

#1096 fix(ci): remove build step when publishing typescript-bindings
  .github/workflows/npm_publish.yml
Labels: P-acks_required

#1094 fix(docs): tari_template_lib resource builders not showing on rust docs
  dan_layer/template_lib/src/resource/builder/mod.rs
Labels: P-acks_required, P-reviews_required

#1097 feat(consensus): optionally configure max block time
  applications/tari_dan_app_utilities/src/consensus_constants.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  dan_layer/consensus/src/hotstuff/config.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/pacemaker.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/engine/src/runtime/working_state.rs
Labels: P-acks_required, P-reviews_required
