Repository tari-project/tari-ootle, pull requests merged in 2024-01, with the labels that each got.

#862 fix: clippies on latest stable rust 1.75
  applications/tari_dan_wallet_cli/src/command/account.rs
  dan_layer/consensus_tests/src/support/mod.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/state_store_sqlite/src/sql_models/locked_output.rs
  dan_layer/state_store_sqlite/src/sql_models/mod.rs
  dan_layer/tari_bor/src/json_encoding.rs
  integration_tests/tests/steps/wallet_daemon.rs
  utilities/transaction_generator/src/transaction_reader.rs
Labels: P-acks_required, P-reviews_required

#854 chore(engine): remove unused NFT marketplace POC template
  dan_layer/engine/tests/templates/nft/marketplace/Cargo.toml
  dan_layer/engine/tests/templates/nft/marketplace/src/lib.rs
Labels: P-acks_required

#855 feat(template_lib): add from_str for NFT addresses
  dan_layer/engine_types/src/substate.rs
  dan_layer/template_lib/src/models/non_fungible.rs
Labels: P-acks_required

#858 feat: sign proposal
  applications/tari_validator_node/src/consensus/spec.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/vote_receiver.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus_tests/src/support/signing_service.rs
  dan_layer/consensus_tests/src/support/spec.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/validator_node_rpc/proto/consensus.proto
  dan_layer/validator_node_rpc/src/conversions/common.rs
  dan_layer/validator_node_rpc/src/conversions/consensus.rs
Labels: P-acks_required

#848 fix: claim burn to create account
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/account.rs
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  clients/wallet_daemon_client/src/types.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#865 fix: gossip
  applications/tari_validator_node/src/p2p/services/mempool/gossip.rs
  networking/swarm/src/behaviour.rs
Labels: P-acks_required

#866 test: break infinity loop in template
  dan_layer/engine/src/wasm/metering.rs
  dan_layer/engine/tests/templates/infinity_loop/Cargo.toml
  dan_layer/engine/tests/templates/infinity_loop/src/lib.rs
  dan_layer/engine/tests/test.rs
Labels: P-acks_required

#867 fix: block signature saving
  dan_layer/state_store_sqlite/src/writer.rs
Labels: P-acks_required

#839 feat: reduce messages sent when broadcasting to foreign committee
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/network.rs
Labels: P-acks_required

#873 test(engine): fix infinite loop test
  Cargo.lock
  dan_layer/engine/tests/test.rs
Labels: P-acks_required, P-reviews_required

#863 fix(template-lib): minor cross-template call api improvement
  dan_layer/template_lib/src/component/manager.rs
  dan_layer/template_lib/src/template/manager.rs
Labels: P-acks_required

#861 fix(engine): remove unnecessary allocations from GetNonFungibleIds
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/template_builtin/templates/account/src/lib.rs
Labels: P-acks_required

#868 feat(template): allow resource actions to be restricted by component
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/runtime/tracker_auth.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/address_allocation.rs
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/address_allocation/Cargo.toml
  dan_layer/engine/tests/templates/address_allocation/src/lib.rs
  dan_layer/engine_types/src/lib.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/auth/access_rules.rs
  dan_layer/template_lib/src/caller_context.rs
  dan_layer/template_lib/src/component/instance.rs
  dan_layer/template_lib/src/component/manager.rs
  dan_layer/template_lib/src/engine.rs
  dan_layer/template_lib/src/models/address_allocation.rs
  dan_layer/template_lib/src/models/mod.rs
  dan_layer/template_lib/src/prelude.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/template_macros/src/template/dispatcher.rs
Labels: P-acks_required

#876 fix: account parser in claim fee request
  clients/wallet_daemon_client/src/types.rs
Labels: P-acks_required

#879 feat: show keys in claim burn
  applications/tari_dan_wallet_web_ui/src/api/hooks/useKeys.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimBurn.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
Labels: P-acks_required

#857 feat: validate qc
  Cargo.lock
  dan_layer/common_types/Cargo.toml
  dan_layer/common_types/src/validator_metadata.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/vote_receiver.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/handle.rs
  dan_layer/epoch_manager/src/traits.rs
Labels: P-acks_required

#878 fix(walletd): correctly set indexer url via JRPC
  applications/tari_dan_wallet_daemon/src/handlers/settings.rs
  applications/tari_dan_wallet_daemon/src/indexer_jrpc_impl.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  dan_layer/wallet/sdk/src/network.rs
  dan_layer/wallet/sdk/src/sdk.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: P-acks_required

#872 refactor: move dan configs into this repo
  Cargo.lock
  Cargo.toml
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_app_utilities/config_presets/a_common.toml
  applications/tari_dan_app_utilities/config_presets/b_peer_seeds.toml
  applications/tari_dan_app_utilities/config_presets/c_validator_node.toml
  applications/tari_dan_app_utilities/config_presets/d_indexer.toml
  applications/tari_dan_app_utilities/config_presets/e_dan_wallet_daemon.toml
  applications/tari_dan_app_utilities/src/configuration.rs
  applications/tari_dan_app_utilities/src/lib.rs
  applications/tari_dan_app_utilities/src/p2p_config.rs
  applications/tari_dan_wallet_daemon/Cargo.toml
  applications/tari_dan_wallet_daemon/src/main.rs
  applications/tari_indexer/src/cli.rs
  applications/tari_indexer/src/config.rs
  applications/tari_indexer/src/main.rs
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/main.rs
  integration_tests/src/indexer.rs
  integration_tests/src/validator_node.rs
Labels: P-acks_required

#874 chore(ci): enable machete check
  .github/workflows/ci.yml
Labels: P-acks_required, P-reviews_required

#864 fix!: use configured network string in networking protocol
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/src/bootstrap.rs
  networking/core/src/lib.rs
  networking/core/src/worker.rs
  networking/swarm/src/config.rs
  networking/swarm/src/error.rs
  networking/swarm/src/lib.rs
  networking/swarm/src/network.rs
  networking/swarm/src/protocol_version.rs
Labels: P-acks_required

#889 feat: add foreign proposal validation
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
Labels: P-acks_required

#885 feat: don't add substates that are already being processed
  dan_layer/state_store_sqlite/src/reader.rs
Labels: P-acks_required

#897 feat(template_lib): improve API for extracting data from NFTs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/tests/templates/nft/basic_nft/src/lib.rs
  dan_layer/engine/tests/test.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/vault.rs
Labels: P-acks_required

#896 fix: qc was validated based on current epoch, not the qc's epoch
  dan_layer/consensus/src/block_validations.rs
Labels: P-acks_required

#892 refactor(consensus): clean up inbound message processing
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/worker.rs
Labels: P-acks_required

#898 fix: add base node proto to fix compile error
  Cargo.toml
  dan_layer/common_types/Cargo.toml
  integration_tests/Cargo.toml
Labels: P-acks_required

#894 fix(consensus)!: allow multiple read-only shard references in proposals
  Cargo.lock
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  dan_layer/engine_types/src/lock.rs
  dan_layer/state_store_sqlite/Cargo.toml
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/storage/Cargo.toml
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/transaction_decision.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
Labels: P-acks_required

#886 fix(consensus): dont send dummy blocks on sync
  Cargo.lock
  Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/spec.rs
  applications/tari_validator_node/src/p2p/rpc/sync_task.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_sync_request.rs
  dan_layer/consensus/src/hotstuff/on_sync_response.rs
  dan_layer/consensus/src/hotstuff/pacemaker_handle.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/rpc_state_sync/Cargo.toml
  dan_layer/rpc_state_sync/src/error.rs
  dan_layer/rpc_state_sync/src/lib.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required

#905 fix: uncomment sync cucumber test
  integration_tests/tests/features/block_sync.feature
Labels: P-acks_required

#907 fix: ui
  applications/tari_validator_node_web_ui/src/routes/Committees/Committees.tsx
  applications/tari_validator_node_web_ui/src/routes/Committees/CommitteesPieChart.tsx
  applications/tari_validator_node_web_ui/src/routes/Committees/CommitteesRadial.tsx
  applications/tari_validator_node_web_ui/src/routes/Committees/CommitteesWaterfall.tsx
  applications/tari_validator_node_web_ui/src/utils/interfaces.tsx
Labels: P-acks_required

#909 feat: remove serde-byte-array
  Cargo.lock
  Cargo.toml
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_lib/src/crypto/balance_proof.rs
  dan_layer/template_lib/src/crypto/commitment.rs
  dan_layer/template_lib/src/crypto/ristretto.rs
  dan_layer/template_lib/src/hash.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_lib/src/models/non_fungible.rs
Labels: P-acks_required

#912 fix: remove unused `hotstuff_rounds` consensus constant
  applications/tari_dan_app_utilities/src/consensus_constants.rs
Labels: P-acks_required

#911 fix(consensus): minor foreign counters fixes
  Cargo.lock
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  dan_layer/consensus/Cargo.toml
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/migrations/2024-01-22-123711_rename_mined_at_to_proposed_at/down.sql
  dan_layer/state_store_sqlite/migrations/2024-01-22-123711_rename_mined_at_to_proposed_at/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/bookkeeping.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/foreign_proposal.rs
  dan_layer/storage/src/consensus_models/foreign_receive_counters.rs
  dan_layer/storage/src/consensus_models/foreign_send_counters.rs
Labels: P-acks_required

#895 feat: claim fees ui
  applications/tari_dan_wallet_cli/src/command/validator.rs
  applications/tari_dan_wallet_daemon/src/handlers/validator.rs
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ActionMenu.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimFees.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  applications/tari_indexer/src/dry_run/error.rs
  applications/tari_indexer/src/dry_run/processor.rs
  clients/wallet_daemon_client/src/types.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/steps/wallet_daemon.rs
Labels: P-acks_required

#840 refactor: rename jrpc cli names
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/lib.rs
  integration_tests/src/validator_node.rs
Labels: CR-insufficient_context, P-acks_required

#916 fix(consensus): improve block fullness when tx rate is high
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/after/outputs_dont_exist_locally.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/pacemaker.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  networking/core/src/worker.rs
Labels: P-acks_required

#891 feat!: add transaction execute and finalized time to vn+indexer+wallet
  applications/tari_dan_wallet_daemon/src/indexer_jrpc_impl.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/transaction_manager/error.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_web_ui/.gitignore
  applications/tari_validator_node_web_ui/package-lock.json
  applications/tari_validator_node_web_ui/src/App.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_validator_node_web_ui/src/utils/helpers.tsx
  applications/tari_validator_node_web_ui/src/utils/json_rpc.tsx
  clients/tari_indexer_client/src/types.rs
  clients/validator_node_client/src/types.rs
  dan_layer/consensus/src/hotstuff/proposer.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/indexer_lib/src/transaction_autofiller.rs
  dan_layer/p2p/proto/rpc.proto
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/validator_node_rpc/src/client.rs
  dan_layer/validator_node_rpc/src/proto.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/wallet_transaction.rs
  dan_layer/wallet/sdk/src/network.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2024-01-12-072845_add_executed_and_finalized_time_to_transactions/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2024-01-12-072845_add_executed_and_finalized_time_to_transactions/up.sql
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  integration_tests/src/validator_node_cli.rs
  utilities/tariswap_test_bench/src/runner.rs
  utilities/tariswap_test_bench/src/stats.rs
  utilities/tariswap_test_bench/src/templates.rs
  utilities/transaction_submitter/src/main.rs
Labels: P-acks_required

#917 fix(messaging): check and clear closed substreams before use
  networking/libp2p-messaging/src/behaviour.rs
  networking/libp2p-messaging/src/stream.rs
Labels: P-acks_required

#918 chore!: upgrade to latest feature-dan2
  Cargo.lock
  Cargo.toml
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_indexer/src/dry_run/processor.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/lib.rs
  dan_layer/common_types/Cargo.toml
  dan_layer/common_types/src/hashing.rs
  dan_layer/common_types/src/validator_metadata.rs
  dan_layer/consensus/Cargo.toml
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/vote_receiver.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/engine/Cargo.toml
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/base_layer_hashing.rs
  dan_layer/engine_types/src/hashing.rs
  dan_layer/epoch_manager/Cargo.toml
  dan_layer/epoch_manager/src/base_layer/base_layer_epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/epoch_manager_service.rs
  dan_layer/epoch_manager/src/base_layer/initializer.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/rpc_state_sync/Cargo.toml
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/migrations/2024-01-18-100401_rename_fields/down.sql
  dan_layer/state_store_sqlite/migrations/2024-01-18-100401_rename_fields/up.sql
  dan_layer/state_store_sqlite/migrations/2024-01-22-123711_rename_mined_at_to_proposed_at/down.sql
  dan_layer/state_store_sqlite/migrations/2024-01-22-123711_rename_mined_at_to_proposed_at/up.sql
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/Cargo.toml
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/global/models/validator_node.rs
  dan_layer/template_test_tooling/Cargo.toml
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  integration_tests/Cargo.toml
  integration_tests/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet.rs
  integration_tests/tests/log4rs/cucumber.yml
  integration_tests/tests/steps/wallet.rs
Labels: P-acks_required
