Repository tari-project/tari-ootle, pull requests merged in 2024-09, with the labels that each got.

#1128 fix(watcher): register before expiry and use network consts
  applications/tari_watcher/README.md
  applications/tari_watcher/src/constants.rs
  applications/tari_watcher/src/helpers.rs
  applications/tari_watcher/src/main.rs
  applications/tari_watcher/src/manager.rs
  applications/tari_watcher/src/minotari.rs
  applications/tari_watcher/src/monitoring.rs
  applications/tari_watcher/src/process.rs
  applications/tari_watcher/src/registration.rs
Labels: P-acks_required, P-reviews_required

#1132 feat(dan): add resource metadata for image url
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/mod.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
Labels: P-acks_required

#1131 fix(watcher): general fixes while testing
  Cargo.lock
  applications/tari_dan_app_utilities/config_presets/c_validator_node.toml
  applications/tari_dan_app_utilities/config_presets/d_indexer.toml
  applications/tari_indexer/Cargo.toml
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_indexer/src/config.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_swarm_daemon/src/process_definitions/indexer.rs
  applications/tari_swarm_daemon/src/process_definitions/validator_node.rs
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/config.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_watcher/Cargo.toml
  applications/tari_watcher/src/cli.rs
  applications/tari_watcher/src/config.rs
  applications/tari_watcher/src/constants.rs
  applications/tari_watcher/src/helpers.rs
  applications/tari_watcher/src/main.rs
  applications/tari_watcher/src/manager.rs
  applications/tari_watcher/src/minotari.rs
  applications/tari_watcher/src/monitoring.rs
  applications/tari_watcher/src/process.rs
  applications/tari_watcher/src/registration.rs
  clients/base_node_client/Cargo.toml
  clients/base_node_client/src/grpc.rs
  integration_tests/src/base_node.rs
  integration_tests/src/indexer.rs
  integration_tests/src/validator_node.rs
Labels: P-acks_required, P-reviews_required

#1133 fix(consensus)!: fix block and leader fee proposals
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/transaction_pool.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/consensus_models/transaction_pool_status_update.rs
  utilities/tariswap_test_bench/templates/tariswap/src/lib.rs
Labels: P-acks_required, P-reviews_required

#1129 fix(dan)!: update nft address format
  .license.ignore
  bindings/dist/index.d.ts
  bindings/dist/index.js
  bindings/dist/types/SubstateRequirementLockIntent.d.ts
  bindings/dist/types/SubstateRequirementLockIntent.js
  bindings/src/index.ts
  bindings/src/types/SubstateRequirementLockIntent.ts
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/template_lib/src/models/non_fungible_index.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
Labels: P-acks_required

#1135 feat(consensus)!: add sidechain id in the genesis block
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  bindings/dist/index.d.ts
  bindings/dist/index.js
  bindings/dist/tari-indexer-client.d.ts
  bindings/dist/tari-indexer-client.js
  bindings/dist/types/Block.d.ts
  bindings/dist/types/ExtraData.d.ts
  bindings/dist/types/ExtraData.js
  bindings/dist/validator-node-client.d.ts
  bindings/dist/validator-node-client.js
  bindings/dist/wallet-daemon-client.d.ts
  bindings/dist/wallet-daemon-client.js
  bindings/src/index.ts
  bindings/src/tari-indexer-client.ts
  bindings/src/types/Block.ts
  bindings/src/types/ExtraData.ts
  bindings/src/validator-node-client.ts
  bindings/src/wallet-daemon-client.ts
  dan_layer/common_types/src/bytes.rs
  dan_layer/common_types/src/extra_data.rs
  dan_layer/common_types/src/lib.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/hotstuff/config.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/sql_models/foreign_proposal.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/error.rs
Labels: P-acks_required, P-reviews_required

#1136 test(cucumber): enable counter template scenario
  integration_tests/src/helpers.rs
  integration_tests/src/indexer.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/counter.feature
  integration_tests/tests/features/counter.feature.ignore
Labels: CR-insufficient_context, P-acks_required

#1137 test(cucumber): nft and fungible features
  integration_tests/src/miner.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/counter.feature
  integration_tests/tests/features/fungible.feature
  integration_tests/tests/features/fungible.feature.ignore
  integration_tests/tests/features/nft.feature
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1138 feat!: new account constructor for custom access rules
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_validator_node_cli/src/command/account.rs
  bindings/src/types/Instruction.ts
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine/tests/airdrop.rs
  dan_layer/engine_types/src/instruction.rs
  dan_layer/p2p/proto/transaction.proto
  dan_layer/p2p/src/conversions/transaction.rs
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_lib/src/auth/owner_rule.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/transaction/src/builder.rs
Labels: P-acks_required, P-reviews_required

#1140 test(cucumber): add concurrent wallet daemon call
  integration_tests/src/helpers.rs
  integration_tests/src/validator_node_cli.rs
  integration_tests/src/wallet_daemon_cli.rs
  integration_tests/tests/cucumber.rs
  integration_tests/tests/features/concurrency.feature.ignore
Labels: P-acks_required

#1134 fix(consensus)!: read-only resource + other fixes
  Cargo.lock
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_swarm_daemon/src/logger.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  bindings/dist/types/FeeBreakdown.d.ts
  bindings/dist/types/FeeCostBreakdown.d.ts
  bindings/dist/types/FeeReceipt.d.ts
  bindings/dist/types/VersionedSubstateIdLockIntent.d.ts
  bindings/src/types/FeeBreakdown.ts
  bindings/src/types/FeeCostBreakdown.ts
  bindings/src/types/FeeReceipt.ts
  bindings/src/types/VersionedSubstateIdLockIntent.ts
  dan_layer/consensus/src/hotstuff/common.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/substate_store/error.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/manager.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/prepared.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/transaction_executor.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/engine/src/runtime/fee_state.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/Cargo.toml
  dan_layer/engine_types/src/fees.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/lock_intent.rs
  dan_layer/storage/src/consensus_models/substate_lock.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  integration_tests/tests/steps/validator_node.rs
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/tariswap_test_bench/src/faucet.rs
  utilities/tariswap_test_bench/src/main.rs
  utilities/tariswap_test_bench/src/runner.rs
  utilities/tariswap_test_bench/src/tariswap.rs
Labels: P-acks_required, P-reviews_required

#1143 fix(engine): simplify and improve state store performance
  Cargo.lock
  Cargo.toml
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_indexer/src/dry_run/processor.rs
  applications/tari_validator_node/src/consensus/block_transaction_executor.rs
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  dan_layer/consensus_tests/src/support/transaction_executor.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/state_store.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/src/state_store/bootstrap.rs
  dan_layer/engine/src/state_store/memory.rs
  dan_layer/engine/src/state_store/mod.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/tests/test.rs
  dan_layer/storage_lmdb/Cargo.toml
  dan_layer/storage_lmdb/src/engine_state_store.rs
  dan_layer/storage_lmdb/src/lib.rs
  dan_layer/template_test_tooling/src/read_only_state_store.rs
  dan_layer/template_test_tooling/src/template_test.rs
Labels: P-acks_required, P-reviews_required

#1157 fix(consensus): vote handling improvement, bug fixes
  Cargo.lock
  applications/tari_dan_app_utilities/src/consensus_constants.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_swarm_daemon/Cargo.toml
  applications/tari_swarm_daemon/src/process_manager/executables/manager.rs
  applications/tari_validator_node/src/consensus/metrics.rs
  applications/tari_validator_node/src/consensus/signature_service.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/mempool/gossip.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/messaging/gossip.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/hotstuff/block_change_set.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_transaction.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/vote_collector.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/messages/message.rs
  dan_layer/consensus/src/messages/vote.rs
  dan_layer/consensus/src/traits/hooks.rs
  dan_layer/consensus/src/traits/signing_service.rs
  dan_layer/consensus_tests/src/support/signing_service.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine_types/src/confidential/withdraw.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/proto/transaction.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/p2p/src/conversions/transaction.rs
  dan_layer/p2p/src/message.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/block.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/foreign_proposal.rs
  dan_layer/storage/src/consensus_models/no_vote.rs
  dan_layer/storage/src/consensus_models/quorum_certificate.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/consensus_models/transaction_pool_status_update.rs
  dan_layer/storage/src/consensus_models/vote.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/transaction/src/signature.rs
  dan_layer/transaction/src/transaction_id.rs
  dan_layer/wallet/sdk/Cargo.toml
  networking/swarm/Cargo.toml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required
