Repository tari-project/tari-ootle, pull requests merged in 2024-02, with the labels that each got.

#926 fix(engine)!: determinism bug with log entries
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Logs.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/Logs.tsx
  dan_layer/engine_types/src/logs.rs
Labels: P-acks_required

#925 fix: use hash domains from tari_hash_domains
  Cargo.lock
  dan_layer/engine_types/src/hashing.rs
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/confidential/proof.rs
Labels: P-acks_required

#802 feat: foreign proposal transaction timeout
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/bookkeeping.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/foreign_proposal.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required

#914 feat(consensus): adds metrics to consensus
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/metrics.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/spec.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/metrics.rs
  applications/tari_validator_node/src/p2p/rpc/sync_task.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/metrics.rs
  applications/tari_validator_node/src/p2p/services/mempool/mod.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_sync_request.rs
  dan_layer/consensus/src/hotstuff/proposer.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/hooks.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus_tests/src/support/spec.rs
  dan_layer/consensus_tests/src/support/validator/builder.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/command.rs
  prometheus/dashboard.json
  prometheus/docker-compose.yml
  prometheus/prometheus.yml
Labels: CR-too_long, P-acks_required

#927 fix(consensus): dont transition to error state with invalid foreign proposal
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/network.rs
Labels: P-acks_required

#932 fix: clippy on new rust stable
  applications/tari_indexer/src/json_rpc/handlers.rs
  dan_layer/consensus_tests/src/support/harness.rs
Labels: P-acks_required, P-reviews_required

#929 feat(scaffold): wait for transaction result
  Cargo.lock
  applications/tari_scaffolder/Cargo.toml
  applications/tari_scaffolder/src/cli.rs
  applications/tari_scaffolder/src/main.rs
  applications/tari_scaffolder/src/snake_case.rs
  applications/tari_scaffolder/src/template/Cargo.toml.liquid
  applications/tari_scaffolder/src/template/src/cli.rs.liquid
  applications/tari_scaffolder/src/template/src/daemon_client.rs.liquid
Labels: P-acks_required

#931 fix(walletd): handle null NFT metadata case
  dan_layer/engine_types/src/non_fungible.rs
Labels: P-acks_required

#933 feat(scaffold): allow for multiple generators + walletd client
  Cargo.lock
  applications/tari_scaffolder/Cargo.toml
  applications/tari_scaffolder/README.md
  applications/tari_scaffolder/liquid_templates/rust_cli/.gitignore.liquid
  applications/tari_scaffolder/liquid_templates/rust_cli/Cargo.toml.liquid
  applications/tari_scaffolder/liquid_templates/rust_cli/src/cli.rs.liquid
  applications/tari_scaffolder/liquid_templates/rust_cli/src/daemon_client.rs.liquid
  applications/tari_scaffolder/liquid_templates/rust_cli/src/main.rs.liquid
  applications/tari_scaffolder/src/cli.rs
  applications/tari_scaffolder/src/command.rs
  applications/tari_scaffolder/src/generators/liquid/mod.rs
  applications/tari_scaffolder/src/generators/liquid/snake_case.rs
  applications/tari_scaffolder/src/generators/mod.rs
  applications/tari_scaffolder/src/main.rs
  clients/javascript/wallet_daemon_client/.gitignore
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
  clients/javascript/wallet_daemon_client/src/index.ts
  clients/javascript/wallet_daemon_client/tsconfig.json
Labels: P-acks_required

#934 chore: add `@tarilabs` to the bindings package
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/package.json
  applications/tari_dan_wallet_web_ui/src/Components/StatusChip.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useTransactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimBurn.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ClaimFees.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SelectAccount.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Events.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/FeeInstructions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Instructions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Logs.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Substates.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  bindings/package.json
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context, P-acks_required

#921 feat: adapt indexer to ts-rs exported interfaces
  Cargo.lock
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer_web_ui/package-lock.json
  applications/tari_indexer_web_ui/package.json
  applications/tari_indexer_web_ui/src/routes/VN/Components/Connections.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/Info.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/MonitoredNftCollections.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/MonitoredSubstates.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/NftGallery.tsx
  applications/tari_indexer_web_ui/src/routes/VN/Components/RecentTransactions.tsx
  applications/tari_indexer_web_ui/src/routes/VN/ValidatorNode.tsx
  applications/tari_indexer_web_ui/src/utils/interfaces.tsx
  applications/tari_indexer_web_ui/src/utils/json_rpc.tsx
  bindings/index.ts
  bindings/src/types/AddAddressResponse.ts
  bindings/src/types/AuthLoginRequest.ts
  bindings/src/types/ClearAddressesResponse.ts
  bindings/src/types/Connection.ts
  bindings/src/types/DeleteAddressResponse.ts
  bindings/src/types/ExecutedTransaction.ts
  bindings/src/types/GetAddressesResponse.ts
  bindings/src/types/GetAllVnsRequest.ts
  bindings/src/types/GetAllVnsResponse.ts
  bindings/src/types/GetCommsStatsResponse.ts
  bindings/src/types/GetNonFungibleCollectionsResponse.ts
  bindings/src/types/GetNonFungibleCountResponse.ts
  bindings/src/types/GetTransactionResultResponse.ts
  bindings/src/types/IndexerTransactionFinalizedResult.ts
  clients/base_node_client/Cargo.toml
  clients/base_node_client/src/types.rs
  clients/tari_indexer_client/Cargo.toml
  clients/tari_indexer_client/src/types.rs
  clients/validator_node_client/src/types.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
Labels: CR-too_long, P-acks_required

#941 feat: add tari-generate
  Cargo.lock
  Cargo.toml
  applications/tari_generate/Cargo.toml
  applications/tari_generate/liquid_templates/rust_cli/.gitignore.liquid
  applications/tari_generate/liquid_templates/rust_cli/Cargo.toml.liquid
  applications/tari_generate/liquid_templates/rust_cli/src/cli.rs.liquid
  applications/tari_generate/liquid_templates/rust_cli/src/daemon_client.rs.liquid
  applications/tari_generate/liquid_templates/rust_cli/src/main.rs.liquid
  applications/tari_generate/src/generators/liquid/mod.rs
  applications/tari_generate/src/generators/liquid/snake_case.rs
  applications/tari_generate/src/generators/mod.rs
  applications/tari_generate/src/main.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
Labels: P-acks_required

#937 chore: update to latest feature-dan2
  Cargo.lock
  Cargo.toml
  clients/base_node_client/src/grpc.rs
  dan_layer/common_types/Cargo.toml
  dan_layer/common_types/src/validator_metadata.rs
  dan_layer/engine/src/runtime/scope.rs
  dan_layer/engine_types/src/base_layer_hashing.rs
  dan_layer/engine_types/src/hashing.rs
  integration_tests/src/base_node.rs
Labels: P-acks_required

#940 fix(engine): prevent creation of mismatched resource type bucket
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/tests/shenanigans.rs
  dan_layer/engine/tests/templates/resource_shenanigans/Cargo.toml
  dan_layer/engine/tests/templates/resource_shenanigans/src/lib.rs
  dan_layer/engine_types/src/resource_container.rs
Labels: P-acks_required

#948 fix(validator_node_web_ui): infinite loop on transaction details
  applications/tari_validator_node_web_ui/src/routes/Transactions/TransactionDetails.tsx
Labels: P-acks_required

#946 feat(engine)!: allow revealed-only mint and transfers
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/recall.rs
  dan_layer/engine/tests/templates/access_rules/Cargo.toml
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/confidential/faucet/src/lib.rs
  dan_layer/engine_types/src/bucket.rs
  dan_layer/engine_types/src/confidential/proof.rs
  dan_layer/engine_types/src/confidential/validation.rs
  dan_layer/engine_types/src/confidential/withdraw.rs
  dan_layer/engine_types/src/resource_container.rs
  dan_layer/p2p/proto/transaction.proto
  dan_layer/p2p/src/conversions/transaction.rs
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/confidential_proof.rs
  dan_layer/template_lib/src/models/metadata.rs
  dan_layer/template_lib/src/models/proof.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_test_tooling/src/support/confidential.rs
  dan_layer/wallet/sdk/src/apis/confidential_crypto.rs
  dan_layer/wallet/sdk/src/confidential/proof.rs
Labels: P-acks_required

#949 fix: correctly strip prefix from VaultId
  dan_layer/template_lib/src/models/component.rs
  dan_layer/template_lib/src/models/resource.rs
  dan_layer/template_lib/src/models/vault.rs
Labels: P-acks_required

#947 feat(indexer): add list templates
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/json_rpc/server.rs
  bindings/index.ts
  bindings/src/types/tari-indexer-client/ListTemplatesRequest.ts
  bindings/src/types/tari-indexer-client/ListTemplatesResponse.ts
  bindings/tari-indexer-client.ts
  bindings/validator-node-client.ts
  bindings/wallet-daemon-client.ts
  clients/tari_indexer_client/src/types.rs
Labels: P-acks_required
