Repository tari-project/tari-ootle, pull requests merged in 2024-05, with the labels that each got.

#1021 chore: add versions to npms
  bindings/package.json
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: CR-insufficient_context, P-acks_required

#1025 test(cucumber): ignore failing test
  integration_tests/tests/features/concurrency.feature
Labels: P-acks_required, P-reviews_required

#1026 fix(cucumber): update and exit process on ctrl+c
  Cargo.lock
  Cargo.toml
  integration_tests/Cargo.toml
  integration_tests/tests/cucumber.rs
Labels: P-acks_required, P-reviews_required

#1027 fix(mempool): allow local transactions with unversioned inputs
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_validator_node/src/dry_run_transaction_processor.rs
  applications/tari_validator_node/src/p2p/services/mempool/error.rs
  applications/tari_validator_node/src/p2p/services/mempool/executor.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/metrics.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/mempool/traits.rs
  applications/tari_validator_node/src/substate_resolver.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/lib.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/transaction/src/transaction.rs
  integration_tests/tests/features/concurrency.feature
Labels: P-acks_required, P-reviews_required

#1029 fix: lock rust stable version to 1.77
  .github/workflows/ci.yml
  rust-toolchain.toml
Labels: P-acks_required

#1028 chore: update libp2p
  Cargo.lock
  Cargo.toml
  applications/tari_indexer/src/event_manager.rs
  applications/tari_indexer/src/substate_manager.rs
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
  applications/tari_swarm_daemon/src/config.rs
  applications/tari_validator_node/src/metrics.rs
  integration_tests/src/base_node.rs
  integration_tests/src/validator_node.rs
  integration_tests/src/wallet_daemon.rs
  networking/core/src/spawn.rs
  networking/rpc_framework/src/optional.rs
Labels: P-acks_required

#1030 ci(fix): bring binary builds in line with main project
  .github/workflows/build_binaries.json
  .github/workflows/build_binaries.yml
  .github/workflows/build_dockers.yml
  docker_rig/tari-dan.Dockerfile
Labels: P-acks_required

#1032 fix(mempool): insert transaction for failed before validation
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/after/has_involved_shards.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/epoch_range.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/fee.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/has_inputs.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/signature.rs
  applications/tari_validator_node/src/p2p/services/mempool/validators/before/template_exists.rs
Labels: P-acks_required

#1031 fix(consensus)!: implements power of two and half shard boundaries
  Cargo.lock
  Cargo.toml
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/common_types/Cargo.toml
  dan_layer/common_types/src/shard.rs
  dan_layer/common_types/src/substate_address.rs
  dan_layer/common_types/src/uint.rs
  dan_layer/common_types/src/validator_metadata.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/consensus_tests/src/support/helpers.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/epoch_manager/src/base_layer/base_layer_epoch_manager.rs
  dan_layer/epoch_manager/src/base_layer/config.rs
Labels: P-acks_required

#1036 fix: remove incorrect limit
  applications/tari_indexer/src/event_manager.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
Labels: CR-insufficient_context, P-acks_required

#1038 fix: minor improvements to template lib and test tooling
  clients/validator_node_client/Cargo.toml
  dan_layer/engine/src/runtime/actions.rs
  dan_layer/engine/src/runtime/tracker_auth.rs
  dan_layer/engine/tests/access_rules.rs
  dan_layer/engine/tests/account.rs
  dan_layer/engine/tests/account_nfts.rs
  dan_layer/engine/tests/composability.rs
  dan_layer/engine/tests/confidential.rs
  dan_layer/engine/tests/events.rs
  dan_layer/engine/tests/fees.rs
  dan_layer/engine/tests/shenanigans.rs
  dan_layer/engine/tests/tariswap.rs
  dan_layer/engine/tests/test.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/template_lib/src/component/instance.rs
  dan_layer/template_lib/src/models/bucket.rs
  dan_layer/template_lib/src/models/resource.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_test_tooling/src/template_test.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required

#1039 fix(consensus): deferred execution fixes
  applications/tari_dan_app_utilities/src/transaction_executor.rs
  applications/tari_validator_node/src/consensus/block_transaction_executor.rs
  applications/tari_validator_node/src/p2p/services/mempool/executor.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/common_types/src/committee.rs
  dan_layer/consensus/src/hotstuff/block_change_set.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/substate_store/error.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/executed_transaction.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/consensus_models/transaction_execution.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required, P-reviews_required

#1042 fix(tari-generate): fix some small bugs
  applications/tari_generate/src/generators/mod.rs
  applications/tari_generate/src/main.rs
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1041 feat(tari_swarm_daemon): link up wallet daemon and signaling server
  applications/tari_swarm_daemon/src/main.rs
  applications/tari_swarm_daemon/src/process_definitions/context.rs
  applications/tari_swarm_daemon/src/process_definitions/wallet_daemon.rs
  applications/tari_swarm_daemon/src/process_manager/instances/manager.rs
  applications/tari_swarm_daemon/src/process_manager/processes/signaling_server.rs
Labels: P-acks_required
