Repository tari-project/tari-ootle, pull requests merged in 2025-02, with the labels that each got.

#1283 chore(ci): move binary audit to before archive and checksums
  .github/workflows/build_binaries.yml
Labels: P-acks_required, P-reviews_required

#1287 chore: v0.8.1
  Cargo.lock
  Cargo.toml
Labels: CR-insufficient_context

#1288 chore: wallet daemon and npm pain points
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_web_ui/src/Components/WalletConnectLink/WalletConnectLink.tsx
  applications/tari_dan_wallet_web_ui/src/theme/LayoutMain.tsx
  bindings/package-lock.json
  bindings/package.json
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: P-acks_required

#1296 fix: set versions for template wasm independently
  Cargo.lock
  Cargo.toml
  dan_layer/engine/src/wasm/process.rs
  dan_layer/template_abi/Cargo.toml
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_macros/Cargo.toml
  dan_layer/template_test_tooling/Cargo.toml
Labels: P-acks_required, P-reviews_required

#1301 fix(ci): add tari_swarm_daemon to build matrix
  .github/workflows/build_binaries.yml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1300 fix(indexer): sync templates from event scanner
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer/src/network_client.rs
  applications/tari_indexer/src/transaction_manager/error.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/global/models/validator_node.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
Labels: P-acks_required, P-reviews_required

#1302 fix(indexer): list_substates can also list nfts
  applications/tari_indexer/src/substate_storage_sqlite/sqlite_substate_store_factory.rs
Labels: P-acks_required, P-reviews_required

#1308 fix(wallet): correct version for vaults in substates table
  dan_layer/wallet/sdk/src/apis/transaction.rs
Labels: P-acks_required, P-reviews_required

#1307 fix(mempool): provide finalize result for invalid transactions
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/storage/src/consensus_models/transaction.rs
Labels: P-acks_required, P-reviews_required

#1309 fix(wallet): add missing resource_id field in upsert
  .github/workflows/ci.yml
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_swarm_daemon/src/webserver/server.rs
  applications/tari_watcher/src/transaction_worker.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/epoch_manager/src/service/epoch_manager.rs
  dan_layer/indexer_lib/src/substate_scanner.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/block_pledges.rs
  dan_layer/storage/src/consensus_models/evidence.rs
  dan_layer/storage/src/consensus_models/substate_lock.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/global/base_layer_db.rs
  dan_layer/storage/src/global/bmt_db.rs
  dan_layer/storage/src/global/epoch_db.rs
  dan_layer/storage/src/global/validator_node_db.rs
  dan_layer/template_lib/src/models/non_fungible.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  integration_tests/src/wallet_daemon_cli.rs
  networking/libp2p-messaging/src/behaviour.rs
  networking/libp2p-peersync/src/behaviour.rs
  networking/rpc_framework/src/body.rs
Labels: P-acks_required

#1303 fix(indexer): new graphql url config option
  applications/tari_indexer/src/cli.rs
  applications/tari_indexer/src/config.rs
  applications/tari_indexer/src/http_ui/server.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer_web_ui/src/routes/Events/Events.tsx
  applications/tari_indexer_web_ui/src/utils/graphql.tsx
  applications/tari_swarm_daemon/src/process_definitions/context.rs
  applications/tari_swarm_daemon/src/process_definitions/indexer.rs
  applications/tari_swarm_daemon/src/process_manager/handle.rs
  applications/tari_swarm_daemon/src/webserver/rpc/indexers.rs
Labels: P-acks_required

#1310 fix(indexer): implement code review comments from #1303
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_indexer/src/http_ui/server.rs
  applications/tari_indexer/src/lib.rs
  applications/tari_indexer_web_ui/src/utils/graphql.tsx
  applications/tari_swarm_daemon/src/process_manager/handle.rs
  applications/tari_swarm_daemon/src/process_manager/instances/manager.rs
  applications/tari_swarm_daemon/src/process_manager/manager.rs
  applications/tari_swarm_daemon/src/process_manager/port_allocator.rs
  applications/tari_swarm_daemon/src/webserver/rpc/instances.rs
  applications/tari_swarm_daemon/webui/src/routes/Main.tsx
Labels: P-acks_required, P-reviews_required

#1315 chore: update package locks after npm publish
  applications/tari_validator_node_web_ui/package-lock.json
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context

#1316 chore: release new js wallet client
  applications/tari_dan_wallet_web_ui/package-lock.json
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: P-acks_required, P-reviews_required
