Repository tari-project/tari-ootle, pull requests merged in 2025-06, with the labels that each got.

#1448 fix(epoch-oracles): finish implementation of hybrid epoch oracle
  applications/tari_dan_app_utilities/config_presets/a_common.toml
  applications/tari_dan_app_utilities/config_presets/f_epoch_oracle.toml
  applications/tari_dan_app_utilities/src/configuration.rs
  applications/tari_dan_app_utilities/src/epoch_oracle_config.rs
  applications/tari_dan_app_utilities/src/keypair.rs
  applications/tari_dan_wallet_daemon/src/http_ui/server.rs
  applications/tari_dan_wallet_daemon/web_ui/src/routes/AssetVault/Components/PublishTemplate.tsx
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_indexer/src/cli.rs
  applications/tari_indexer/src/graphql/server.rs
  applications/tari_indexer/src/http_ui/server.rs
  applications/tari_indexer/src/json_rpc/handlers.rs
  applications/tari_indexer/src/json_rpc/server.rs
  applications/tari_swarm_daemon/src/webserver/server.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/dan_node.rs
  applications/tari_validator_node/src/http_ui/server.rs
  applications/tari_validator_node/src/json_rpc/handlers.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/main.rs
  dan_layer/common_types/src/epoch.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/on_catch_up_sync.rs
  dan_layer/consensus/src/hotstuff/on_catch_up_sync_request.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/vote_collector/collector.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/certificate.rs
  dan_layer/epoch_manager/src/epoch_event_oracle/event.rs
  dan_layer/epoch_manager/src/service/epoch_manager_service.rs
  dan_layer/epoch_oracles/Cargo.toml
  dan_layer/epoch_oracles/src/base_layer/mod.rs
  dan_layer/epoch_oracles/src/configured/epoch_ticker.rs
  dan_layer/epoch_oracles/src/configured/mod.rs
  dan_layer/epoch_oracles/src/configured/oracle.rs
  dan_layer/epoch_oracles/src/hybrid/mod.rs
  dan_layer/epoch_oracles/src/hybrid/oracle.rs
  dan_layer/epoch_oracles/src/hybrid/watch_ticker.rs
  dan_layer/epoch_oracles/src/lib.rs
  dan_layer/epoch_oracles/src/store.rs
  dan_layer/state_store_rocksdb/src/writer.rs
  dan_layer/storage/src/state_store/mod.rs
  integration_tests/src/validator_node.rs
  utilities/db_inspector/src/webserver/server.rs
Labels: P-acks_required, P-reviews_required

#1433 feat: upgrade metrics and add libp2p metrics
  Cargo.lock
  Cargo.toml
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/Cargo.toml
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/metrics.rs
  applications/tari_validator_node/src/consensus/spec.rs
  applications/tari_validator_node/src/json_rpc/metrics.rs
  applications/tari_validator_node/src/json_rpc/mod.rs
  applications/tari_validator_node/src/json_rpc/server.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/metrics.rs
  applications/tari_validator_node/src/p2p/services/mempool/initializer.rs
  applications/tari_validator_node/src/p2p/services/mempool/metrics.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/traits/hooks.rs
  networking/core/Cargo.toml
  networking/core/src/builder.rs
  networking/core/src/lib.rs
  networking/core/src/message_mode.rs
  networking/core/src/worker.rs
  networking/libp2p-messaging/Cargo.toml
  networking/libp2p-messaging/src/lib.rs
  networking/libp2p-messaging/src/metrics.rs
  networking/libp2p-peersync/Cargo.toml
  networking/libp2p-peersync/src/lib.rs
  networking/libp2p-peersync/src/metrics.rs
  networking/libp2p-substream/Cargo.toml
  networking/libp2p-substream/src/lib.rs
  networking/libp2p-substream/src/metrics.rs
  networking/swarm/Cargo.toml
  networking/swarm/src/lib.rs
  networking/swarm/src/metrics.rs
  prometheus/README.md
  prometheus/docker-compose.yml
  prometheus/prometheus.yml
Labels: P-acks_required, P-reviews_required

#1456 fix: disambiguate tx args and call args
  applications/tari_wallet_cli/src/command/transaction.rs
  applications/tari_walletd/build.rs
  applications/tari_walletd/src/handlers/accounts.rs
  applications/tari_walletd/web_ui/tsconfig.json
  clients/tari_indexer_client/src/json_rpc_client.rs
  clients/tari_indexer_client/src/types.rs
  crates/consensus_tests/src/support/transaction.rs
  crates/engine/src/runtime/impl.rs
  crates/engine/src/runtime/limits.rs
  crates/engine/src/runtime/mod.rs
  crates/engine/src/transaction/processor.rs
  crates/engine/tests/access_rules.rs
  crates/engine/tests/account.rs
  crates/engine/tests/account_nfts.rs
  crates/engine/tests/airdrop.rs
  crates/engine/tests/asserts.rs
  crates/engine/tests/composability.rs
  crates/engine/tests/confidential.rs
  crates/engine/tests/events.rs
  crates/engine/tests/fees.rs
  crates/engine/tests/resource.rs
  crates/engine/tests/tariswap.rs
  crates/engine/tests/templates/access_rules/src/lib.rs
  crates/engine/tests/templates/composability/src/lib.rs
  crates/engine/tests/templates/reentrancy/src/lib.rs
  crates/engine/tests/templates/shenanigans/src/lib.rs
  crates/engine/tests/test.rs
  crates/engine_types/src/argument_parser.rs
  crates/engine_types/src/instruction.rs
  crates/template_lib/src/args/mod.rs
  crates/template_lib/src/models/vault.rs
  crates/template_lib/src/prelude.rs
  crates/transaction/src/builder/mod.rs
  crates/transaction/src/transaction.rs
  crates/transaction_manifest/src/generator.rs
  crates/transaction_manifest/tests/parser.rs
  integration_tests/src/validator_node_cli.rs
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: CR-too_long

#1464 chore: update feature-dan2 branch
  Cargo.lock
  Cargo.toml
  applications/tari_swarm_daemon/src/layer_one_transactions/submitter.rs
  applications/tari_swarm_daemon/src/process_manager/processes/minotari_wallet.rs
  applications/tari_watcher/src/minotari.rs
  crates/consensus/src/hotstuff/state_machine/idle.rs
  crates/epoch_manager/src/service/epoch_manager.rs
  crates/epoch_manager/src/service/epoch_manager_service.rs
  crates/state_store_rocksdb/src/tests.rs
  crates/state_store_tests/src/helpers.rs
  integration_tests/Cargo.toml
  integration_tests/src/base_node.rs
  integration_tests/src/lib.rs
  integration_tests/src/miner.rs
  integration_tests/src/wallet.rs
  integration_tests/tests/steps/validator_node.rs
  integration_tests/tests/steps/wallet.rs
  integration_tests/tests/steps/wallet_daemon.rs
  networking/rpc_framework/src/server/mod.rs
Labels: CR-too_long, P-acks_required, P-reviews_required

#1465 fix(wallet/webui): fix possible crash in nft list
  Cargo.lock
  applications/tari_walletd/web_ui/src/routes/AssetVault/Components/TransferNft.tsx
  applications/tari_walletd/web_ui/src/routes/Settings/Components/ViewVaultBalance.tsx
  crates/common_types/src/versioned_substate_id.rs
Labels: P-acks_required, P-reviews_required

#1467 chore: release v0.10.1
  CHECKLISTS.md
  Cargo.lock
  Cargo.toml
Labels: CR-insufficient_context

#1470 fix(bindings): fix cannot serialize bigint
  applications/tari_walletd/web_ui/src/routes/AssetVault/Components/AccountBalance.tsx
  bindings/package.json
  bindings/src/types/SubstateRequirement.ts
  bindings/src/types/wallet-daemon-client/SubstatesListRequest.ts
  clients/javascript/wallet_daemon_client/package.json
  clients/wallet_daemon_client/src/types.rs
Labels: P-acks_required, P-reviews_required

#1473 chore: release 0.10.2
  CHECKLISTS.md
  Cargo.lock
  Cargo.toml
Labels: CR-insufficient_context

#1475 chore: version 0.10.3
  Cargo.lock
  Cargo.toml
Labels: CR-insufficient_context

#1477 fix(template_lib)!: remove unused vault/bucket functions + docs
  Cargo.lock
  applications/tari_walletd/src/handlers/confidential.rs
  crates/engine/src/runtime/engine_args.rs
  crates/engine/src/runtime/impl.rs
  crates/engine/src/runtime/working_state.rs
  crates/engine/tests/confidential.rs
  crates/engine/tests/templates/confidential/faucet/src/lib.rs
  crates/engine/tests/templates/confidential/utilities/src/lib.rs
  crates/engine/tests/templates/nft/basic_nft/src/lib.rs
  crates/engine/tests/templates/resource/src/lib.rs
  crates/engine_types/src/bucket.rs
  crates/engine_types/src/resource.rs
  crates/engine_types/src/resource_container.rs
  crates/engine_types/src/vault.rs
  crates/template_builtin/Cargo.toml
  crates/template_builtin/src/account.rs
  crates/template_builtin/src/lib.rs
  crates/template_builtin/templates/account/src/lib.rs
  crates/template_lib/Cargo.toml
  crates/template_lib/src/args/types.rs
  crates/template_lib/src/lib.rs
  crates/template_lib/src/models/address_allocation.rs
  crates/template_lib/src/models/amount.rs
  crates/template_lib/src/models/bucket.rs
  crates/template_lib/src/models/component.rs
  crates/template_lib/src/models/confidential_proof.rs
  crates/template_lib/src/models/layer_one_commitment.rs
  crates/template_lib/src/models/proof.rs
  crates/template_lib/src/models/resource.rs
  crates/template_lib/src/models/vault.rs
  crates/template_lib/src/resource/builder/confidential.rs
  crates/template_lib/src/resource/manager.rs
  crates/wallet/sdk/src/apis/confidential_transfer.rs
Labels: P-acks_required, P-reviews_required
