Repository tari-project/tari-ootle, pull requests merged in 2025-01, with the labels that each got.

#1230 fix: walletd client package lockfile
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context

#1231 chore: update wallet daemon client version 1.3.0
  applications/tari_dan_wallet_web_ui/package-lock.json
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: CR-insufficient_context

#1234 fix(wallet/webui): fix crash in renderJson
  applications/tari_dan_wallet_web_ui/src/utils/helpers.tsx
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1236 fix(wallet/webui): nft data json render fix
  applications/tari_dan_wallet_web_ui/src/Components/FetchStatusCheck.tsx
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AccountBalance.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Keys.tsx
  applications/tari_dan_wallet_web_ui/src/utils/cbor.ts
Labels: P-acks_required, P-reviews_required

#1235 fix(consensus): validate evidence, stuck transactions bug + other fixes
  Cargo.toml
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/PublishTemplate.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  bindings/dist/base-node-client.js
  bindings/dist/helpers/helpers.js
  bindings/dist/index.d.ts
  bindings/dist/index.js
  bindings/dist/tari-indexer-client.d.ts
  bindings/dist/tari-indexer-client.js
  bindings/dist/types/RejectReason.d.ts
  bindings/dist/validator-node-client.d.ts
  bindings/dist/validator-node-client.js
  bindings/dist/wallet-daemon-client.d.ts
  bindings/dist/wallet-daemon-client.js
  bindings/src/base-node-client.ts
  bindings/src/helpers/helpers.ts
  bindings/src/index.ts
  bindings/src/tari-indexer-client.ts
  bindings/src/types/RejectReason.ts
  bindings/src/validator-node-client.ts
  bindings/src/wallet-daemon-client.ts
  dan_layer/common_types/src/committee.rs
  dan_layer/common_types/src/lock_intent.rs
  dan_layer/consensus/src/block_validations.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_message_validate.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/manager.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/prepared.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/substate_store.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/block_pledges.rs
  dan_layer/storage/src/consensus_models/evidence.rs
  dan_layer/storage/src/consensus_models/foreign_parked_proposal.rs
  dan_layer/storage/src/consensus_models/foreign_proposal.rs
  dan_layer/storage/src/consensus_models/no_vote.rs
  dan_layer/storage/src/consensus_models/substate_lock.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/consensus_models/transaction_decision.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/state_store/mod.rs
  networking/core/src/worker.rs
Labels: CR-too_long, P-acks_required, P-reviews_required

#1237 fix(consensus)!: dont send duplicate substate values when pledging
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/on_message_validate.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/engine_types/src/component.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/storage/src/consensus_models/block_pledges.rs
  dan_layer/storage/src/consensus_models/lock_intent.rs
  dan_layer/storage/src/consensus_models/substate_lock.rs
Labels: P-acks_required, P-reviews_required

#1238 feat(swarm): changes to allow public IP with swarm
  .github/workflows/ci.yml
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_swarm_daemon/src/config.rs
  applications/tari_swarm_daemon/src/main.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_node.rs
  applications/tari_swarm_daemon/src/process_manager/executables/manager.rs
  applications/tari_swarm_daemon/src/process_manager/instances/manager.rs
  applications/tari_swarm_daemon/src/process_manager/manager.rs
  applications/tari_swarm_daemon/src/process_manager/mod.rs
  applications/tari_swarm_daemon/src/process_manager/processes/minotari_node.rs
  applications/tari_swarm_daemon/src/webserver/rpc/dan_wallets.rs
  applications/tari_swarm_daemon/src/webserver/rpc/indexers.rs
  applications/tari_swarm_daemon/src/webserver/rpc/validator_nodes.rs
  applications/tari_swarm_daemon/src/webserver/server.rs
  dan_layer/engine/src/runtime/tracker_auth.rs
  dan_layer/engine_types/src/resource.rs
  dan_layer/storage/src/consensus_models/evidence.rs
  dan_layer/template_lib/src/models/amount.rs
  networking/core/src/relay_state.rs
  scripts/bundle-app-bins.sh
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1240 fix(consensus): fix bug in foreign proposal validation
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/tariswap_test_bench/src/main.rs
  utilities/tariswap_test_bench/src/runner.rs
  utilities/tariswap_test_bench/src/tariswap.rs
  utilities/tariswap_test_bench/src/timer.rs
Labels: P-acks_required, P-reviews_required

#1245 fix(wallet): ensure assoc. resource address included for detect_inputs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/confidential.rs
  applications/tari_dan_wallet_daemon/src/handlers/helpers.rs
  applications/tari_dan_wallet_daemon/src/handlers/substates.rs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Substates.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionDetails.tsx
  dan_layer/template_lib/Cargo.toml
  dan_layer/wallet/sdk/src/apis/confidential_transfer.rs
  dan_layer/wallet/sdk/src/apis/substate.rs
  dan_layer/wallet/sdk/src/apis/transaction.rs
  dan_layer/wallet/sdk/src/models/non_fungible_tokens.rs
  dan_layer/wallet/sdk/src/models/substate.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2023-02-08-122514_initial/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-04-17-121212_add_default/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-04-17-121212_add_default/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-04-25-155300_add_auth_status/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-04-25-155300_add_auth_status/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-05-09-120000_add_revokability/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-05-09-120000_add_revokability/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-02-156480_add_nft_table/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-02-156480_add_nft_table/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-20-130549_add_encrypted_data_to_outputs/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-20-130549_add_encrypted_data_to_outputs/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-21-122832_add_token_symbol_to_nft_table/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-06-21-122832_add_token_symbol_to_nft_table/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-09-04-200422_add_json_result_to_transactions/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-09-04-200422_add_json_result_to_transactions/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-10-23-083718_remove_token_symbol/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2023-10-23-083718_remove_token_symbol/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2024-01-12-072845_add_executed_and_finalized_time_to_transactions/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2024-01-12-072845_add_executed_and_finalized_time_to_transactions/up.sql
  dan_layer/wallet/storage_sqlite/migrations/2024-03-18-054147_add_required_substates_to_transactions/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2024-03-18-054147_add_required_substates_to_transactions/up.sql
  dan_layer/wallet/storage_sqlite/src/models/account.rs
  dan_layer/wallet/storage_sqlite/src/models/non_fungible_tokens.rs
  dan_layer/wallet/storage_sqlite/src/models/output.rs
  dan_layer/wallet/storage_sqlite/src/models/substate.rs
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  dan_layer/wallet/storage_sqlite/tests/substates.rs
Labels: P-acks_required, P-reviews_required

#1243 feat: add TryFrom impls for SubstateId and Addresses
  dan_layer/engine/src/runtime/address_allocation.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine_types/src/substate.rs
Labels: P-acks_required, P-reviews_required

#1244 fix(consensus)!: optmise foreign pledging for output-only case
  .github/workflows/ci.yml
  applications/tari_dan_app_utilities/src/base_layer_scanner.rs
  applications/tari_indexer/src/event_scanner.rs
  applications/tari_swarm_daemon/src/webserver/templates.rs
  applications/tari_swarm_daemon/webui/src/routes/Main.tsx
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  applications/tari_validator_node_cli/src/command/transaction.rs
  applications/tari_validator_node_web_ui/src/Components/CodeBlock.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/BlockDetails.tsx
  applications/tari_validator_node_web_ui/src/routes/Blocks/Transactions.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/Events.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/FeeInstructions.tsx
  applications/tari_validator_node_web_ui/src/routes/Transactions/Instructions.tsx
  applications/tari_validator_node_web_ui/src/utils/helpers.tsx
  dan_layer/common_types/src/committee.rs
  dan_layer/common_types/src/option.rs
  dan_layer/common_types/src/versioned_substate_id.rs
  dan_layer/consensus/src/hotstuff/block_change_set.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/on_message_validate.rs
  dan_layer/consensus/src/hotstuff/on_next_sync_view.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_request_missing_transactions.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/manager.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/prepared.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/support/epoch_manager.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/network.rs
  dan_layer/consensus_tests/src/support/validator/instance.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/epoch_manager/src/base_layer/base_layer_epoch_manager.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_tree/src/staged_store.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/block_diff.rs
  dan_layer/storage/src/consensus_models/block_pledges.rs
  dan_layer/storage/src/consensus_models/evidence.rs
  dan_layer/storage/src/consensus_models/foreign_proposal.rs
  dan_layer/storage/src/consensus_models/substate_lock.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/consensus_models/transaction_decision.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/state_store/mod.rs
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/tariswap_test_bench/src/main.rs
Labels: CR-too_long, P-acks_required, P-reviews_required

#1242 feat(template): sync templates when syncing substates
  Cargo.lock
  applications/tari_dan_app_utilities/Cargo.toml
  applications/tari_dan_app_utilities/src/template_manager/implementation/initializer.rs
  applications/tari_dan_app_utilities/src/template_manager/implementation/manager.rs
  applications/tari_dan_app_utilities/src/template_manager/implementation/service.rs
  applications/tari_dan_app_utilities/src/template_manager/interface/error.rs
  applications/tari_dan_app_utilities/src/template_manager/interface/handle.rs
  applications/tari_dan_app_utilities/src/template_manager/interface/mod.rs
  applications/tari_dan_app_utilities/src/template_manager/interface/types.rs
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/consensus/spec.rs
  applications/tari_validator_node/src/p2p/rpc/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/rpc/template_sync_task.rs
  applications/tari_validator_node/src/transaction_validators/template_exists.rs
  dan_layer/p2p/proto/rpc.proto
  dan_layer/rpc_state_sync/Cargo.toml
  dan_layer/rpc_state_sync/src/error.rs
  dan_layer/rpc_state_sync/src/manager.rs
  dan_layer/storage/src/global/backend_adapter.rs
  dan_layer/storage/src/global/template_db.rs
  dan_layer/storage_sqlite/src/error.rs
  dan_layer/storage_sqlite/src/global/backend_adapter.rs
  dan_layer/storage_sqlite/src/global/models/template.rs
  dan_layer/validator_node_rpc/src/rpc_service.rs
Labels: P-acks_required

#1247 feat(template-sync-test): updated tests to use new template syncing method
  dan_layer/rpc_state_sync/src/manager.rs
  integration_tests/src/lib.rs
  integration_tests/src/template.rs
  integration_tests/src/templates/basic_nft/src/lib.rs
  integration_tests/src/templates/faucet/src/lib.rs
  integration_tests/tests/features/committee.feature
  integration_tests/tests/features/concurrency.feature
  integration_tests/tests/features/counter.feature
  integration_tests/tests/features/epoch_change.feature
  integration_tests/tests/features/fungible.feature
  integration_tests/tests/features/indexer.feature
  integration_tests/tests/features/nft.feature
  integration_tests/tests/features/state_sync.feature
  integration_tests/tests/features/transfer.feature
  integration_tests/tests/features/wallet_daemon.feature
  integration_tests/tests/steps/validator_node.rs
Labels: P-acks_required

#1250 feat(wallet): Add method transactions.get_all
  Cargo.toml
  clients/wallet_daemon_client/src/lib.rs
Labels: P-acks_required

#1252 fix(swarm): use localhost for inter-node comms
  applications/tari_swarm_daemon/src/process_definitions/context.rs
  applications/tari_swarm_daemon/src/process_definitions/indexer.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_miner.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_node.rs
  applications/tari_swarm_daemon/src/process_definitions/minotari_wallet.rs
  applications/tari_swarm_daemon/src/process_definitions/validator_node.rs
  applications/tari_swarm_daemon/src/process_definitions/wallet_daemon.rs
  applications/tari_swarm_daemon/src/process_manager/manager.rs
Labels: P-acks_required, P-reviews_required

#1256 chore: update node package lockfiles
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_indexer_web_ui/package-lock.json
  applications/tari_validator_node_web_ui/package-lock.json
  clients/javascript/wallet_daemon_client/package-lock.json
  clients/javascript/wallet_daemon_client/package.json
Labels: CR-insufficient_context

#1253 fix(indexer): fixes inability to serialize Connection because of Arc.
  applications/tari_indexer/src/json_rpc/handlers.rs
  clients/tari_indexer_client/src/types.rs
Labels: P-acks_required, P-reviews_required

#1260 fix(wallet/webui): fix settings page
  applications/tari_dan_wallet_daemon/build.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/helpers.rs
  applications/tari_dan_wallet_web_ui/src/App.tsx
  applications/tari_dan_wallet_web_ui/src/Components/NFTList.tsx
  applications/tari_dan_wallet_web_ui/src/api/helpers/types.ts
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useKeys.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useTokens.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useTransactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccountDetails/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/AssetVault.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AccountBalance.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AccountDetails.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/ActionMenu.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/AddAccount.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/MyAssets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/PublishTemplate.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SelectAccount.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/SendMoney.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Onboarding/Onboarding.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/GeneralSettings.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/ViewVaultBalance.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/Transactions.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Transactions/TransactionsLayout.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/AccessTokens.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Components/Accounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Wallet/Wallet.tsx
  applications/tari_dan_wallet_web_ui/src/store/accountStore.ts
  applications/tari_dan_wallet_web_ui/src/theme/LayoutMain.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  bindings/dist/helpers/helpers.d.ts
  bindings/dist/helpers/helpers.js
  bindings/src/helpers/helpers.ts
Labels: CR-insufficient_context, P-acks_required

#1249 feat(wallet): using correct network
  applications/tari_dan_wallet_daemon/src/config.rs
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/helpers.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/validator.rs
  applications/tari_dan_wallet_daemon/src/main.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/transaction_validators/error.rs
  applications/tari_validator_node/src/transaction_validators/mod.rs
  applications/tari_validator_node/src/transaction_validators/network.rs
  integration_tests/src/wallet_daemon.rs
Labels: P-acks_required

#1262 fix(cucumber-tests): using correct network for cucumber test transactions
  integration_tests/src/lib.rs
  integration_tests/src/util.rs
  integration_tests/src/validator_node.rs
  integration_tests/src/wallet_daemon_cli.rs
Labels: P-acks_required

#1265 fix: set the network for all wallet transactions
  Cargo.lock
  applications/tari_dan_wallet_cli/src/command/transaction.rs
  applications/tari_dan_wallet_daemon/src/handlers/settings.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/AssetVault.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Onboarding/Onboarding.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Settings/Components/GeneralSettings.tsx
  bindings/dist/types/wallet-daemon-client/NetworkInfo.d.ts
  bindings/dist/types/wallet-daemon-client/NetworkInfo.js
  bindings/dist/types/wallet-daemon-client/SettingsGetResponse.d.ts
  bindings/dist/types/wallet-daemon-client/SettingsGetResponse.js
  bindings/dist/wallet-daemon-client.d.ts
  bindings/dist/wallet-daemon-client.js
  bindings/package.json
  bindings/src/types/wallet-daemon-client/NetworkInfo.ts
  bindings/src/types/wallet-daemon-client/SettingsGetResponse.ts
  bindings/src/wallet-daemon-client.ts
  clients/javascript/wallet_daemon_client/package.json
  clients/javascript/wallet_daemon_client/src/index.ts
  clients/wallet_daemon_client/src/lib.rs
  clients/wallet_daemon_client/src/types.rs
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/apis/confidential_transfer.rs
  dan_layer/wallet/sdk/src/apis/config.rs
  dan_layer/wallet/sdk/src/sdk.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
  utilities/tariswap_test_bench/Cargo.toml
  utilities/tariswap_test_bench/src/accounts.rs
  utilities/tariswap_test_bench/src/faucet.rs
  utilities/tariswap_test_bench/src/runner.rs
  utilities/tariswap_test_bench/src/tariswap.rs
  utilities/transaction_generator/Cargo.toml
  utilities/transaction_generator/src/cli.rs
  utilities/transaction_generator/src/main.rs
  utilities/transaction_generator/src/transaction_builders/free_coins.rs
  utilities/transaction_generator/src/transaction_builders/manifest.rs
Labels: P-acks_required, P-reviews_required

#1267 chore: update js client package.json
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context

#1268 fix: cucumber test for events, remove resource event
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/tests/events.rs
  dan_layer/engine_types/src/events.rs
  dan_layer/template_lib/src/models/metadata.rs
  integration_tests/tests/features/indexer.feature
Labels: P-acks_required, P-reviews_required

#1263 fix(consensus): detect and abort conflicting cross-shard transactions
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_indexer/src/transaction_manager/mod.rs
  applications/tari_swarm_daemon/webui/src/routes/Main.tsx
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/common_types/src/lock_intent.rs
  dan_layer/common_types/src/substate_address.rs
  dan_layer/consensus/src/hotstuff/block_change_set.rs
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/on_receive_foreign_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_transaction.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/consensus/src/hotstuff/transaction_manager/manager.rs
  dan_layer/consensus/src/traits/transaction_executor.rs
  dan_layer/consensus_tests/src/consensus.rs
  dan_layer/consensus_tests/src/substate_store.rs
  dan_layer/consensus_tests/src/support/executions_store.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/consensus_tests/src/support/transaction.rs
  dan_layer/consensus_tests/src/support/transaction_executor.rs
  dan_layer/engine_types/src/commit_result.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/sql_models/foreign_substate_pledge.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_tree/src/tree.rs
  dan_layer/storage/src/consensus_models/block_header.rs
  dan_layer/storage/src/consensus_models/block_pledges.rs
  dan_layer/storage/src/consensus_models/epoch_checkpoint.rs
  dan_layer/storage/src/consensus_models/evidence.rs
  dan_layer/storage/src/consensus_models/lock_intent.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/consensus_models/substate_lock.rs
  dan_layer/storage/src/consensus_models/transaction.rs
  dan_layer/storage/src/consensus_models/transaction_decision.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/state_store/mod.rs
  utilities/tariswap_test_bench/src/accounts.rs
Labels: P-acks_required, P-reviews_required

#1271 chore: update package.json for wallet client
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context

#1272 chore: update package.json for wallet client
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context

#1273 feat(consensus): skip to local accept phase for aborted transactions
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node_web_ui/src/routes/Transactions/TransactionDetails.tsx
  dan_layer/common_types/src/versioned_substate_id.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/substate_store/pending_store.rs
  dan_layer/storage/src/consensus_models/evidence.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
Labels: P-acks_required, P-reviews_required
