Repository tari-project/tari-ootle, pull requests merged in 2025-03, with the labels that each got.

#1318 fix(wallet): add vault to substates table for NFTs
  applications/tari_dan_wallet_daemon/src/services/account_monitor.rs
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAccounts.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/Assets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/MyAssets.tsx
Labels: P-acks_required, P-reviews_required

#1319 fix(consensus)!: remove unnecessary commands and tx phases
  dan_layer/consensus/src/hotstuff/foreign_proposal_processor.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/engine_types/src/substate.rs
  dan_layer/p2p/proto/consensus.proto
  dan_layer/p2p/src/conversions/consensus.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_sqlite/tests/tests.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/command.rs
  dan_layer/storage/src/consensus_models/no_vote.rs
  dan_layer/storage/src/consensus_models/transaction_pool.rs
  dan_layer/storage/src/state_store/mod.rs
Labels: P-acks_required

#1324 chore(ci): docker builds fixes, rust build bump, workflow and scripts sync with main repo
  .github/workflows/build_dockers_workflow.yml
  docker_rig/cross_compile_tooling.sh
  docker_rig/tari-dan.Dockerfile
  scripts/cross_compile_ubuntu_18-pre-build.sh
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required, P-reviews_required

#1325 fix(indexer): specific error message when no inputs are in the transaction
  applications/tari_indexer/src/network_client.rs
Labels: P-acks_required, P-reviews_required

#1335 feat(wallet-daemon): add method to list nft
  applications/tari_dan_wallet_web_ui/src/Components/WalletConnectLink/WalletConnectLink.tsx
  clients/javascript/wallet_daemon_client/src/index.ts
Labels: P-acks_required, P-reviews_required

#1322 feat(engine)!: allow address allocation in templates and instructions
  Cargo.lock
  Cargo.toml
  bindings/src/types/Committee.ts
  bindings/src/types/CommitteeInfo.ts
  bindings/src/types/Epoch.ts
  bindings/src/types/Era.ts
  bindings/src/types/ExtraData.ts
  bindings/src/types/NodeHeight.ts
  bindings/src/types/NumPreshards.ts
  bindings/src/types/PeerAddress.ts
  bindings/src/types/Shard.ts
  bindings/src/types/ShardGroup.ts
  bindings/src/types/SubstateAddress.ts
  bindings/src/types/SubstateLockType.ts
  bindings/src/types/SubstateRequirement.ts
  bindings/src/types/SubstateType.ts
  bindings/src/types/VersionedSubstateId.ts
  bindings/src/types/base-node-client/BaseLayerValidatorNode.ts
  dan_layer/engine/src/runtime/address_allocation.rs
  dan_layer/engine/src/runtime/error.rs
  dan_layer/engine/src/runtime/impl.rs
  dan_layer/engine/src/runtime/mod.rs
  dan_layer/engine/src/runtime/tracker.rs
  dan_layer/engine/src/runtime/working_state.rs
  dan_layer/engine/src/transaction/processor.rs
  dan_layer/engine/src/wasm/compile.rs
  dan_layer/engine/src/wasm/process.rs
  dan_layer/engine/tests/address_allocation.rs
  dan_layer/engine/tests/templates/access_rules/src/lib.rs
  dan_layer/engine/tests/templates/address_allocation/src/lib.rs
  dan_layer/engine_types/src/id_provider.rs
  dan_layer/engine_types/src/indexed_value.rs
  dan_layer/engine_types/src/instruction.rs
  dan_layer/p2p/proto/transaction.proto
  dan_layer/p2p/src/conversions/transaction.rs
  dan_layer/template_abi/Cargo.toml
  dan_layer/template_abi/src/ops.rs
  dan_layer/template_builtin/templates/account/src/lib.rs
  dan_layer/template_lib/Cargo.toml
  dan_layer/template_lib/src/args/types.rs
  dan_layer/template_lib/src/caller_context.rs
  dan_layer/template_lib/src/component/instance.rs
  dan_layer/template_lib/src/engine.rs
  dan_layer/template_lib/src/models/address_allocation.rs
  dan_layer/template_lib/src/models/binary_tag.rs
  dan_layer/template_lib/src/models/mod.rs
  dan_layer/template_lib/src/prelude.rs
  dan_layer/template_lib/src/resource/builder/confidential.rs
  dan_layer/template_lib/src/resource/builder/fungible.rs
  dan_layer/template_lib/src/resource/builder/mod.rs
  dan_layer/template_lib/src/resource/builder/non_fungible.rs
  dan_layer/template_lib/src/resource/manager.rs
  dan_layer/template_macros/Cargo.toml
  dan_layer/template_test_tooling/Cargo.toml
  dan_layer/template_test_tooling/templates/faucet/Cargo.lock
  dan_layer/transaction/src/builder.rs
  dan_layer/transaction/src/v1/transaction.rs
Labels: P-acks_required

#1333 feat(wallet-daemon): track authored templates and show on UI
  applications/tari_dan_wallet_daemon/src/handlers/templates.rs
  applications/tari_dan_wallet_daemon/src/jrpc_server.rs
  applications/tari_dan_wallet_daemon/src/services/mod.rs
  applications/tari_dan_wallet_daemon/src/services/template_monitor.rs
  applications/tari_dan_wallet_web_ui/package-lock.json
  applications/tari_dan_wallet_web_ui/src/App.tsx
  applications/tari_dan_wallet_web_ui/src/Components/CopyToClipboard.tsx
  applications/tari_dan_wallet_web_ui/src/Components/MenuItems.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useAuth.tsx
  applications/tari_dan_wallet_web_ui/src/api/hooks/useTemplatesAuthored.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AccessToken/AccessToken.tsx
  applications/tari_dan_wallet_web_ui/src/routes/AssetVault/Components/MyAssets.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Onboarding/Onboarding.tsx
  applications/tari_dan_wallet_web_ui/src/routes/Templates/Templates.tsx
  applications/tari_dan_wallet_web_ui/src/theme/LayoutMain.tsx
  applications/tari_dan_wallet_web_ui/src/utils/json_rpc.tsx
  bindings/dist/index.d.ts
  bindings/dist/index.js
  bindings/dist/tari-indexer-client.d.ts
  bindings/dist/tari-indexer-client.js
  bindings/dist/types/Command.d.ts
  bindings/dist/types/TransactionPoolStage.d.ts
  bindings/dist/types/wallet-daemon-client/AuthoredTemplate.d.ts
  bindings/dist/types/wallet-daemon-client/AuthoredTemplate.js
  bindings/dist/types/wallet-daemon-client/TemplatesListAuthoredRequest.d.ts
  bindings/dist/types/wallet-daemon-client/TemplatesListAuthoredRequest.js
  bindings/dist/types/wallet-daemon-client/TemplatesListAuthoredResponse.d.ts
  bindings/dist/types/wallet-daemon-client/TemplatesListAuthoredResponse.js
  bindings/dist/validator-node-client.d.ts
  bindings/dist/validator-node-client.js
  bindings/dist/wallet-daemon-client.d.ts
  bindings/dist/wallet-daemon-client.js
  bindings/package-lock.json
  bindings/package.json
  bindings/src/index.ts
  bindings/src/tari-indexer-client.ts
  bindings/src/types/Command.ts
  bindings/src/types/TransactionPoolStage.ts
  bindings/src/types/wallet-daemon-client/AuthoredTemplate.ts
  bindings/src/types/wallet-daemon-client/TemplatesListAuthoredRequest.ts
  bindings/src/types/wallet-daemon-client/TemplatesListAuthoredResponse.ts
  bindings/src/validator-node-client.ts
  bindings/src/wallet-daemon-client.ts
  clients/javascript/wallet_daemon_client/package.json
  clients/javascript/wallet_daemon_client/src/index.ts
  clients/wallet_daemon_client/src/types.rs
  dan_layer/wallet/sdk/src/apis/key_manager.rs
  dan_layer/wallet/sdk/src/apis/mod.rs
  dan_layer/wallet/sdk/src/apis/template.rs
  dan_layer/wallet/sdk/src/models/authored_template.rs
  dan_layer/wallet/sdk/src/models/mod.rs
  dan_layer/wallet/sdk/src/sdk.rs
  dan_layer/wallet/sdk/src/storage.rs
  dan_layer/wallet/storage_sqlite/migrations/2025-03-06-105802_template/down.sql
  dan_layer/wallet/storage_sqlite/migrations/2025-03-06-105802_template/up.sql
  dan_layer/wallet/storage_sqlite/src/models/authored_template.rs
  dan_layer/wallet/storage_sqlite/src/models/mod.rs
  dan_layer/wallet/storage_sqlite/src/reader.rs
  dan_layer/wallet/storage_sqlite/src/schema.rs
  dan_layer/wallet/storage_sqlite/src/writer.rs
Labels: CR-too_long, P-acks_required, P-reviews_required

#1342 fix: update wallet client package.lock
  clients/javascript/wallet_daemon_client/package-lock.json
Labels: CR-insufficient_context

#1344 fix(wallet): add missing walletconnect method
  applications/tari_dan_wallet_web_ui/src/Components/WalletConnectLink/WalletConnectLink.tsx
Labels: P-acks_required, P-reviews_required

#1343 fix(wallet-daemon): authored templates are not saved always to local DB
  applications/tari_dan_wallet_daemon/src/services/template_monitor.rs
  dan_layer/wallet/sdk/src/apis/template.rs
  dan_layer/wallet/sdk/src/sdk.rs
Labels: P-acks_required, P-reviews_required

#1339 feat(wallet-daemon): wallet seed word restoration
  Cargo.lock
  applications/tari_dan_wallet_daemon/src/cli.rs
  applications/tari_dan_wallet_daemon/src/lib.rs
  applications/tari_dan_wallet_daemon/src/main.rs
  dan_layer/wallet/sdk/Cargo.toml
  dan_layer/wallet/sdk/src/sdk.rs
  dan_layer/wallet/sdk/tests/confidential_output_api.rs
  integration_tests/src/wallet_daemon.rs
  utilities/tariswap_test_bench/src/runner.rs
Labels: P-acks_required, P-reviews_required

#1351 fix: fix compile for windows
  applications/tari_validator_node/src/dan_node.rs
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1350 chore(ci): increase build timeout and disable audit for cross builds
  .github/workflows/build_binaries.yml
Labels: P-acks_required
