Repository tari-project/tari-ootle, pull requests merged in 2025-05, with the labels that each got.

#1415 feat(db-inspector): basic server pagination and key query
  utilities/db_inspector/src/webserver/error.rs
  utilities/db_inspector/src/webserver/handlers/block_diff.rs
  utilities/db_inspector/src/webserver/handlers/blocks.rs
  utilities/db_inspector/src/webserver/handlers/state_transitions.rs
  utilities/db_inspector/src/webserver/handlers/tables.rs
  utilities/db_inspector/src/webserver/handlers/types.rs
  utilities/db_inspector/web_ui/src/client.ts
  utilities/db_inspector/web_ui/src/routes/InspectCf.tsx
Labels: P-acks_required, P-reviews_required

#1418 fix(consensus): collect votes in memory rather in persistent storage
  Cargo.lock
  applications/tari_dan_wallet_daemon/build.rs
  applications/tari_dan_wallet_daemon/web_ui/.gitignore
  applications/tari_dan_wallet_daemon/web_ui/vite.config.ts
  applications/tari_indexer/build.rs
  applications/tari_indexer/web_ui/.gitignore
  applications/tari_indexer/web_ui/vite.config.ts
  applications/tari_validator_node/build.rs
  applications/tari_validator_node/web_ui/.gitignore
  applications/tari_validator_node/web_ui/dist/.gitkeep
  applications/tari_validator_node/web_ui/package.json
  applications/tari_validator_node/web_ui/src/routes/Blocks/BlockDetails.tsx
  applications/tari_validator_node/web_ui/src/routes/VN/Components/Blocks.tsx
  applications/tari_validator_node/web_ui/tsconfig.json
  applications/tari_validator_node/web_ui/vite.config.ts
  dan_layer/consensus/src/hotstuff/commit_proofs.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/on_receive_new_view.rs
  dan_layer/consensus/src/hotstuff/on_receive_vote.rs
  dan_layer/consensus/src/hotstuff/vote_collector.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus_tests/src/eviction_proof.rs
  dan_layer/state_store_rocksdb/src/models/mod.rs
  dan_layer/state_store_rocksdb/src/models/vote.rs
  dan_layer/state_store_rocksdb/src/reader.rs
  dan_layer/state_store_rocksdb/src/store.rs
  dan_layer/state_store_rocksdb/src/writer.rs
  dan_layer/state_store_sqlite/Cargo.toml
  dan_layer/state_store_sqlite/migrations/2023-06-08-091819_create_state_store/up.sql
  dan_layer/state_store_sqlite/src/reader.rs
  dan_layer/state_store_sqlite/src/schema.rs
  dan_layer/state_store_sqlite/src/sql_models/mod.rs
  dan_layer/state_store_sqlite/src/sql_models/vote.rs
  dan_layer/state_store_sqlite/src/writer.rs
  dan_layer/state_store_tests/src/helpers.rs
  dan_layer/state_store_tests/src/lib.rs
  dan_layer/state_store_tests/src/votes.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/vote.rs
  dan_layer/storage/src/consensus_models/vote_signature.rs
  dan_layer/storage/src/state_store/mod.rs
  pnpm-lock.yaml
  scripts/build_webuis.sh
  utilities/db_inspector/src/webserver/server.rs
  utilities/db_inspector/web_ui/src/routes/InspectCf.tsx
Labels: P-acks_required, P-reviews_required

#1420 fix(wallet): update indexer port
  applications/tari_dan_app_utilities/config_presets/e_dan_wallet_daemon.toml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#1421 feat: add VN command to compact the database
  applications/tari_dan_wallet_daemon/build.rs
  applications/tari_validator_node/src/cli.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/lib.rs
  applications/tari_validator_node/src/main.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  bindings/package.json
  dan_layer/consensus/src/hotstuff/on_ready_to_vote_on_local_block.rs
  dan_layer/consensus/src/hotstuff/pacemaker.rs
  dan_layer/p2p/proto/rpc.proto
  dan_layer/rpc_state_sync/src/state_sync.rs
  dan_layer/state_store_rocksdb/src/reader.rs
  dan_layer/state_store_rocksdb/src/store.rs
  dan_layer/state_store_rocksdb/src/writer.rs
  dan_layer/storage/src/consensus_models/epoch_checkpoint.rs
  scripts/build_webuis.sh
  utilities/db_inspector/src/webserver/handlers/column_families.rs
  utilities/db_inspector/src/webserver/handlers/mod.rs
  utilities/db_inspector/src/webserver/server.rs
  utilities/db_inspector/web_ui/src/routes/ListColumnFamilies.tsx
  utilities/db_inspector/web_ui/src/store/databases.ts
Labels: P-acks_required, P-reviews_required

#1427 feat(wallet)!: prevent dry run transactions submitted as real
  applications/tari_dan_wallet_daemon/src/handlers/accounts.rs
  applications/tari_dan_wallet_daemon/src/handlers/nfts.rs
  applications/tari_dan_wallet_daemon/src/handlers/transaction.rs
  applications/tari_indexer/src/dry_run/error.rs
  applications/tari_indexer/src/dry_run/processor.rs
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/transaction_validators/dry_run.rs
  applications/tari_validator_node/src/transaction_validators/error.rs
  applications/tari_validator_node/src/transaction_validators/mod.rs
  applications/tari_validator_node/src/transaction_validators/network.rs
  bindings/src/types/UnsignedTransactionV1.ts
  dan_layer/transaction/src/builder.rs
  dan_layer/transaction/src/transaction.rs
  dan_layer/transaction/src/unsigned_transaction.rs
  dan_layer/transaction/src/v1/transaction.rs
  dan_layer/transaction/src/v1/unsealed.rs
  dan_layer/transaction/src/v1/unsigned.rs
  dan_layer/wallet/sdk/src/apis/confidential_transfer.rs
  dan_layer/wallet/storage_sqlite/src/models/transaction.rs
Labels: P-acks_required, P-reviews_required

#1438 fix(consensus)!: periodic epoch GC, catch up bug, use smallvec
  Cargo.lock
  Cargo.toml
  applications/tari_validator_node/src/bootstrap.rs
  applications/tari_validator_node/src/consensus/mod.rs
  applications/tari_validator_node/src/p2p/rpc/block_sync_task.rs
  applications/tari_validator_node/src/p2p/rpc/mod.rs
  applications/tari_validator_node/src/p2p/rpc/service_impl.rs
  applications/tari_validator_node/src/p2p/services/mempool/service.rs
  dan_layer/consensus/src/hotstuff/config.rs
  dan_layer/consensus/src/hotstuff/epoch_gc.rs
  dan_layer/consensus/src/hotstuff/error.rs
  dan_layer/consensus/src/hotstuff/mod.rs
  dan_layer/consensus/src/hotstuff/on_inbound_message.rs
  dan_layer/consensus/src/hotstuff/on_next_sync_view.rs
  dan_layer/consensus/src/hotstuff/on_propose.rs
  dan_layer/consensus/src/hotstuff/on_receive_local_proposal.rs
  dan_layer/consensus/src/hotstuff/state_tree_gc.rs
  dan_layer/consensus/src/hotstuff/worker.rs
  dan_layer/consensus/src/traits/certificate.rs
  dan_layer/consensus/src/traits/mod.rs
  dan_layer/consensus/src/traits/tasks.rs
  dan_layer/consensus_tests/src/support/harness.rs
  dan_layer/p2p/proto/rpc.proto
  dan_layer/state_store_rocksdb/Cargo.toml
  dan_layer/state_store_rocksdb/src/cf_api.rs
  dan_layer/state_store_rocksdb/src/codecs/mod.rs
  dan_layer/state_store_rocksdb/src/codecs/small_bytes.rs
  dan_layer/state_store_rocksdb/src/codecs/time.rs
  dan_layer/state_store_rocksdb/src/column_families/block.rs
  dan_layer/state_store_rocksdb/src/column_families/block_transaction_execution.rs
  dan_layer/state_store_rocksdb/src/column_families/certificates.rs
  dan_layer/state_store_rocksdb/src/column_families/finalized_transaction.rs
  dan_layer/state_store_rocksdb/src/options.rs
  dan_layer/state_store_rocksdb/src/reader.rs
  dan_layer/state_store_rocksdb/src/store.rs
  dan_layer/state_store_rocksdb/src/writer.rs
  dan_layer/state_store_tests/src/quorum_certificates.rs
  dan_layer/state_store_tests/src/transactions.rs
  dan_layer/storage/src/consensus_models/block.rs
  dan_layer/storage/src/consensus_models/foreign_proposal.rs
  dan_layer/storage/src/consensus_models/substate.rs
  dan_layer/storage/src/state_store/mod.rs
  dan_layer/validator_node_rpc/src/rpc_service.rs
  utilities/db_inspector/src/webserver/handlers/tables.rs
  utilities/db_inspector/src/webserver/server.rs
Labels: P-acks_required, P-reviews_required

#1441 chore: update bindigngs 1.8.0
  applications/tari_dan_wallet_daemon/web_ui/package.json
  applications/tari_indexer/web_ui/package.json
  applications/tari_validator_node/web_ui/package.json
  bindings/package.json
  clients/javascript/wallet_daemon_client/package.json
Labels: CR-insufficient_context

#1442 fix(bindings): include declarations and enable composite
  bindings/package.json
  bindings/tsconfig.json
  bindings/tsconfig.prod.json
Labels: P-acks_required, P-reviews_required

#1444 feat: adds hybrid epoch oracle
  applications/tari_dan_app_utilities/src/epoch_oracle_config.rs
  applications/tari_indexer/src/bootstrap.rs
  applications/tari_validator_node/src/bootstrap.rs
  dan_layer/epoch_oracles/src/base_layer/mod.rs
  dan_layer/epoch_oracles/src/hybrid/mod.rs
  dan_layer/epoch_oracles/src/hybrid/oracle.rs
  dan_layer/epoch_oracles/src/lib.rs
  utilities/db_inspector/src/webserver/handlers/tables.rs
  utilities/db_inspector/src/webserver/handlers/types.rs
  utilities/db_inspector/web_ui/src/routes/InspectCf.tsx
Labels: P-acks_required, P-reviews_required

#1445 fix(engine): upgrade to wasmer 6
  Cargo.lock
  Cargo.toml
  dan_layer/engine/src/wasm/limiting_tunable.rs
  dan_layer/engine/src/wasm/metering.rs
  dan_layer/engine/src/wasm/module.rs
Labels: P-acks_required, P-reviews_required
